import type { ProjectParams } from '@/lib/calculations';
import { DEMO_PROJECT_ID } from './constants';

/**
 * Complete Copper Mine Demo — a realistic open-pit copper feasibility study
 * so public visitors can explore every analysis module immediately.
 */
export interface DemoProjectDefinition {
  id: string;
  name: string;
  mineType: string;
  miningMethod: string;
  location: string;
  currency: string;
  exchangeRate: number;
  fuelPricePerLiter: number;
  electricityUnitPrice: number;
  explosiveUnitPrice: number;
  totalReserves: number;
  maxAnnualCapacity: number;
  oreGrade: number;
  oreGradeUnit: string;
  waterConsumptionDaily: number;
  rehabilitationAreaHa: number;
  rehabilitationCostPerHa: number;
  loanAmount: number;
  loanInterestRate: number;
  loanTermYears: number;
  equityRatio: number;
  depreciationMethod: string;
  equipmentRenewalEnabled: boolean;
  equipmentRenewalCycleYears: number;
  latitude: number;
  longitude: number;
  params: ProjectParams;
  equipments: Record<string, unknown>[];
  personnels: Record<string, unknown>[];
  byProducts: Record<string, unknown>[];
  methodCosts: Record<string, unknown>[];
}

export const COPPER_MINE_DEMO: DemoProjectDefinition = {
  id: DEMO_PROJECT_ID,
  name: 'Copper Mine Demo',
  mineType: 'copper',
  miningMethod: 'openPit',
  location: 'Atacama Region, Chile (demo)',
  currency: 'USD',
  exchangeRate: 1.0,
  fuelPricePerLiter: 1.35,
  electricityUnitPrice: 0.09,
  explosiveUnitPrice: 1.85,
  totalReserves: 120,
  maxAnnualCapacity: 6.0,
  oreGrade: 0.65,
  oreGradeUnit: '%',
  waterConsumptionDaily: 2800,
  rehabilitationAreaHa: 420,
  rehabilitationCostPerHa: 18000,
  loanAmount: 280,
  loanInterestRate: 6.5,
  loanTermYears: 12,
  equityRatio: 45,
  depreciationMethod: 'linear',
  equipmentRenewalEnabled: true,
  equipmentRenewalCycleYears: 10,
  latitude: -22.9083,
  longitude: -69.1894,
  params: {
    projectLifeYears: 25,
    discountRate: 8.0,
    taxRate: 25,
    royaltyRate: 5,
    creditRate: 6.5,
    creditYears: 12,
    unitPrice: 9200,
    annualProduction: 0.085,
    plantProcessingRate: 92,
    equipmentCost: 185,
    facilityCost: 320,
    infrastructureCost: 95,
    contingencyRate: 12,
    totalCapex: 672.0,
    fuelCost: 18.5,
    personnelCost: 22.0,
    maintenanceCost: 14.5,
    explosivesCost: 8.2,
    tireCost: 3.5,
    strippingCost: 28.0,
    otherOpex: 6.5,
    totalOpex: 101.2,
    forestCost: 2.5,
    landCost: 4.0,
    rehabilitationCost: 12.0,
    annualStrippingVolume: 42,
    strippingUnitCost: 1.85,
    contractorStrippingCost: 0,
    plantOperatingCost: 35.0,
    equipmentDepLife: 8,
    facilityDepLife: 20,
    byProductRevenue: 18.5,
    fuelPricePerLiter: 1.35,
    electricityUnitPrice: 0.09,
    totalReserves: 120,
    oreGrade: 0.65,
    waterConsumptionDaily: 2800,
    rehabilitationAreaHa: 420,
    rehabilitationCostPerHa: 18000,
    loanAmount: 280,
    loanInterestRate: 6.5,
    loanTermYears: 12,
    equityRatio: 45,
  },
  equipments: [
    {
      machineType: 'Caterpillar 793F Haul Truck',
      equipmentCategory: 'truck',
      model: '793F',
      tonnageCapacity: '227 ton',
      quantity: 14,
      spareQuantity: 2,
      unitCost: 3_800_000,
      totalCost: 60_800_000,
      dailyWorkHours: 20,
      maintenancePeriodHours: 500,
      operatorCount: 1,
      powerType: 'diesel',
      hourlyFuelConsumption: 75,
      maintenanceCost: 95_000,
      fuelConsumption: 75,
      productionImpact: 500,
      transportCapacity: 227,
    },
    {
      machineType: 'Liebherr R 9800 Excavator',
      equipmentCategory: 'excavator',
      model: 'R 9800',
      tonnageCapacity: '800 ton class',
      quantity: 2,
      spareQuantity: 0,
      unitCost: 12_000_000,
      totalCost: 24_000_000,
      dailyWorkHours: 20,
      maintenancePeriodHours: 400,
      operatorCount: 2,
      powerType: 'diesel',
      hourlyFuelConsumption: 160,
      maintenanceCost: 280_000,
      fuelConsumption: 160,
      productionImpact: 900,
      bucketVolume: 42,
    },
    {
      machineType: 'Komatsu PC2000-11 Excavator',
      equipmentCategory: 'excavator',
      model: 'PC2000-11',
      tonnageCapacity: '200 ton class',
      quantity: 3,
      spareQuantity: 1,
      unitCost: 2_800_000,
      totalCost: 11_200_000,
      dailyWorkHours: 18,
      maintenancePeriodHours: 500,
      operatorCount: 1,
      powerType: 'diesel',
      hourlyFuelConsumption: 85,
      maintenanceCost: 72_000,
      fuelConsumption: 85,
      productionImpact: 450,
      bucketVolume: 12,
    },
    {
      machineType: 'Caterpillar 994K Wheel Loader',
      equipmentCategory: 'loader',
      model: '994K',
      tonnageCapacity: '56 ton',
      quantity: 2,
      spareQuantity: 0,
      unitCost: 2_900_000,
      totalCost: 5_800_000,
      dailyWorkHours: 16,
      maintenancePeriodHours: 500,
      operatorCount: 1,
      powerType: 'diesel',
      hourlyFuelConsumption: 55,
      maintenanceCost: 68_000,
      fuelConsumption: 55,
      productionImpact: 420,
      loadingCapacity: 420,
      bucketVolume: 14,
    },
    {
      machineType: 'Caterpillar D11 Dozer',
      equipmentCategory: 'dozer',
      model: 'D11',
      tonnageCapacity: '104 ton',
      quantity: 3,
      spareQuantity: 1,
      unitCost: 1_850_000,
      totalCost: 7_400_000,
      dailyWorkHours: 16,
      maintenancePeriodHours: 500,
      operatorCount: 1,
      powerType: 'diesel',
      hourlyFuelConsumption: 62,
      maintenanceCost: 55_000,
      fuelConsumption: 62,
      productionImpact: 0,
    },
    {
      machineType: 'Epiroc Pit Viper 271 Drill',
      equipmentCategory: 'drill',
      model: 'Pit Viper 271',
      tonnageCapacity: '',
      quantity: 3,
      spareQuantity: 1,
      unitCost: 2_200_000,
      totalCost: 8_800_000,
      dailyWorkHours: 16,
      maintenancePeriodHours: 400,
      operatorCount: 1,
      powerType: 'diesel',
      hourlyFuelConsumption: 48,
      maintenanceCost: 62_000,
      fuelConsumption: 48,
      productionImpact: 28,
      drillCapacity: 28,
      holeDiameter: 270,
      maxDrillDepth: 60,
    },
    {
      machineType: 'Metso Primary Crusher',
      equipmentCategory: 'crusher',
      model: 'C160',
      tonnageCapacity: '1200 tph',
      quantity: 1,
      spareQuantity: 0,
      unitCost: 4_500_000,
      totalCost: 4_500_000,
      dailyWorkHours: 22,
      maintenancePeriodHours: 600,
      operatorCount: 2,
      powerType: 'electric',
      hourlyFuelConsumption: 0,
      maintenanceCost: 85_000,
      fuelConsumption: 0,
      productionImpact: 900,
      crushingCapacity: 900,
    },
  ],
  personnels: [
    { role: 'Mine Manager', count: 1, monthlySalary: 12_000 },
    { role: 'Mining Engineer', count: 4, monthlySalary: 6_500 },
    { role: 'Geologist', count: 3, monthlySalary: 5_800 },
    { role: 'Metallurgist', count: 2, monthlySalary: 6_200 },
    { role: 'Environmental Engineer', count: 2, monthlySalary: 5_500 },
    { role: 'Shift Supervisor', count: 6, monthlySalary: 4_200 },
    { role: 'Haul Truck Operator', count: 28, monthlySalary: 3_400 },
    { role: 'Excavator Operator', count: 10, monthlySalary: 3_600 },
    { role: 'Drill Operator', count: 6, monthlySalary: 3_500 },
    { role: 'Maintenance Technician', count: 16, monthlySalary: 3_800 },
    { role: 'Plant Operator', count: 12, monthlySalary: 3_200 },
    { role: 'Electrician', count: 6, monthlySalary: 3_600 },
    { role: 'Safety / Rescue', count: 8, monthlySalary: 3_000 },
    { role: 'Admin / HR', count: 6, monthlySalary: 2_800 },
  ],
  byProducts: [
    {
      name: 'Gold (by-product)',
      annualProduction: 1_800,
      productionUnit: 'kg',
      unitPrice: 65,
      priceUnit: 'USD/g',
      totalRevenue: 7.02,
    },
    {
      name: 'Silver (by-product)',
      annualProduction: 28_000,
      productionUnit: 'kg',
      unitPrice: 0.95,
      priceUnit: 'USD/g',
      totalRevenue: 1.596,
    },
    {
      name: 'Molybdenum',
      annualProduction: 420,
      productionUnit: 'ton',
      unitPrice: 28_000,
      priceUnit: 'USD/ton',
      totalRevenue: 11.76,
    },
  ],
  methodCosts: [
    { name: 'Waste dump construction', category: 'openPit', value: 8.5, unit: 'MUSD' },
    { name: 'Stripping / overburden', category: 'openPit', value: 28.0, unit: 'MUSD' },
    { name: 'Drilling & blasting', category: 'openPit', value: 6.2, unit: 'MUSD' },
    { name: 'Haul road construction', category: 'openPit', value: 4.8, unit: 'MUSD' },
    { name: 'Dewatering', category: 'openPit', value: 3.5, unit: 'MUSD' },
    { name: 'Pit slope monitoring', category: 'openPit', value: 1.2, unit: 'MUSD' },
  ],
};
