import type { DemoProjectDefinition } from '../types';
import { buildParams, equipmentRow, standardMineStaff } from '../helpers';

/** Australia underground metallurgical / thermal coal longwall operation. */
export const COAL_AUSTRALIA_DEMO: DemoProjectDefinition = {
  id: 'demo-coal-australia',
  name: 'Hunter Valley Coal Project',
  mineType: 'coal',
  miningMethod: 'underground',
  location: 'New South Wales, Australia',
  country: 'Australia',
  productionLabel: '4.2 Mtpa coal',
  accent: 'coal',
  currency: 'USD',
  exchangeRate: 1.0,
  fuelPricePerLiter: 1.42,
  electricityUnitPrice: 0.1,
  explosiveUnitPrice: 1.7,
  totalReserves: 95,
  maxAnnualCapacity: 5.0,
  oreGrade: 6_800,
  oreGradeUnit: 'kcal/kg',
  strippingRatio: 0,
  recoveryPercent: 82,
  waterConsumptionDaily: 1_600,
  rehabilitationAreaHa: 220,
  rehabilitationCostPerHa: 22_000,
  loanAmount: 180,
  loanInterestRate: 6.0,
  loanTermYears: 10,
  equityRatio: 48,
  depreciationMethod: 'linear',
  equipmentRenewalEnabled: true,
  equipmentRenewalCycleYears: 10,
  latitude: -32.55,
  longitude: 151.05,
  params: buildParams({
    projectLifeYears: 20,
    discountRate: 8.0,
    taxRate: 30,
    royaltyRate: 8,
    creditRate: 6.0,
    creditYears: 10,
    unitPrice: 145,
    annualProduction: 4.2,
    plantProcessingRate: 85,
    equipmentCost: 195,
    facilityCost: 140,
    infrastructureCost: 75,
    contingencyRate: 12,
    fuelCost: 12,
    personnelCost: 32,
    maintenanceCost: 22,
    explosivesCost: 3.5,
    tireCost: 1.8,
    strippingCost: 0,
    otherOpex: 9.5,
    forestCost: 2.5,
    landCost: 4.0,
    rehabilitationCost: 9.0,
    annualStrippingVolume: 0,
    strippingUnitCost: 0,
    contractorStrippingCost: 0,
    plantOperatingCost: 28,
    equipmentDepLife: 8,
    facilityDepLife: 18,
    byProductRevenue: 0,
    fuelPricePerLiter: 1.42,
    electricityUnitPrice: 0.1,
    totalReserves: 95,
    oreGrade: 6_800,
    waterConsumptionDaily: 1_600,
    rehabilitationAreaHa: 220,
    rehabilitationCostPerHa: 22_000,
    loanAmount: 180,
    loanInterestRate: 6.0,
    loanTermYears: 10,
    equityRatio: 48,
  }),
  equipments: [
    equipmentRow({
      machineType: 'Caterpillar EL3000 Longwall Shearer',
      equipmentCategory: 'underground',
      model: 'EL3000',
      tonnageCapacity: '3500 tph',
      quantity: 1,
      unitCost: 12_500_000,
      dailyWorkHours: 20,
      powerType: 'electric',
      maintenanceCost: 280_000,
      productionImpact: 2_200,
    }),
    equipmentRow({
      machineType: 'Komatsu 12CM27 Continuous Miner',
      equipmentCategory: 'underground',
      model: '12CM27',
      tonnageCapacity: '45 tpm',
      quantity: 3,
      spareQuantity: 1,
      unitCost: 4_800_000,
      dailyWorkHours: 18,
      powerType: 'electric',
      maintenanceCost: 145_000,
      productionImpact: 850,
    }),
    equipmentRow({
      machineType: 'Sandvik MB650 Bolter Miner',
      equipmentCategory: 'underground',
      model: 'MB650',
      quantity: 2,
      unitCost: 3_600_000,
      powerType: 'electric',
      maintenanceCost: 95_000,
      productionImpact: 400,
    }),
    equipmentRow({
      machineType: 'Caterpillar AD45 Underground Truck',
      equipmentCategory: 'truck',
      model: 'AD45',
      tonnageCapacity: '45 ton',
      quantity: 8,
      spareQuantity: 2,
      unitCost: 1_150_000,
      gallerySuitability: '5.0 x 5.0 m',
      hourlyFuelConsumption: 35,
      fuelConsumption: 35,
      maintenanceCost: 42_000,
      productionImpact: 260,
      transportCapacity: 45,
    }),
    equipmentRow({
      machineType: 'Epiroc Scooptram ST18',
      equipmentCategory: 'loader',
      model: 'ST18',
      tonnageCapacity: '18 ton',
      quantity: 4,
      unitCost: 1_050_000,
      hourlyFuelConsumption: 26,
      fuelConsumption: 26,
      maintenanceCost: 38_000,
      productionImpact: 200,
      loadingCapacity: 200,
      bucketVolume: 7.0,
    }),
    equipmentRow({
      machineType: 'Metso Coal Prep Dense Media Circuit',
      equipmentCategory: 'crusher',
      model: 'DMS-2400',
      tonnageCapacity: '800 tph',
      quantity: 1,
      unitCost: 6_200_000,
      dailyWorkHours: 20,
      powerType: 'electric',
      maintenanceCost: 110_000,
      productionImpact: 700,
      crushingCapacity: 700,
    }),
  ],
  personnels: [
    ...standardMineStaff('large'),
    { role: 'Longwall Operator', count: 16, monthlySalary: 4_800 },
    { role: 'Continuous Miner Operator', count: 12, monthlySalary: 4_500 },
    { role: 'Underground Miner', count: 55, monthlySalary: 4_000 },
  ],
  byProducts: [],
  methodCosts: [
    { name: 'Longwall face equipment', category: 'underground', value: 85, unit: 'MUSD' },
    { name: 'Gate road development', category: 'underground', value: 32, unit: 'MUSD' },
    { name: 'Ventilation & gas drainage', category: 'underground', value: 22, unit: 'MUSD' },
    { name: 'Coal preparation plant', category: 'underground', value: 48, unit: 'MUSD' },
    { name: 'Subsidence management', category: 'underground', value: 6.5, unit: 'MUSD' },
  ],
};
