import type { DemoProjectDefinition } from '../types';
import { buildParams, equipmentRow, standardMineStaff } from '../helpers';

/** Chile open-pit copper porphyry — mid-tier Andean operation. */
export const COPPER_CHILE_DEMO: DemoProjectDefinition = {
  id: 'demo-copper-mine',
  name: 'Atacama Copper Project',
  mineType: 'copper',
  miningMethod: 'openPit',
  location: 'Atacama Region, Chile',
  country: 'Chile',
  productionLabel: '85 ktpa Cu',
  accent: 'copper',
  currency: 'USD',
  exchangeRate: 1.0,
  fuelPricePerLiter: 1.35,
  electricityUnitPrice: 0.09,
  explosiveUnitPrice: 1.85,
  totalReserves: 120,
  maxAnnualCapacity: 6.0,
  oreGrade: 0.65,
  oreGradeUnit: '%',
  strippingRatio: 2.8,
  recoveryPercent: 88,
  waterConsumptionDaily: 2800,
  rehabilitationAreaHa: 420,
  rehabilitationCostPerHa: 18000,
  loanAmount: 280,
  loanInterestRate: 6.5,
  loanTermYears: 12,
  equityRatio: 45,
  depreciationMethod: 'linear',
  equipmentRenewalEnabled: true,
  equipmentRenewalCycleYears: 10,
  latitude: -22.9083,
  longitude: -69.1894,
  params: buildParams({
    projectLifeYears: 25,
    discountRate: 8.0,
    taxRate: 25,
    royaltyRate: 5,
    creditRate: 6.5,
    creditYears: 12,
    unitPrice: 9200,
    annualProduction: 0.085,
    plantProcessingRate: 92,
    equipmentCost: 185,
    facilityCost: 320,
    infrastructureCost: 95,
    contingencyRate: 12,
    fuelCost: 18.5,
    personnelCost: 22.0,
    maintenanceCost: 14.5,
    explosivesCost: 8.2,
    tireCost: 3.5,
    strippingCost: 28.0,
    otherOpex: 6.5,
    forestCost: 2.5,
    landCost: 4.0,
    rehabilitationCost: 12.0,
    annualStrippingVolume: 42,
    strippingUnitCost: 1.85,
    contractorStrippingCost: 0,
    plantOperatingCost: 35.0,
    equipmentDepLife: 8,
    facilityDepLife: 20,
    byProductRevenue: 18.5,
    fuelPricePerLiter: 1.35,
    electricityUnitPrice: 0.09,
    totalReserves: 120,
    oreGrade: 0.65,
    waterConsumptionDaily: 2800,
    rehabilitationAreaHa: 420,
    rehabilitationCostPerHa: 18000,
    loanAmount: 280,
    loanInterestRate: 6.5,
    loanTermYears: 12,
    equityRatio: 45,
  }),
  equipments: [
    equipmentRow({
      machineType: 'Caterpillar 793F Haul Truck',
      equipmentCategory: 'truck',
      model: '793F',
      tonnageCapacity: '227 ton',
      quantity: 14,
      spareQuantity: 2,
      unitCost: 3_800_000,
      dailyWorkHours: 20,
      operatorCount: 1,
      hourlyFuelConsumption: 75,
      fuelConsumption: 75,
      maintenanceCost: 95_000,
      productionImpact: 500,
      transportCapacity: 227,
    }),
    equipmentRow({
      machineType: 'Liebherr R 9800 Excavator',
      equipmentCategory: 'excavator',
      model: 'R 9800',
      tonnageCapacity: '800 ton class',
      quantity: 2,
      unitCost: 12_000_000,
      dailyWorkHours: 20,
      maintenancePeriodHours: 400,
      operatorCount: 2,
      hourlyFuelConsumption: 160,
      fuelConsumption: 160,
      maintenanceCost: 280_000,
      productionImpact: 900,
      bucketVolume: 42,
    }),
    equipmentRow({
      machineType: 'Komatsu PC2000-11 Excavator',
      equipmentCategory: 'excavator',
      model: 'PC2000-11',
      tonnageCapacity: '200 ton class',
      quantity: 3,
      spareQuantity: 1,
      unitCost: 2_800_000,
      dailyWorkHours: 18,
      hourlyFuelConsumption: 85,
      fuelConsumption: 85,
      maintenanceCost: 72_000,
      productionImpact: 450,
      bucketVolume: 12,
    }),
    equipmentRow({
      machineType: 'Caterpillar 994K Wheel Loader',
      equipmentCategory: 'loader',
      model: '994K',
      tonnageCapacity: '56 ton',
      quantity: 2,
      unitCost: 2_900_000,
      hourlyFuelConsumption: 55,
      fuelConsumption: 55,
      maintenanceCost: 68_000,
      productionImpact: 420,
      loadingCapacity: 420,
      bucketVolume: 14,
    }),
    equipmentRow({
      machineType: 'Caterpillar D11 Dozer',
      equipmentCategory: 'dozer',
      model: 'D11',
      tonnageCapacity: '104 ton',
      quantity: 3,
      spareQuantity: 1,
      unitCost: 1_850_000,
      hourlyFuelConsumption: 62,
      fuelConsumption: 62,
      maintenanceCost: 55_000,
    }),
    equipmentRow({
      machineType: 'Epiroc Pit Viper 271 Drill',
      equipmentCategory: 'drill',
      model: 'Pit Viper 271',
      quantity: 3,
      spareQuantity: 1,
      unitCost: 2_200_000,
      maintenancePeriodHours: 400,
      hourlyFuelConsumption: 48,
      fuelConsumption: 48,
      maintenanceCost: 62_000,
      productionImpact: 28,
      drillCapacity: 28,
      holeDiameter: 270,
      maxDrillDepth: 60,
    }),
    equipmentRow({
      machineType: 'Metso Nordberg C160 Jaw Crusher',
      equipmentCategory: 'crusher',
      model: 'C160',
      tonnageCapacity: '1200 tph',
      quantity: 1,
      unitCost: 4_500_000,
      dailyWorkHours: 22,
      maintenancePeriodHours: 600,
      operatorCount: 2,
      powerType: 'electric',
      maintenanceCost: 85_000,
      productionImpact: 900,
      crushingCapacity: 900,
    }),
  ],
  personnels: [
    ...standardMineStaff('large'),
    { role: 'Haul Truck Operator', count: 28, monthlySalary: 3_400 },
    { role: 'Excavator Operator', count: 10, monthlySalary: 3_600 },
    { role: 'Drill Operator', count: 6, monthlySalary: 3_500 },
  ],
  byProducts: [
    {
      name: 'Gold (by-product)',
      annualProduction: 1_800,
      productionUnit: 'kg',
      unitPrice: 65,
      priceUnit: 'USD/g',
      totalRevenue: 7.02,
    },
    {
      name: 'Silver (by-product)',
      annualProduction: 28_000,
      productionUnit: 'kg',
      unitPrice: 0.95,
      priceUnit: 'USD/g',
      totalRevenue: 1.596,
    },
    {
      name: 'Molybdenum',
      annualProduction: 420,
      productionUnit: 'ton',
      unitPrice: 28_000,
      priceUnit: 'USD/ton',
      totalRevenue: 11.76,
    },
  ],
  methodCosts: [
    { name: 'Waste dump construction', category: 'openPit', value: 8.5, unit: 'MUSD' },
    { name: 'Stripping / overburden', category: 'openPit', value: 28.0, unit: 'MUSD' },
    { name: 'Drilling & blasting', category: 'openPit', value: 6.2, unit: 'MUSD' },
    { name: 'Haul road construction', category: 'openPit', value: 4.8, unit: 'MUSD' },
    { name: 'Dewatering', category: 'openPit', value: 3.5, unit: 'MUSD' },
    { name: 'Pit slope monitoring', category: 'openPit', value: 1.2, unit: 'MUSD' },
  ],
};
