import type { DemoProjectDefinition } from '../types';
import { buildParams, equipmentRow, standardMineStaff } from '../helpers';

/**
 * Türkiye underground gold — orogenic vein system.
 * Economics expressed on ore throughput with Au NSR unit price:
 * ~0.55 Mtpa @ 4.8 g/t Au, 91% recovery ≈ 2,400 kg Au → NSR ≈ $280/t ore.
 */
export const GOLD_TURKIYE_DEMO: DemoProjectDefinition = {
  id: 'demo-gold-turkiye',
  name: 'Anatolia Gold Project',
  mineType: 'gold',
  miningMethod: 'underground',
  location: 'İzmir Province, Türkiye',
  country: 'Türkiye',
  productionLabel: '2.4 tpa Au',
  accent: 'gold',
  currency: 'USD',
  exchangeRate: 1.0,
  fuelPricePerLiter: 1.45,
  electricityUnitPrice: 0.11,
  explosiveUnitPrice: 2.4,
  totalReserves: 8.5,
  maxAnnualCapacity: 0.7,
  oreGrade: 4.8,
  oreGradeUnit: 'g/t',
  strippingRatio: 0,
  recoveryPercent: 91,
  waterConsumptionDaily: 950,
  rehabilitationAreaHa: 65,
  rehabilitationCostPerHa: 32_000,
  loanAmount: 95,
  loanInterestRate: 7.5,
  loanTermYears: 10,
  equityRatio: 40,
  depreciationMethod: 'linear',
  equipmentRenewalEnabled: true,
  equipmentRenewalCycleYears: 8,
  latitude: 39.12,
  longitude: 27.18,
  params: buildParams({
    projectLifeYears: 15,
    discountRate: 9.0,
    taxRate: 25,
    royaltyRate: 4,
    creditRate: 7.5,
    creditYears: 10,
    unitPrice: 280,
    annualProduction: 0.55,
    plantProcessingRate: 94,
    equipmentCost: 72,
    facilityCost: 95,
    infrastructureCost: 38,
    contingencyRate: 14,
    fuelCost: 6.8,
    personnelCost: 18.5,
    maintenanceCost: 9.2,
    explosivesCost: 4.5,
    tireCost: 0.6,
    strippingCost: 0,
    otherOpex: 5.4,
    forestCost: 1.2,
    landCost: 2.0,
    rehabilitationCost: 4.5,
    annualStrippingVolume: 0,
    strippingUnitCost: 0,
    contractorStrippingCost: 0,
    plantOperatingCost: 22.0,
    equipmentDepLife: 7,
    facilityDepLife: 15,
    byProductRevenue: 8.5,
    fuelPricePerLiter: 1.45,
    electricityUnitPrice: 0.11,
    totalReserves: 8.5,
    oreGrade: 4.8,
    waterConsumptionDaily: 950,
    rehabilitationAreaHa: 65,
    rehabilitationCostPerHa: 32_000,
    loanAmount: 95,
    loanInterestRate: 7.5,
    loanTermYears: 10,
    equityRatio: 40,
  }),
  equipments: [
    equipmentRow({
      machineType: 'Sandvik LH621i LHD',
      equipmentCategory: 'loader',
      model: 'LH621i',
      tonnageCapacity: '21 ton',
      quantity: 6,
      spareQuantity: 1,
      unitCost: 1_450_000,
      dailyWorkHours: 18,
      gallerySuitability: '5.0 x 5.0 m',
      hourlyFuelConsumption: 28,
      fuelConsumption: 28,
      maintenanceCost: 48_000,
      productionImpact: 280,
      loadingCapacity: 280,
      bucketVolume: 8.5,
    }),
    equipmentRow({
      machineType: 'Sandvik TH663i Underground Truck',
      equipmentCategory: 'truck',
      model: 'TH663i',
      tonnageCapacity: '63 ton',
      quantity: 8,
      spareQuantity: 1,
      unitCost: 1_650_000,
      dailyWorkHours: 18,
      gallerySuitability: '5.5 x 5.5 m',
      hourlyFuelConsumption: 42,
      fuelConsumption: 42,
      maintenanceCost: 52_000,
      productionImpact: 320,
      transportCapacity: 63,
    }),
    equipmentRow({
      machineType: 'Epiroc Boomer M2 Jumbo',
      equipmentCategory: 'drill',
      model: 'Boomer M2',
      quantity: 4,
      spareQuantity: 1,
      unitCost: 980_000,
      dailyWorkHours: 16,
      maintenancePeriodHours: 400,
      gallerySuitability: '4.5 x 4.5 m',
      powerType: 'electric',
      maintenanceCost: 38_000,
      productionImpact: 45,
      drillCapacity: 45,
      holeDiameter: 45,
      maxDrillDepth: 4.2,
    }),
    equipmentRow({
      machineType: 'Atlas Copco Simba S7 Production Drill',
      equipmentCategory: 'drill',
      model: 'Simba S7',
      quantity: 2,
      unitCost: 1_250_000,
      powerType: 'electric',
      maintenanceCost: 42_000,
      productionImpact: 55,
      drillCapacity: 55,
      holeDiameter: 76,
      maxDrillDepth: 32,
    }),
    equipmentRow({
      machineType: 'Sandvik DS412i Bolter',
      equipmentCategory: 'underground',
      model: 'DS412i',
      quantity: 3,
      unitCost: 890_000,
      powerType: 'electric',
      maintenanceCost: 28_000,
      productionImpact: 0,
    }),
    equipmentRow({
      machineType: 'Metso Vertimill VTM-3000',
      equipmentCategory: 'crusher',
      model: 'VTM-3000',
      tonnageCapacity: '180 tph',
      quantity: 1,
      unitCost: 3_200_000,
      dailyWorkHours: 22,
      powerType: 'electric',
      maintenanceCost: 75_000,
      productionImpact: 160,
      crushingCapacity: 160,
    }),
  ],
  personnels: [
    ...standardMineStaff('medium'),
    { role: 'LHD Operator', count: 14, monthlySalary: 3_600 },
    { role: 'Jumbo Operator', count: 8, monthlySalary: 3_800 },
    { role: 'Underground Miner', count: 32, monthlySalary: 3_200 },
  ],
  byProducts: [
    {
      name: 'Silver',
      annualProduction: 12_000,
      productionUnit: 'kg',
      unitPrice: 0.9,
      priceUnit: 'USD/g',
      totalRevenue: 6.48,
    },
    {
      name: 'Copper concentrate',
      annualProduction: 1_800,
      productionUnit: 'ton',
      unitPrice: 1_100,
      priceUnit: 'USD/ton',
      totalRevenue: 1.98,
    },
  ],
  methodCosts: [
    { name: 'Decline & lateral development', category: 'underground', value: 28.0, unit: 'MUSD' },
    { name: 'Ground support / bolting', category: 'underground', value: 9.5, unit: 'MUSD' },
    { name: 'Ventilation & refrigeration', category: 'underground', value: 7.2, unit: 'MUSD' },
    { name: 'Backfill plant', category: 'underground', value: 6.8, unit: 'MUSD' },
    { name: 'Paste fill operating', category: 'underground', value: 4.1, unit: 'MUSD' },
  ],
};
