import type { DemoProjectDefinition } from '../types';
import { buildParams, equipmentRow, standardMineStaff } from '../helpers';

/** Brazil Carajás-style open-pit high-grade iron ore. */
export const IRON_BRAZIL_DEMO: DemoProjectDefinition = {
  id: 'demo-iron-brazil',
  name: 'Carajás Iron Project',
  mineType: 'iron',
  miningMethod: 'openPit',
  location: 'Pará, Brazil',
  country: 'Brazil',
  productionLabel: '12 Mtpa Fe ore',
  accent: 'iron',
  currency: 'USD',
  exchangeRate: 1.0,
  fuelPricePerLiter: 1.28,
  electricityUnitPrice: 0.07,
  explosiveUnitPrice: 1.55,
  totalReserves: 280,
  maxAnnualCapacity: 14,
  oreGrade: 65,
  oreGradeUnit: '% Fe',
  strippingRatio: 1.4,
  recoveryPercent: 94,
  waterConsumptionDaily: 4_500,
  rehabilitationAreaHa: 980,
  rehabilitationCostPerHa: 14_000,
  loanAmount: 520,
  loanInterestRate: 6.0,
  loanTermYears: 14,
  equityRatio: 50,
  depreciationMethod: 'linear',
  equipmentRenewalEnabled: true,
  equipmentRenewalCycleYears: 10,
  latitude: -6.06,
  longitude: -50.15,
  params: buildParams({
    projectLifeYears: 22,
    discountRate: 7.5,
    taxRate: 34,
    royaltyRate: 3.5,
    creditRate: 6.0,
    creditYears: 14,
    unitPrice: 105,
    annualProduction: 12,
    plantProcessingRate: 90,
    equipmentCost: 420,
    facilityCost: 380,
    infrastructureCost: 260,
    contingencyRate: 11,
    fuelCost: 48,
    personnelCost: 35,
    maintenanceCost: 32,
    explosivesCost: 18,
    tireCost: 9.5,
    strippingCost: 42,
    otherOpex: 14,
    forestCost: 8,
    landCost: 6,
    rehabilitationCost: 18,
    annualStrippingVolume: 16.8,
    strippingUnitCost: 1.45,
    contractorStrippingCost: 0,
    plantOperatingCost: 55,
    equipmentDepLife: 8,
    facilityDepLife: 20,
    byProductRevenue: 0,
    fuelPricePerLiter: 1.28,
    electricityUnitPrice: 0.07,
    totalReserves: 280,
    oreGrade: 65,
    waterConsumptionDaily: 4_500,
    rehabilitationAreaHa: 980,
    rehabilitationCostPerHa: 14_000,
    loanAmount: 520,
    loanInterestRate: 6.0,
    loanTermYears: 14,
    equityRatio: 50,
  }),
  equipments: [
    equipmentRow({
      machineType: 'Komatsu 980E-5 Haul Truck',
      equipmentCategory: 'truck',
      model: '980E-5',
      tonnageCapacity: '363 ton',
      quantity: 18,
      spareQuantity: 2,
      unitCost: 5_200_000,
      dailyWorkHours: 20,
      hourlyFuelConsumption: 95,
      fuelConsumption: 95,
      maintenanceCost: 120_000,
      productionImpact: 650,
      transportCapacity: 363,
    }),
    equipmentRow({
      machineType: 'Hitachi EX5600-7 Excavator',
      equipmentCategory: 'excavator',
      model: 'EX5600-7',
      tonnageCapacity: '550 ton class',
      quantity: 3,
      spareQuantity: 1,
      unitCost: 9_800_000,
      dailyWorkHours: 20,
      maintenancePeriodHours: 400,
      operatorCount: 2,
      hourlyFuelConsumption: 145,
      fuelConsumption: 145,
      maintenanceCost: 210_000,
      productionImpact: 1_100,
      bucketVolume: 34,
    }),
    equipmentRow({
      machineType: 'Caterpillar 7495 Electric Rope Shovel',
      equipmentCategory: 'excavator',
      model: '7495',
      tonnageCapacity: '100 ton payload',
      quantity: 1,
      unitCost: 18_000_000,
      dailyWorkHours: 20,
      powerType: 'electric',
      maintenanceCost: 320_000,
      productionImpact: 1_400,
      bucketVolume: 52,
    }),
    equipmentRow({
      machineType: 'Komatsu D475A-8 Dozer',
      equipmentCategory: 'dozer',
      model: 'D475A-8',
      tonnageCapacity: '108 ton',
      quantity: 4,
      spareQuantity: 1,
      unitCost: 1_650_000,
      hourlyFuelConsumption: 58,
      fuelConsumption: 58,
      maintenanceCost: 48_000,
    }),
    equipmentRow({
      machineType: 'Epiroc Pit Viper 351 Drill',
      equipmentCategory: 'drill',
      model: 'Pit Viper 351',
      quantity: 4,
      spareQuantity: 1,
      unitCost: 2_800_000,
      hourlyFuelConsumption: 55,
      fuelConsumption: 55,
      maintenanceCost: 70_000,
      productionImpact: 32,
      drillCapacity: 32,
      holeDiameter: 311,
      maxDrillDepth: 70,
    }),
    equipmentRow({
      machineType: 'Metso HP900 Cone Crusher',
      equipmentCategory: 'crusher',
      model: 'HP900',
      tonnageCapacity: '1800 tph',
      quantity: 2,
      unitCost: 3_800_000,
      dailyWorkHours: 22,
      powerType: 'electric',
      maintenanceCost: 95_000,
      productionImpact: 1_400,
      crushingCapacity: 1_400,
    }),
  ],
  personnels: [
    ...standardMineStaff('large'),
    { role: 'Haul Truck Operator', count: 40, monthlySalary: 3_200 },
    { role: 'Shovel Operator', count: 12, monthlySalary: 3_800 },
  ],
  byProducts: [],
  methodCosts: [
    { name: 'Waste dump & drainage', category: 'openPit', value: 22, unit: 'MUSD' },
    { name: 'Stripping campaign', category: 'openPit', value: 42, unit: 'MUSD' },
    { name: 'Railway spur / stockyard', category: 'openPit', value: 85, unit: 'MUSD' },
    { name: 'Primary crushing station', category: 'openPit', value: 48, unit: 'MUSD' },
    { name: 'Haul road network', category: 'openPit', value: 18, unit: 'MUSD' },
  ],
};
