import type { DemoProjectDefinition } from '../types';
import { buildParams, equipmentRow, standardMineStaff } from '../helpers';

/**
 * Argentina lithium — open-pit hard-rock spodumene / chemical-grade concentrate.
 * 220 ktpa SC6 concentrate @ ~$1,900/t.
 */
export const LITHIUM_ARGENTINA_DEMO: DemoProjectDefinition = {
  id: 'demo-lithium-argentina',
  name: 'Puna Lithium Project',
  mineType: 'lithium',
  miningMethod: 'openPit',
  location: 'Salta Province, Argentina',
  country: 'Argentina',
  productionLabel: '220 ktpa SC6',
  accent: 'lithium',
  currency: 'USD',
  exchangeRate: 1.0,
  fuelPricePerLiter: 1.4,
  electricityUnitPrice: 0.095,
  explosiveUnitPrice: 1.9,
  totalReserves: 48,
  maxAnnualCapacity: 4.5,
  oreGrade: 1.35,
  oreGradeUnit: '% Li2O',
  strippingRatio: 3.2,
  recoveryPercent: 78,
  waterConsumptionDaily: 1_800,
  rehabilitationAreaHa: 310,
  rehabilitationCostPerHa: 16_000,
  loanAmount: 260,
  loanInterestRate: 7.0,
  loanTermYears: 12,
  equityRatio: 42,
  depreciationMethod: 'linear',
  equipmentRenewalEnabled: true,
  equipmentRenewalCycleYears: 10,
  latitude: -24.6,
  longitude: -66.9,
  params: buildParams({
    projectLifeYears: 20,
    discountRate: 9.5,
    taxRate: 30,
    royaltyRate: 3,
    creditRate: 7.0,
    creditYears: 12,
    unitPrice: 1900,
    annualProduction: 0.22,
    plantProcessingRate: 88,
    equipmentCost: 145,
    facilityCost: 310,
    infrastructureCost: 125,
    contingencyRate: 15,
    fuelCost: 14,
    personnelCost: 16,
    maintenanceCost: 12,
    explosivesCost: 6.5,
    tireCost: 2.8,
    strippingCost: 22,
    otherOpex: 8.5,
    forestCost: 1.5,
    landCost: 3.5,
    rehabilitationCost: 8.0,
    annualStrippingVolume: 11.5,
    strippingUnitCost: 1.75,
    contractorStrippingCost: 0,
    plantOperatingCost: 48,
    equipmentDepLife: 8,
    facilityDepLife: 18,
    byProductRevenue: 4.2,
    fuelPricePerLiter: 1.4,
    electricityUnitPrice: 0.095,
    totalReserves: 48,
    oreGrade: 1.35,
    waterConsumptionDaily: 1_800,
    rehabilitationAreaHa: 310,
    rehabilitationCostPerHa: 16_000,
    loanAmount: 260,
    loanInterestRate: 7.0,
    loanTermYears: 12,
    equityRatio: 42,
  }),
  equipments: [
    equipmentRow({
      machineType: 'Volvo EC750E Excavator',
      equipmentCategory: 'excavator',
      model: 'EC750E',
      tonnageCapacity: '75 ton',
      quantity: 4,
      spareQuantity: 1,
      unitCost: 980_000,
      hourlyFuelConsumption: 48,
      fuelConsumption: 48,
      maintenanceCost: 42_000,
      productionImpact: 380,
      bucketVolume: 5.2,
    }),
    equipmentRow({
      machineType: 'Caterpillar 777E Haul Truck',
      equipmentCategory: 'truck',
      model: '777E',
      tonnageCapacity: '100 ton',
      quantity: 12,
      spareQuantity: 2,
      unitCost: 2_100_000,
      dailyWorkHours: 18,
      hourlyFuelConsumption: 52,
      fuelConsumption: 52,
      maintenanceCost: 55_000,
      productionImpact: 280,
      transportCapacity: 100,
    }),
    equipmentRow({
      machineType: 'Volvo L350H Wheel Loader',
      equipmentCategory: 'loader',
      model: 'L350H',
      tonnageCapacity: '35 ton',
      quantity: 3,
      unitCost: 1_150_000,
      hourlyFuelConsumption: 38,
      fuelConsumption: 38,
      maintenanceCost: 36_000,
      productionImpact: 320,
      loadingCapacity: 320,
      bucketVolume: 7.5,
    }),
    equipmentRow({
      machineType: 'Epiroc SmartROC D65 Drill',
      equipmentCategory: 'drill',
      model: 'SmartROC D65',
      quantity: 3,
      spareQuantity: 1,
      unitCost: 780_000,
      hourlyFuelConsumption: 32,
      fuelConsumption: 32,
      maintenanceCost: 28_000,
      productionImpact: 26,
      drillCapacity: 26,
      holeDiameter: 165,
      maxDrillDepth: 45,
    }),
    equipmentRow({
      machineType: 'Metso HP6 Cone Crusher',
      equipmentCategory: 'crusher',
      model: 'HP6',
      tonnageCapacity: '450 tph',
      quantity: 2,
      unitCost: 2_400_000,
      dailyWorkHours: 22,
      powerType: 'electric',
      maintenanceCost: 68_000,
      productionImpact: 400,
      crushingCapacity: 400,
    }),
    equipmentRow({
      machineType: 'Caterpillar D10 Dozer',
      equipmentCategory: 'dozer',
      model: 'D10',
      tonnageCapacity: '70 ton',
      quantity: 2,
      unitCost: 1_250_000,
      hourlyFuelConsumption: 48,
      fuelConsumption: 48,
      maintenanceCost: 40_000,
    }),
  ],
  personnels: standardMineStaff('medium'),
  byProducts: [
    {
      name: 'Tantalum concentrate',
      annualProduction: 85,
      productionUnit: 'ton',
      unitPrice: 48_000,
      priceUnit: 'USD/ton',
      totalRevenue: 4.08,
    },
  ],
  methodCosts: [
    { name: 'Stripping / overburden', category: 'openPit', value: 22, unit: 'MUSD' },
    { name: 'Dense media separation plant', category: 'openPit', value: 65, unit: 'MUSD' },
    { name: 'Camp & high-altitude logistics', category: 'openPit', value: 18, unit: 'MUSD' },
    { name: 'Water management', category: 'openPit', value: 9.5, unit: 'MUSD' },
    { name: 'Tailings storage facility', category: 'openPit', value: 28, unit: 'MUSD' },
  ],
};
