import type { DemoProjectDefinition } from '../types';
import { buildParams, equipmentRow, standardMineStaff } from '../helpers';

/**
 * Canada underground nickel sulphide — Sudbury-style.
 *
 * Engine convention: **ore throughput (Mt/year)** + Ni NSR ($/t ore), not payable metal Mt.
 *
 * - Ore reserve 42 Mt / 18 y life → 2.333 Mtpa ore
 * - 1.85% Ni × 86% recovery → ≈ 37 ktpa payable Ni
 * - NSR = $18,500/t Ni × 1.85% × 86% = $294.34/t ore
 * - Capacity 2.8 Mtpa → ≈ 83% utilization
 */
export const NICKEL_CANADA_DEMO: DemoProjectDefinition = {
  id: 'demo-nickel-canada',
  name: 'Sudbury Nickel Project',
  mineType: 'nickel',
  miningMethod: 'underground',
  location: 'Ontario, Canada',
  country: 'Canada',
  productionLabel: '2.333 Mtpa ore (~37 ktpa Ni)',
  accent: 'nickel',
  currency: 'USD',
  exchangeRate: 1.0,
  fuelPricePerLiter: 1.5,
  electricityUnitPrice: 0.08,
  explosiveUnitPrice: 2.2,
  totalReserves: 42,
  maxAnnualCapacity: 2.8,
  oreGrade: 1.85,
  oreGradeUnit: '% Ni',
  strippingRatio: 0,
  recoveryPercent: 86,
  waterConsumptionDaily: 2_200,
  rehabilitationAreaHa: 140,
  rehabilitationCostPerHa: 28_000,
  loanAmount: 220,
  loanInterestRate: 6.25,
  loanTermYears: 12,
  equityRatio: 45,
  depreciationMethod: 'linear',
  equipmentRenewalEnabled: true,
  equipmentRenewalCycleYears: 8,
  latitude: 46.49,
  longitude: -81.0,
  params: buildParams({
    projectLifeYears: 18,
    discountRate: 8.5,
    taxRate: 26.5,
    royaltyRate: 4,
    creditRate: 6.25,
    creditYears: 12,
    unitPrice: 294.34,
    annualProduction: 2.333,
    plantProcessingRate: 91,
    equipmentCost: 165,
    facilityCost: 210,
    infrastructureCost: 85,
    contingencyRate: 13,
    fuelCost: 9.5,
    personnelCost: 28,
    maintenanceCost: 16,
    explosivesCost: 7.2,
    tireCost: 1.1,
    strippingCost: 0,
    otherOpex: 8.5,
    forestCost: 2.0,
    landCost: 3.0,
    rehabilitationCost: 7.5,
    annualStrippingVolume: 0,
    strippingUnitCost: 0,
    contractorStrippingCost: 0,
    plantOperatingCost: 42,
    equipmentDepLife: 7,
    facilityDepLife: 18,
    byProductRevenue: 42,
    fuelPricePerLiter: 1.5,
    electricityUnitPrice: 0.08,
    totalReserves: 42,
    oreGrade: 1.85,
    waterConsumptionDaily: 2_200,
    rehabilitationAreaHa: 140,
    rehabilitationCostPerHa: 28_000,
    loanAmount: 220,
    loanInterestRate: 6.25,
    loanTermYears: 12,
    equityRatio: 45,
  }),
  equipments: [
    equipmentRow({
      machineType: 'Sandvik LH517i LHD',
      equipmentCategory: 'loader',
      model: 'LH517i',
      tonnageCapacity: '17 ton',
      quantity: 8,
      spareQuantity: 2,
      unitCost: 1_250_000,
      dailyWorkHours: 18,
      gallerySuitability: '4.5 x 4.5 m',
      hourlyFuelConsumption: 24,
      fuelConsumption: 24,
      maintenanceCost: 44_000,
      productionImpact: 220,
      loadingCapacity: 220,
      bucketVolume: 6.5,
    }),
    equipmentRow({
      machineType: 'Epiroc Minetruck MT65',
      equipmentCategory: 'truck',
      model: 'MT65',
      tonnageCapacity: '65 ton',
      quantity: 10,
      spareQuantity: 2,
      unitCost: 1_550_000,
      dailyWorkHours: 18,
      gallerySuitability: '5.5 x 5.5 m',
      hourlyFuelConsumption: 40,
      fuelConsumption: 40,
      maintenanceCost: 50_000,
      productionImpact: 300,
      transportCapacity: 65,
    }),
    equipmentRow({
      machineType: 'Epiroc Boomer E2 Jumbo',
      equipmentCategory: 'drill',
      model: 'Boomer E2',
      quantity: 5,
      spareQuantity: 1,
      unitCost: 1_050_000,
      powerType: 'electric',
      maintenanceCost: 40_000,
      productionImpact: 48,
      drillCapacity: 48,
      holeDiameter: 48,
      maxDrillDepth: 4.5,
    }),
    equipmentRow({
      machineType: 'Sandvik DL421 Longhole Drill',
      equipmentCategory: 'drill',
      model: 'DL421',
      quantity: 3,
      unitCost: 1_380_000,
      powerType: 'electric',
      maintenanceCost: 46_000,
      productionImpact: 60,
      drillCapacity: 60,
      holeDiameter: 89,
      maxDrillDepth: 40,
    }),
    equipmentRow({
      machineType: 'Atlas Copco Scooptram ST14',
      equipmentCategory: 'loader',
      model: 'ST14',
      tonnageCapacity: '14 ton',
      quantity: 4,
      unitCost: 980_000,
      gallerySuitability: '4.0 x 4.0 m',
      hourlyFuelConsumption: 22,
      fuelConsumption: 22,
      maintenanceCost: 35_000,
      productionImpact: 180,
      loadingCapacity: 180,
      bucketVolume: 5.4,
    }),
    equipmentRow({
      machineType: 'Metso SAG Mill 32ft',
      equipmentCategory: 'crusher',
      model: 'SAG-32',
      tonnageCapacity: '350 tph',
      quantity: 1,
      unitCost: 8_500_000,
      dailyWorkHours: 22,
      powerType: 'electric',
      maintenanceCost: 180_000,
      productionImpact: 300,
      crushingCapacity: 300,
    }),
  ],
  personnels: [
    ...standardMineStaff('large'),
    { role: 'LHD Operator', count: 20, monthlySalary: 4_200 },
    { role: 'Jumbo Operator', count: 10, monthlySalary: 4_400 },
    { role: 'Underground Miner', count: 45, monthlySalary: 3_800 },
  ],
  byProducts: [
    {
      name: 'Copper',
      annualProduction: 12_000,
      productionUnit: 'ton',
      unitPrice: 9_000,
      priceUnit: 'USD/ton',
      totalRevenue: 108,
    },
    {
      name: 'Cobalt',
      annualProduction: 850,
      productionUnit: 'ton',
      unitPrice: 32_000,
      priceUnit: 'USD/ton',
      totalRevenue: 27.2,
    },
    {
      name: 'PGM (credit)',
      annualProduction: 1_200,
      productionUnit: 'kg',
      unitPrice: 45,
      priceUnit: 'USD/g',
      totalRevenue: 32.4,
    },
  ],
  methodCosts: [
    { name: 'Shaft / ramp development', category: 'underground', value: 95, unit: 'MUSD' },
    { name: 'Ground support', category: 'underground', value: 14, unit: 'MUSD' },
    { name: 'Ventilation & heating', category: 'underground', value: 18, unit: 'MUSD' },
    { name: 'Paste backfill', category: 'underground', value: 12, unit: 'MUSD' },
    { name: 'Mine water treatment', category: 'underground', value: 8.5, unit: 'MUSD' },
  ],
};
