import type { DemoProjectDefinition } from '../types';
import { buildParams, equipmentRow, standardMineStaff } from '../helpers';

/**
 * Sweden open-pit rare earth — Kiruna / Norra Kärr style TREO project.
 *
 * Engine convention: **ore throughput (Mt/year)** + TREO NSR ($/t ore), not payable TREO Mt.
 *
 * - Ore reserve 36 Mt / 18 y life → 2.0 Mtpa ore
 * - 0.55% TREO × 72% recovery → ≈ 7.9 ktpa TREO
 * - NSR = $28,000/t TREO × 0.55% × 72% = $110.88/t ore
 * - Capacity 3.5 Mtpa → ≈ 57% utilization; strip 4.5 → 9.0 Mtpa waste
 */
export const RARE_EARTH_SWEDEN_DEMO: DemoProjectDefinition = {
  id: 'demo-rare-earth-sweden',
  name: 'Kiruna Rare Earth Project',
  mineType: 'rareEarth',
  miningMethod: 'openPit',
  location: 'Norrbotten County, Sweden',
  country: 'Sweden',
  productionLabel: '2.0 Mtpa ore (~8 ktpa TREO)',
  accent: 'rareEarth',
  currency: 'USD',
  exchangeRate: 1.0,
  fuelPricePerLiter: 1.55,
  electricityUnitPrice: 0.065,
  explosiveUnitPrice: 2.1,
  totalReserves: 36,
  maxAnnualCapacity: 3.5,
  oreGrade: 0.55,
  oreGradeUnit: '% TREO',
  strippingRatio: 4.5,
  recoveryPercent: 72,
  waterConsumptionDaily: 2_600,
  rehabilitationAreaHa: 380,
  rehabilitationCostPerHa: 26_000,
  loanAmount: 240,
  loanInterestRate: 5.5,
  loanTermYears: 12,
  equityRatio: 50,
  depreciationMethod: 'linear',
  equipmentRenewalEnabled: true,
  equipmentRenewalCycleYears: 10,
  latitude: 67.85,
  longitude: 20.25,
  params: buildParams({
    projectLifeYears: 18,
    discountRate: 8.0,
    taxRate: 20.6,
    royaltyRate: 2,
    creditRate: 5.5,
    creditYears: 12,
    unitPrice: 110.88,
    annualProduction: 2.0,
    plantProcessingRate: 86,
    equipmentCost: 155,
    facilityCost: 285,
    infrastructureCost: 95,
    contingencyRate: 16,
    fuelCost: 11,
    personnelCost: 24,
    maintenanceCost: 14,
    explosivesCost: 5.5,
    tireCost: 2.2,
    strippingCost: 26,
    otherOpex: 9.0,
    forestCost: 3.5,
    landCost: 2.5,
    rehabilitationCost: 11,
    annualStrippingVolume: 9.0,
    strippingUnitCost: 2.1,
    contractorStrippingCost: 0,
    plantOperatingCost: 52,
    equipmentDepLife: 8,
    facilityDepLife: 18,
    byProductRevenue: 6.5,
    fuelPricePerLiter: 1.55,
    electricityUnitPrice: 0.065,
    totalReserves: 36,
    oreGrade: 0.55,
    waterConsumptionDaily: 2_600,
    rehabilitationAreaHa: 380,
    rehabilitationCostPerHa: 26_000,
    loanAmount: 240,
    loanInterestRate: 5.5,
    loanTermYears: 12,
    equityRatio: 50,
  }),
  equipments: [
    equipmentRow({
      machineType: 'Liebherr R 9400 Excavator',
      equipmentCategory: 'excavator',
      model: 'R 9400',
      tonnageCapacity: '400 ton class',
      quantity: 2,
      spareQuantity: 1,
      unitCost: 6_500_000,
      dailyWorkHours: 18,
      operatorCount: 2,
      hourlyFuelConsumption: 110,
      fuelConsumption: 110,
      maintenanceCost: 165_000,
      productionImpact: 700,
      bucketVolume: 22,
    }),
    equipmentRow({
      machineType: 'Hitachi EH4000AC-3 Haul Truck',
      equipmentCategory: 'truck',
      model: 'EH4000AC-3',
      tonnageCapacity: '221 ton',
      quantity: 10,
      spareQuantity: 2,
      unitCost: 3_600_000,
      dailyWorkHours: 18,
      hourlyFuelConsumption: 72,
      fuelConsumption: 72,
      maintenanceCost: 88_000,
      productionImpact: 480,
      transportCapacity: 221,
    }),
    equipmentRow({
      machineType: 'Volvo EC480E Excavator',
      equipmentCategory: 'excavator',
      model: 'EC480E',
      tonnageCapacity: '48 ton',
      quantity: 3,
      unitCost: 620_000,
      hourlyFuelConsumption: 32,
      fuelConsumption: 32,
      maintenanceCost: 28_000,
      productionImpact: 280,
      bucketVolume: 3.2,
    }),
    equipmentRow({
      machineType: 'Epiroc FlexiROC D65 Drill',
      equipmentCategory: 'drill',
      model: 'FlexiROC D65',
      quantity: 3,
      spareQuantity: 1,
      unitCost: 720_000,
      hourlyFuelConsumption: 30,
      fuelConsumption: 30,
      maintenanceCost: 26_000,
      productionImpact: 24,
      drillCapacity: 24,
      holeDiameter: 152,
      maxDrillDepth: 42,
    }),
    equipmentRow({
      machineType: 'Metso VERTIMILL VTM-4500',
      equipmentCategory: 'crusher',
      model: 'VTM-4500',
      tonnageCapacity: '250 tph',
      quantity: 2,
      unitCost: 4_800_000,
      dailyWorkHours: 22,
      powerType: 'electric',
      maintenanceCost: 95_000,
      productionImpact: 220,
      crushingCapacity: 220,
    }),
    equipmentRow({
      machineType: 'Liebherr PR 776 Dozer',
      equipmentCategory: 'dozer',
      model: 'PR 776',
      tonnageCapacity: '73 ton',
      quantity: 2,
      unitCost: 1_450_000,
      hourlyFuelConsumption: 45,
      fuelConsumption: 45,
      maintenanceCost: 42_000,
    }),
  ],
  personnels: [
    ...standardMineStaff('medium'),
    { role: 'Process Metallurgist (REE)', count: 4, monthlySalary: 7_200 },
    { role: 'Haul Truck Operator', count: 22, monthlySalary: 3_800 },
  ],
  byProducts: [
    {
      name: 'Fluorspar (by-product)',
      annualProduction: 18_000,
      productionUnit: 'ton',
      unitPrice: 280,
      priceUnit: 'USD/ton',
      totalRevenue: 5.04,
    },
    {
      name: 'Uranium credit (trace)',
      annualProduction: 18,
      productionUnit: 'ton',
      unitPrice: 80_000,
      priceUnit: 'USD/ton',
      totalRevenue: 1.44,
    },
  ],
  methodCosts: [
    { name: 'Stripping / overburden', category: 'openPit', value: 26, unit: 'MUSD' },
    { name: 'Hydrometallurgical plant', category: 'openPit', value: 145, unit: 'MUSD' },
    { name: 'Arctic winterization', category: 'openPit', value: 22, unit: 'MUSD' },
    { name: 'Tailings & residue storage', category: 'openPit', value: 35, unit: 'MUSD' },
    { name: 'Environmental monitoring', category: 'openPit', value: 4.5, unit: 'MUSD' },
  ],
};
