import type { DemoProjectDefinition } from '../types';
import { buildParams, equipmentRow, standardMineStaff } from '../helpers';

/**
 * Peru underground zinc-lead-silver — Central Andes.
 *
 * Engine convention: **ore throughput (Mt/year)** + Zn NSR ($/t ore), not payable metal Mt.
 * Pb/Ag remain in byProductRevenue.
 *
 * - Ore reserve 28 Mt / 16 y life → 1.75 Mtpa ore
 * - 6.5% Zn × 89% recovery → ≈ 101 ktpa payable Zn
 * - NSR = $2,850/t Zn × 6.5% × 89% = $164.87/t ore
 * - Capacity 2.2 Mtpa → ≈ 80% utilization
 */
export const ZINC_PERU_DEMO: DemoProjectDefinition = {
  id: 'demo-zinc-peru',
  name: 'Andes Zinc Project',
  mineType: 'zinc',
  miningMethod: 'underground',
  location: 'Pasco Region, Peru',
  country: 'Peru',
  productionLabel: '1.75 Mtpa ore (~101 ktpa Zn)',
  accent: 'zinc',
  currency: 'USD',
  exchangeRate: 1.0,
  fuelPricePerLiter: 1.38,
  electricityUnitPrice: 0.085,
  explosiveUnitPrice: 2.0,
  totalReserves: 28,
  maxAnnualCapacity: 2.2,
  oreGrade: 6.5,
  oreGradeUnit: '% Zn',
  strippingRatio: 0,
  recoveryPercent: 89,
  waterConsumptionDaily: 1_400,
  rehabilitationAreaHa: 95,
  rehabilitationCostPerHa: 24_000,
  loanAmount: 140,
  loanInterestRate: 7.0,
  loanTermYears: 10,
  equityRatio: 40,
  depreciationMethod: 'linear',
  equipmentRenewalEnabled: true,
  equipmentRenewalCycleYears: 8,
  latitude: -10.68,
  longitude: -76.25,
  params: buildParams({
    projectLifeYears: 16,
    discountRate: 9.0,
    taxRate: 29.5,
    royaltyRate: 4.5,
    creditRate: 7.0,
    creditYears: 10,
    unitPrice: 164.87,
    annualProduction: 1.75,
    plantProcessingRate: 90,
    equipmentCost: 98,
    facilityCost: 125,
    infrastructureCost: 55,
    contingencyRate: 13,
    fuelCost: 7.5,
    personnelCost: 19,
    maintenanceCost: 11,
    explosivesCost: 5.8,
    tireCost: 0.9,
    strippingCost: 0,
    otherOpex: 6.2,
    forestCost: 1.5,
    landCost: 2.2,
    rehabilitationCost: 5.5,
    annualStrippingVolume: 0,
    strippingUnitCost: 0,
    contractorStrippingCost: 0,
    plantOperatingCost: 32,
    equipmentDepLife: 7,
    facilityDepLife: 16,
    byProductRevenue: 48,
    fuelPricePerLiter: 1.38,
    electricityUnitPrice: 0.085,
    totalReserves: 28,
    oreGrade: 6.5,
    waterConsumptionDaily: 1_400,
    rehabilitationAreaHa: 95,
    rehabilitationCostPerHa: 24_000,
    loanAmount: 140,
    loanInterestRate: 7.0,
    loanTermYears: 10,
    equityRatio: 40,
  }),
  equipments: [
    equipmentRow({
      machineType: 'Sandvik LH514i LHD',
      equipmentCategory: 'loader',
      model: 'LH514i',
      tonnageCapacity: '14 ton',
      quantity: 7,
      spareQuantity: 1,
      unitCost: 1_100_000,
      dailyWorkHours: 18,
      gallerySuitability: '4.2 x 4.2 m',
      hourlyFuelConsumption: 22,
      fuelConsumption: 22,
      maintenanceCost: 40_000,
      productionImpact: 200,
      loadingCapacity: 200,
      bucketVolume: 5.5,
    }),
    equipmentRow({
      machineType: 'Epiroc Minetruck MT42',
      equipmentCategory: 'truck',
      model: 'MT42',
      tonnageCapacity: '42 ton',
      quantity: 9,
      spareQuantity: 1,
      unitCost: 1_250_000,
      gallerySuitability: '5.0 x 5.0 m',
      hourlyFuelConsumption: 32,
      fuelConsumption: 32,
      maintenanceCost: 44_000,
      productionImpact: 250,
      transportCapacity: 42,
    }),
    equipmentRow({
      machineType: 'Atlas Copco Boomer S1D Jumbo',
      equipmentCategory: 'drill',
      model: 'Boomer S1D',
      quantity: 4,
      spareQuantity: 1,
      unitCost: 920_000,
      powerType: 'electric',
      maintenanceCost: 34_000,
      productionImpact: 42,
      drillCapacity: 42,
      holeDiameter: 45,
      maxDrillDepth: 3.8,
    }),
    equipmentRow({
      machineType: 'Sandvik DL311 Longhole Drill',
      equipmentCategory: 'drill',
      model: 'DL311',
      quantity: 2,
      unitCost: 1_150_000,
      powerType: 'electric',
      maintenanceCost: 38_000,
      productionImpact: 50,
      drillCapacity: 50,
      holeDiameter: 76,
      maxDrillDepth: 28,
    }),
    equipmentRow({
      machineType: 'Epiroc Boltec E Bolter',
      equipmentCategory: 'underground',
      model: 'Boltec E',
      quantity: 3,
      unitCost: 780_000,
      powerType: 'electric',
      maintenanceCost: 26_000,
    }),
    equipmentRow({
      machineType: 'Metso RCS Flotation Cell Bank',
      equipmentCategory: 'crusher',
      model: 'RCS-300',
      tonnageCapacity: '220 tph',
      quantity: 1,
      unitCost: 4_200_000,
      dailyWorkHours: 22,
      powerType: 'electric',
      maintenanceCost: 85_000,
      productionImpact: 200,
      crushingCapacity: 200,
    }),
  ],
  personnels: [
    ...standardMineStaff('medium'),
    { role: 'LHD Operator', count: 16, monthlySalary: 3_400 },
    { role: 'Jumbo Operator', count: 8, monthlySalary: 3_600 },
    { role: 'Underground Miner', count: 38, monthlySalary: 3_100 },
  ],
  byProducts: [
    {
      name: 'Lead concentrate',
      annualProduction: 28_000,
      productionUnit: 'ton',
      unitPrice: 1_850,
      priceUnit: 'USD/ton',
      totalRevenue: 51.8,
    },
    {
      name: 'Silver',
      annualProduction: 45_000,
      productionUnit: 'kg',
      unitPrice: 0.92,
      priceUnit: 'USD/g',
      totalRevenue: 24.84,
    },
  ],
  methodCosts: [
    { name: 'Ramp & level development', category: 'underground', value: 42, unit: 'MUSD' },
    { name: 'Ground support', category: 'underground', value: 11, unit: 'MUSD' },
    { name: 'Ventilation', category: 'underground', value: 8.5, unit: 'MUSD' },
    { name: 'Flotation plant', category: 'underground', value: 38, unit: 'MUSD' },
    { name: 'Tailings & water treatment', category: 'underground', value: 12, unit: 'MUSD' },
  ],
};
