#!/usr/bin/env python3
"""Generate compact TypeScript seed datasets for the Equipment Catalog."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "lib" / "master-data" / "seed" / "datasets"

FIELD_ORDER = [
    "manufacturer",
    "model",
    "category",
    "description",
    "capacityLabel",
    "payloadTons",
    "bucketCapacityM3",
    "enginePowerKw",
    "operatingWeightTons",
    "fuelTankCapacityL",
    "purchasePriceUsd",
    "usefulLifeYears",
    "availabilityPct",
    "powerType",
    "notes",
    "searchAliasesExtra",
]


Spec = dict[str, Any]


def spec(
    manufacturer: str,
    model: str,
    category: str,
    description: str,
    capacity_label: str,
    price: int,
    **kwargs: Any,
) -> Spec:
    row: Spec = {
        "manufacturer": manufacturer,
        "model": model,
        "category": category,
        "description": description,
        "capacityLabel": capacity_label,
        "purchasePriceUsd": price,
    }
    row.update({key: value for key, value in kwargs.items() if value is not None})
    return row


def by_payload(
    rows: Iterable[tuple[str, str, str, float | None, int, int | None]],
    category: str,
    description: str,
) -> list[Spec]:
    return [
        spec(
            manufacturer,
            model,
            category,
            description,
            f"{payload:g} t payload class" if payload is not None else label,
            price,
            payloadTons=payload,
            enginePowerKw=power,
            usefulLifeYears=12 if payload and payload >= 140 else None,
        )
        for manufacturer, model, label, payload, price, power in rows
    ]


def by_bucket(
    rows: Iterable[tuple[str, str, float | None, int, int | None, float | None]],
    category: str,
    description: str,
) -> list[Spec]:
    return [
        spec(
            manufacturer,
            model,
            category,
            description,
            f"{bucket:g} m3 bucket class" if bucket is not None else label,
            price,
            bucketCapacityM3=bucket,
            enginePowerKw=power,
            operatingWeightTons=weight,
            usefulLifeYears=12 if price >= 3_500_000 else None,
        )
        for manufacturer, model, bucket, price, power, weight in rows
        for label in ["Configuration-dependent bucket class"]
    ]


def simple_models(
    manufacturer: str,
    models: Iterable[str],
    category: str,
    description: str,
    capacity_label: str,
    price: int,
    step: int = 50_000,
    **kwargs: Any,
) -> list[Spec]:
    return [
        spec(
            manufacturer,
            model,
            category,
            description,
            capacity_label,
            price + index * step,
            **kwargs,
        )
        for index, model in enumerate(models)
    ]


def render_value(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def render_ts_array(export_name: str, rows: list[Spec]) -> str:
    blocks = []
    for row in rows:
        lines = []
        for key in FIELD_ORDER:
            if key not in row:
                continue
            lines.append(f"    {key}: {render_value(row[key])},")
        blocks.append("  {\n" + "\n".join(lines) + "\n  }")
    return (
        "import type { CompactEquipmentSpec } from '../helpers';\n\n"
        "/** Auto-generated by scripts/generate-equipment-catalog.py. */\n"
        f"export const {export_name}: CompactEquipmentSpec[] = [\n"
        + ",\n".join(blocks)
        + "\n];\n"
    )


def write_dataset(filename: str, export_name: str, rows: list[Spec]) -> None:
    (OUT_DIR / filename).write_text(render_ts_array(export_name, rows), encoding="utf-8")


def dedupe(rows: list[Spec]) -> list[Spec]:
    seen: set[tuple[str, str]] = set()
    unique: list[Spec] = []
    duplicates: list[str] = []
    for row in rows:
        key = (row["manufacturer"].casefold(), row["model"].casefold())
        if key in seen:
            duplicates.append(f"{row['manufacturer']} {row['model']}")
            continue
        seen.add(key)
        unique.append(row)
    if duplicates:
        print("Deduplicated duplicate manufacturer+model combinations:")
        for duplicate in duplicates:
            print(f"  - {duplicate}")
    return unique


TRUCKS = by_payload(
    [
        ("Caterpillar", "770G", "", 38.6, 1_100_000, 381),
        ("Caterpillar", "772G", "", 46.2, 1_250_000, 446),
        ("Caterpillar", "773G", "", 61.2, 1_550_000, 578),
        ("Caterpillar", "775G", "", 70.3, 1_700_000, 615),
        ("Caterpillar", "777G", "", 98.2, 1_950_000, 765),
        ("Caterpillar", "785D", "", 140, 3_200_000, 1082),
        ("Caterpillar", "789D", "", 181, 4_200_000, 1417),
        ("Caterpillar", "793F", "", 226.8, 5_500_000, 1976),
        ("Caterpillar", "794 AC", "", 291, 6_800_000, 2610),
        ("Caterpillar", "797F", "", 363, 7_500_000, 2983),
        ("Komatsu", "HD465-8", "", 55, 1_350_000, 578),
        ("Komatsu", "HD605-8", "", 63, 1_450_000, 578),
        ("Komatsu", "HD785-8", "", 91, 1_650_000, 895),
        ("Komatsu", "HD1500-8", "", 144, 3_400_000, 1193),
        ("Komatsu", "830E-5", "", 221, 5_000_000, None),
        ("Komatsu", "930E-5", "", 290, 6_000_000, None),
        ("Komatsu", "960E-2K", "", 327, 6_500_000, None),
        ("Komatsu", "980E-5", "", 363, 7_200_000, None),
        ("Liebherr", "T 236", "", 100, 2_400_000, 1000),
        ("Liebherr", "T 264", "", 240, 5_200_000, None),
        ("Liebherr", "T 274", "", 320, 6_400_000, None),
        ("Liebherr", "T 284", "", 363, 7_000_000, None),
        ("Hitachi", "EH1100-5", "", 70, 1_800_000, 671),
        ("Hitachi", "EH1700-3", "", 100, 2_400_000, None),
        ("Hitachi", "EH3500AC-3", "", 181, 4_200_000, None),
        ("Hitachi", "EH4000AC-3", "", 221, 4_800_000, None),
        ("Hitachi", "EH5000AC-3", "", 296, 6_200_000, None),
        ("Volvo CE", "A40G", "", 39, 580_000, 315),
        ("Volvo CE", "A45G", "", 41, 650_000, 350),
        ("Volvo CE", "A60H", "", 55, 820_000, 470),
        ("Bell", "B30E", "", 28, 440_000, 246),
        ("Bell", "B40E", "", 39, 560_000, 335),
        ("Bell", "B45E", "", 41, 620_000, 350),
        ("Bell", "B50E", "", 45.4, 680_000, 390),
        ("Bell", "B60E", "", 55, 780_000, 390),
        ("XCMG", "XDE120", "", 120, 2_100_000, None),
        ("XCMG", "XDE160", "", 160, 2_800_000, None),
        ("XCMG", "XDE240", "", 220, 3_800_000, None),
        ("SANY", "SKT90S", "", 90, 1_400_000, 783),
        ("SANY", "SRT95C", "", 95, 1_550_000, None),
    ],
    "truck",
    "Rigid or articulated haul truck for surface mine production and support.",
)

WATER_TRUCKS = [
    spec("Caterpillar", "777G Water Truck", "waterTruck", "Water truck conversion for haul-road dust suppression.", "75,700 L water tank class", 2_250_000, searchAliasesExtra="water truck"),
    spec("Caterpillar", "785D Water Truck", "waterTruck", "Large water truck conversion for open-pit haul roads.", "121,000 L water tank class", 3_700_000, searchAliasesExtra="water truck"),
    spec("Caterpillar", "789D Water Truck", "waterTruck", "Ultra-large water truck conversion for mine haul roads.", "160,000 L water tank class", 4_850_000, searchAliasesExtra="water truck"),
    spec("Komatsu", "HD785-8 Water Truck", "waterTruck", "Water truck conversion based on a rigid mining truck platform.", "90,000 L water tank class", 2_050_000, searchAliasesExtra="water truck"),
    spec("Bell", "B45E Water Tanker", "waterTruck", "Articulated water tanker for mine infrastructure and dust suppression.", "41 t ADT water tanker class", 760_000, payloadTons=41, searchAliasesExtra="water tanker"),
    spec("Volvo CE", "A45G Water Tanker", "waterTruck", "Articulated water tanker for support roads and construction areas.", "41 t ADT water tanker class", 790_000, payloadTons=41, searchAliasesExtra="water tanker"),
    spec("XCMG", "XDE120 Water Truck", "waterTruck", "Large water truck conversion for surface mines.", "120 t chassis water truck class", 2_450_000, payloadTons=120, searchAliasesExtra="water truck"),
    spec("SANY", "SKT90S Water Truck", "waterTruck", "Rigid water truck conversion for open-pit support.", "90 t chassis water truck class", 1_700_000, payloadTons=90, searchAliasesExtra="water truck"),
]

SERVICE_TRUCKS = [
    spec("Caterpillar", "740 GC Service Truck", "serviceTruck", "Articulated service and lube truck for field maintenance.", "36 t ADT service truck class", 690_000, payloadTons=36.3, searchAliasesExtra="service truck lube"),
    spec("Caterpillar", "745 Service Truck", "serviceTruck", "Articulated service truck for mine fleet lubrication and support.", "41 t ADT service truck class", 760_000, payloadTons=41, searchAliasesExtra="service truck lube"),
    spec("Komatsu", "HD465-8 Service Truck", "serviceTruck", "Service truck conversion on a rigid mine truck chassis.", "55 t chassis service truck class", 1_550_000, payloadTons=55, searchAliasesExtra="service truck"),
    spec("Volvo CE", "A40G Fuel and Lube Truck", "serviceTruck", "Articulated fuel and lube truck for mine maintenance support.", "39 t ADT fuel and lube class", 700_000, payloadTons=39, searchAliasesExtra="fuel lube truck"),
    spec("Bell", "B50E Fuel and Lube Truck", "serviceTruck", "Articulated fuel and lube truck for rough-terrain support.", "45 t ADT fuel and lube class", 790_000, payloadTons=45.4, searchAliasesExtra="fuel lube truck"),
    spec("XCMG", "XDA45U Service Truck", "serviceTruck", "Articulated support truck configured for service duties.", "45 t ADT service truck class", 610_000, payloadTons=45, searchAliasesExtra="service truck"),
    spec("SANY", "SRT45 Service Truck", "serviceTruck", "Rigid service truck for field maintenance in smaller open pits.", "45 t service truck class", 850_000, payloadTons=45, searchAliasesExtra="service truck"),
    spec("MacLean", "BT3 Boom Truck", "serviceTruck", "Mine service boom truck for materials handling and maintenance.", "Underground service boom truck class", 620_000, searchAliasesExtra="service truck boom truck"),
]

SUPPORT = [
    spec("Caterpillar", "834K Wheel Dozer", "support", "Wheel dozer for cleanup, stockpiles, and dump support.", "Large wheel dozer class", 1_200_000, enginePowerKw=370),
    spec("Caterpillar", "844K Wheel Dozer", "support", "Large wheel dozer for mine support and stockpile work.", "Large wheel dozer class", 1_650_000, enginePowerKw=561),
    spec("Caterpillar", "854K Wheel Dozer", "support", "High-production wheel dozer for major mining operations.", "Ultra-large wheel dozer class", 2_500_000, enginePowerKw=676),
    spec("Caterpillar", "657 Wheel Tractor-Scraper", "support", "Wheel tractor-scraper for mine development earthworks.", "Scraper support fleet class", 1_850_000),
    spec("Komatsu", "WD600-6", "support", "Wheel dozer for stockpile and dump maintenance.", "Wheel dozer class", 1_050_000),
    spec("Komatsu", "WD900-3", "support", "Large wheel dozer for surface mine cleanup and support.", "Large wheel dozer class", 1_850_000),
    spec("Liebherr", "LH 80 M High Rise", "support", "Material handler for stockpile and plant support duties.", "Large material handler class", 950_000),
    spec("Volvo CE", "R100E", "support", "Rigid hauler used for mine infrastructure support.", "95 t payload support hauler class", 1_500_000, payloadTons=95),
    spec("XCMG", "LW1100KN Tire Handler", "support", "Wheel-loader-based tire handler for large mining trucks.", "Large tire handler class", 900_000),
    spec("SANY", "SMHW48G5", "support", "Heavy material handler for mine support yards and stockpiles.", "Material handler class", 520_000),
    spec("Normet", "Multimec SF 060 VC", "support", "Carrier platform used for support modules in mining operations.", "Modular support carrier class", 680_000),
    spec("MacLean", "TM3 Transmixer", "support", "Concrete transmixer for mine construction support.", "Concrete support vehicle class", 780_000),
]

SURFACE_EXCAVATORS = by_bucket(
    [
        ("Caterpillar", "6015B", 8.1, 2_800_000, 615, 140),
        ("Caterpillar", "6020B", 12, 3_200_000, 778, 230),
        ("Caterpillar", "6030", 17, 4_200_000, 1140, 300),
        ("Caterpillar", "6040", 22, 5_200_000, None, 400),
        ("Caterpillar", "6050", 28, 6_500_000, None, 500),
        ("Caterpillar", "6060", 34, 8_000_000, None, 600),
        ("Caterpillar", "6090 FS", 52, 13_000_000, None, 980),
        ("Caterpillar", "7495 HF", 30.6, 18_000_000, None, None),
        ("Caterpillar", "7495 HD", 62.7, 22_000_000, None, None),
        ("Caterpillar", "7495 with HydraCrowd", 62.7, 23_000_000, None, None),
        ("Komatsu", "PC1250-11", 6.7, 1_600_000, 578, 115),
        ("Komatsu", "PC2000-11", 12, 3_200_000, None, 200),
        ("Komatsu", "PC3000-11", 16, 4_600_000, None, 300),
        ("Komatsu", "PC4000-11", 22, 5_600_000, None, 400),
        ("Komatsu", "PC5500-11", 29, 7_000_000, None, 550),
        ("Komatsu", "PC7000-11", 36, 9_000_000, None, 700),
        ("Komatsu", "PC8000-11", 42, 11_500_000, None, 750),
        ("Komatsu", "P&H 2800XPC", 33, 17_000_000, None, None),
        ("Komatsu", "P&H 4100XPC", 67.6, 24_000_000, None, None),
        ("Komatsu", "P&H 4800XPC", 80, 28_000_000, None, None),
        ("Liebherr", "R 9150", 8.3, 2_400_000, 565, 130),
        ("Liebherr", "R 9200", 12.5, 3_100_000, None, 210),
        ("Liebherr", "R 9250", 15, 4_100_000, None, 250),
        ("Liebherr", "R 9350", 18, 5_000_000, None, 300),
        ("Liebherr", "R 9400", 22, 5_800_000, None, 400),
        ("Liebherr", "R 9600", 37.5, 8_500_000, None, 600),
        ("Liebherr", "R 9800", 47.5, 11_000_000, None, 800),
        ("Liebherr", "R 996B", 36, 8_500_000, None, 670),
        ("Hitachi", "EX1200-7", 7, 1_700_000, None, 115),
        ("Hitachi", "EX1900-6", 11, 2_800_000, None, 190),
        ("Hitachi", "EX2600-7", 15, 4_500_000, None, 250),
        ("Hitachi", "EX3600-7", 22, 5_700_000, None, 360),
        ("Hitachi", "EX5600-7", 34, 8_500_000, None, 540),
        ("Hitachi", "EX8000-7", 43, 11_500_000, None, 830),
        ("Volvo CE", "EC750E", 5.16, 850_000, 385, 75),
        ("Volvo CE", "EC950F", 6, 1_100_000, None, 95),
        ("SANY", "SY750H", 4.6, 750_000, None, 76),
        ("SANY", "SY980H", 6.1, 1_100_000, None, 95),
        ("SANY", "SY1250H", 8, 1_800_000, None, 125),
        ("SANY", "SY2000H", 12, 3_000_000, None, 200),
    ],
    "excavator",
    "Mining excavator, hydraulic shovel, or rope shovel for truck loading.",
)

SURFACE_LOADERS = by_bucket(
    [
        ("Caterpillar", "950 GC", 3.1, 290_000, 168, 19),
        ("Caterpillar", "966", 4.2, 430_000, 239, 24),
        ("Caterpillar", "972", 4.8, 520_000, 253, 26),
        ("Caterpillar", "980", 5.7, 650_000, 313, 31),
        ("Caterpillar", "982", 6.1, 760_000, 335, 35),
        ("Caterpillar", "986K", 5.4, 900_000, 335, 44),
        ("Caterpillar", "988K", 6.9, 1_300_000, 403, 51),
        ("Caterpillar", "990K", 9.2, 1_850_000, 521, 80),
        ("Caterpillar", "992", 12.3, 3_000_000, None, 105),
        ("Caterpillar", "993K", 14.5, 3_800_000, None, 133),
        ("Caterpillar", "994K", 19, 5_000_000, None, 240),
        ("Komatsu", "WA470-8", 4.2, 420_000, 204, 24),
        ("Komatsu", "WA480-8", 4.8, 500_000, 224, 26),
        ("Komatsu", "WA500-8", 5.4, 620_000, 266, 35),
        ("Komatsu", "WA600-8", 6.4, 850_000, 396, 54),
        ("Komatsu", "WA800-8", 10.5, 1_700_000, None, 115),
        ("Komatsu", "WA900-8", 13, 2_200_000, None, 116),
        ("Komatsu", "WA1200-6", 20, 4_500_000, None, 216),
        ("Volvo CE", "L150H", 4.2, 400_000, 220, 25),
        ("Volvo CE", "L180H", 4.6, 470_000, 245, 28),
        ("Volvo CE", "L220H", 5.2, 560_000, 273, 32),
        ("Volvo CE", "L260H", 6.1, 700_000, 310, 35),
        ("Volvo CE", "L350H", 6.9, 1_200_000, 397, 56),
        ("Hitachi", "ZW310-6", 4.2, 390_000, None, 24),
        ("Hitachi", "ZW370-6", 4.8, 480_000, None, 33),
        ("Hitachi", "ZW550-6", 6.5, 850_000, None, 47),
        ("XCMG", "LW600KN", 3.5, 260_000, None, 20),
        ("XCMG", "LW700KV", 4.2, 360_000, None, 24),
        ("XCMG", "LW800KN", 5, 440_000, None, 30),
        ("XCMG", "LW900KN", 6, 540_000, None, 35),
        ("XCMG", "LW1200KN", 6.5, 650_000, None, 52),
        ("SANY", "SW405K", 3.5, 240_000, None, 18),
        ("SANY", "SW955K", 5, 420_000, None, 31),
        ("SANY", "SW966K", 6, 520_000, None, 35),
        ("Liebherr", "L 586 XPower", 6, 620_000, 260, 33),
    ],
    "loader",
    "Surface wheel loader for truck loading, stockpiles, and support duties.",
)

DOZERS = [
    spec("Caterpillar", "D6", "dozer", "Track-type tractor for mine support and reclamation.", "Medium dozer class", 650_000, enginePowerKw=161, operatingWeightTons=23),
    spec("Caterpillar", "D6 XE", "dozer", "Electric-drive track-type tractor for support and cleanup.", "Medium dozer class", 780_000, operatingWeightTons=24),
    spec("Caterpillar", "D7", "dozer", "Track-type tractor for production support.", "Large dozer class", 850_000, operatingWeightTons=29),
    spec("Caterpillar", "D8", "dozer", "Heavy track-type tractor for mine support.", "Large dozer class", 1_050_000, operatingWeightTons=38),
    spec("Caterpillar", "D8T", "dozer", "Heavy track-type tractor for dump and road maintenance.", "Large dozer class", 1_150_000, operatingWeightTons=39),
    spec("Caterpillar", "D9", "dozer", "Mining dozer for pioneering, cleanup, and dump maintenance.", "49 t operating-weight class", 1_300_000, enginePowerKw=306, operatingWeightTons=49),
    spec("Caterpillar", "D10T2", "dozer", "Large mining dozer for production support.", "70 t operating-weight class", 1_850_000, operatingWeightTons=70),
    spec("Caterpillar", "D11", "dozer", "Largest Caterpillar track-type tractor for mining.", "104 t operating-weight class", 2_500_000, enginePowerKw=634, operatingWeightTons=104),
    spec("Caterpillar", "D11 XE", "dozer", "Electric-drive ultra-class mining dozer.", "Ultra-class mining dozer", 2_850_000, operatingWeightTons=105, powerType="hybrid"),
    spec("Komatsu", "D61EX-24", "dozer", "Production support dozer for smaller mines.", "Medium dozer class", 600_000, operatingWeightTons=19),
    spec("Komatsu", "D65EX-18", "dozer", "Medium crawler dozer for earthmoving and support.", "Medium dozer class", 700_000, operatingWeightTons=22),
    spec("Komatsu", "D71PX-24", "dozer", "Hydrostatic dozer for site development and support.", "Medium dozer class", 780_000, operatingWeightTons=24),
    spec("Komatsu", "D85EX-18", "dozer", "Large crawler dozer for mine support.", "Large dozer class", 900_000, operatingWeightTons=28),
    spec("Komatsu", "D155AX-8", "dozer", "Heavy crawler dozer for mine roads and dumps.", "Large dozer class", 1_150_000, operatingWeightTons=42),
    spec("Komatsu", "D275AX-5", "dozer", "Mining support crawler dozer.", "Large mining dozer class", 1_600_000, operatingWeightTons=50),
    spec("Komatsu", "D375A-8", "dozer", "Large mining dozer for dump and road maintenance.", "72 t operating-weight class", 1_900_000, operatingWeightTons=72),
    spec("Komatsu", "D475A-8", "dozer", "Ultra-large crawler dozer for surface mines.", "112 t operating-weight class", 2_700_000, operatingWeightTons=112),
    spec("Komatsu", "D575A-3", "dozer", "Super dozer used in large-scale mining earthworks.", "Ultra-large dozer class", 3_200_000),
    spec("Liebherr", "PR 736", "dozer", "Hydrostatic crawler tractor for support earthworks.", "Medium dozer class", 650_000),
    spec("Liebherr", "PR 746", "dozer", "Crawler tractor for mine support.", "Large dozer class", 850_000),
    spec("Liebherr", "PR 756", "dozer", "Large crawler tractor for mine and quarry support.", "Large dozer class", 1_100_000),
    spec("Liebherr", "PR 766", "dozer", "Heavy crawler tractor for mining support.", "Heavy dozer class", 1_500_000),
    spec("Liebherr", "PR 776", "dozer", "Large crawler tractor for mining support.", "Large mining dozer class", 1_800_000),
    spec("XCMG", "DL210KV", "dozer", "Wheel dozer used for mine stockpile and support work.", "Wheel dozer class", 520_000),
    spec("XCMG", "DL560KV", "dozer", "Large wheel dozer for bulk material support.", "Large wheel dozer class", 980_000),
]

GRADERS = [
    spec("Caterpillar", "120", "grader", "Motor grader for mine roads and drainage maintenance.", "Small motor grader class", 330_000, enginePowerKw=104),
    spec("Caterpillar", "140", "grader", "Motor grader for haul-road maintenance.", "Medium motor grader class", 430_000, enginePowerKw=136),
    spec("Caterpillar", "150", "grader", "Motor grader for mine roads and site support.", "Medium motor grader class", 480_000, enginePowerKw=151),
    spec("Caterpillar", "160", "grader", "Motor grader for haul roads and infrastructure.", "Large motor grader class", 560_000, enginePowerKw=166),
    spec("Caterpillar", "14", "grader", "Large motor grader for mine haul roads.", "Large motor grader class", 760_000),
    spec("Caterpillar", "16", "grader", "Mine-class motor grader for haul-road maintenance.", "Mine-class motor grader", 950_000),
    spec("Caterpillar", "18", "grader", "Large mine-class motor grader for wide haul roads.", "Mine-class motor grader", 1_250_000),
    spec("Caterpillar", "24", "grader", "Largest Caterpillar motor grader for ultra-class haul roads.", "Ultra-class motor grader", 1_900_000),
    spec("Komatsu", "GD655-7", "grader", "Motor grader for mine roads and construction support.", "Medium motor grader class", 360_000),
    spec("Komatsu", "GD675-7", "grader", "Motor grader for haul-road maintenance.", "Large motor grader class", 440_000),
    spec("Komatsu", "GD825A-2", "grader", "Large motor grader for mine haul roads.", "Large motor grader class", 800_000),
    spec("Volvo CE", "G930", "grader", "Motor grader for road maintenance fleets.", "Motor grader class", 260_000),
    spec("Volvo CE", "G940", "grader", "Motor grader for construction and mine support.", "Motor grader class", 300_000),
    spec("Volvo CE", "G960", "grader", "Heavy motor grader for mine support roads.", "Heavy motor grader class", 390_000),
    spec("XCMG", "GR5505", "grader", "Large motor grader for mine haul-road maintenance.", "Large motor grader class", 420_000),
]

DRILLS = (
    simple_models("Epiroc", ["Pit Viper 231", "Pit Viper 235", "Pit Viper 271 XC", "Pit Viper 275", "Pit Viper 311", "Pit Viper 316"], "drill", "Rotary blasthole drill for surface mining.", "Surface rotary blasthole drill class", 2_600_000, 250_000)
    + simple_models("Epiroc", ["SmartROC D50", "SmartROC D55", "SmartROC D60", "SmartROC D65", "FlexiROC D65"], "drill", "Surface drill rig for production drilling and quarrying.", "Surface drill rig class", 700_000, 80_000)
    + simple_models("Sandvik", ["DR410i", "DR412i", "DR413i", "DR416i", "DR461i", "D25KS", "D45KS"], "drill", "Surface blasthole drill for open-pit production.", "Surface blasthole drill class", 1_800_000, 180_000)
    + simple_models("Sandvik", ["Leopard DI550", "Pantera DP1500i"], "drill", "Top-hammer drill rig for quarry and surface mining.", "Surface top-hammer drill class", 750_000, 120_000)
    + simple_models("Caterpillar", ["MD6200", "MD6250", "MD6310", "MD6380", "MD6420", "MD6640"], "drill", "Rotary blasthole drill for surface mining benches.", "Surface rotary drill class", 1_900_000, 220_000)
    + simple_models("Komatsu", ["ZR77", "ZR122", "ZR160"], "drill", "Surface blasthole drill from the Komatsu drill range.", "Surface blasthole drill class", 1_600_000, 250_000)
    + simple_models("Atlas Copco", ["DM45"], "drill", "Legacy surface blasthole drill still common in mining fleets.", "Surface blasthole drill class", 850_000)
)

UNDERGROUND_TRUCKS = by_payload(
    [
        ("Sandvik", "TH315", "", 15, 900_000, None),
        ("Sandvik", "TH320", "", 20, 1_050_000, None),
        ("Sandvik", "TH430", "", 30, 1_250_000, None),
        ("Sandvik", "TH545i", "", 45, 1_500_000, None),
        ("Sandvik", "TH551i", "", 51, 1_700_000, None),
        ("Sandvik", "TH663i", "", 63, 1_900_000, None),
        ("Sandvik", "TH665B", "", 65, 2_200_000, None),
        ("Epiroc", "Minetruck MT2010", "", 20, 950_000, None),
        ("Epiroc", "Minetruck MT2200", "", 22, 1_050_000, None),
        ("Epiroc", "Minetruck MT42", "", 42, 1_450_000, None),
        ("Epiroc", "Minetruck MT436B", "", 32.6, 1_250_000, None),
        ("Epiroc", "Minetruck MT5020", "", 50, 1_650_000, None),
        ("Epiroc", "Minetruck MT54", "", 54, 1_750_000, None),
        ("Epiroc", "Minetruck MT6020", "", 60, 1_900_000, None),
        ("Epiroc", "Minetruck MT65", "", 65, 2_050_000, None),
        ("Epiroc", "Minetruck MT66", "", 66, 2_150_000, None),
        ("Caterpillar", "AD22", "", 22, 1_000_000, None),
        ("Caterpillar", "AD30", "", 30, 1_200_000, None),
        ("Caterpillar", "AD45", "", 45, 1_400_000, None),
        ("Caterpillar", "AD45B", "", 45, 1_500_000, None),
        ("Caterpillar", "AD55", "", 55, 1_650_000, None),
        ("Caterpillar", "AD55B", "", 55, 1_750_000, None),
        ("Caterpillar", "AD63", "", 63, 1_950_000, None),
        ("Komatsu", "Joy 10SC Shuttle Car", "", 10, 650_000, None),
        ("Komatsu", "Joy 21SC Shuttle Car", "", 21, 850_000, None),
    ],
    "undergroundTruck",
    "Underground truck or shuttle car for hard-rock haulage.",
)

UNDERGROUND_LOADERS = by_payload(
    [
        ("Sandvik", "LH202", "", 3, 430_000, None),
        ("Sandvik", "LH203", "", 3.5, 480_000, None),
        ("Sandvik", "LH204", "", 4.5, 540_000, None),
        ("Sandvik", "LH307", "", 7, 720_000, None),
        ("Sandvik", "LH410", "", 10, 900_000, None),
        ("Sandvik", "LH514", "", 14, 1_100_000, None),
        ("Sandvik", "LH517i", "", 17, 1_400_000, None),
        ("Sandvik", "LH518B", "", 18, 1_650_000, None),
        ("Sandvik", "LH621i", "", 21, 1_700_000, None),
        ("Epiroc", "Scooptram ST2G", "", 4, 430_000, None),
        ("Epiroc", "Scooptram ST3.5", "", 6, 520_000, None),
        ("Epiroc", "Scooptram ST7", "", 7, 750_000, None),
        ("Epiroc", "Scooptram ST7 Battery", "", 7, 980_000, None),
        ("Epiroc", "Scooptram ST14", "", 14, 1_100_000, None),
        ("Epiroc", "Scooptram ST14 Battery", "", 14, 1_450_000, None),
        ("Epiroc", "Scooptram ST18", "", 18, 1_350_000, None),
        ("Epiroc", "Scooptram ST18 SG", "", 18, 1_450_000, None),
        ("Epiroc", "Scooptram EST1030", "", 10, 1_100_000, None),
        ("Caterpillar", "R1300G", "", 6.8, 720_000, None),
        ("Caterpillar", "R1600H", "", 10.2, 950_000, None),
        ("Caterpillar", "R1700", "", 15, 1_450_000, None),
        ("Caterpillar", "R1700 XE", "", 15, 1_750_000, None),
        ("Caterpillar", "R2900G", "", 17.2, 1_350_000, None),
        ("Caterpillar", "R3000H", "", 20, 1_650_000, None),
        ("Komatsu", "WX03", "", 3, 420_000, None),
        ("Komatsu", "WX04", "", 4, 480_000, None),
        ("Komatsu", "WX07", "", 7, 700_000, None),
        ("Komatsu", "WX11", "", 11, 920_000, None),
        ("Komatsu", "WX15", "", 15, 1_200_000, None),
        ("Komatsu", "WX18H", "", 18, 1_450_000, None),
    ],
    "undergroundLoader",
    "Underground LHD loader for development and production mucking.",
)

for row in UNDERGROUND_LOADERS:
    if "Battery" in row["model"] or row["model"] in {"R1700 XE", "WX18H", "Scooptram EST1030"}:
        row["powerType"] = "electric"
        row["notes"] = "Battery-electric or electric-drive model; direct diesel fuel use omitted."

JUMBOS = (
    simple_models("Sandvik", ["DD210", "DD311", "DD321", "DD421", "DD422i", "DD422iE", "DD521", "DD530", "DT821", "DT922i"], "jumbo", "Development drill jumbo for underground headings and tunnels.", "Underground jumbo drill class", 850_000, 80_000)
    + simple_models("Epiroc", ["Boomer S1", "Boomer S2", "Boomer M1", "Boomer M2", "Boomer M20", "Boomer E1", "Boomer E2", "Boomer E3", "Boomer XE3", "Boomer XL3"], "jumbo", "Face drilling jumbo for underground development.", "Underground face drilling jumbo class", 850_000, 90_000)
)

for row in JUMBOS:
    if row["model"] == "DD422iE":
        row["powerType"] = "electric"
        row["notes"] = "Battery-electric jumbo variant; direct diesel fuel use omitted."

BOLTERS = (
    simple_models("Sandvik", ["DS211L", "DS2710", "DS311", "DS411", "DS412iE", "DS422i", "DS512i", "DS612i"], "bolter", "Underground rock bolter for ground support.", "Underground bolter class", 700_000, 80_000)
    + simple_models("Epiroc", ["Boltec S", "Boltec M", "Boltec E", "Boltec SL", "Cabletec M", "Cabletec L", "Cabletec LC"], "bolter", "Mechanized bolting or cable bolting rig for underground support.", "Underground bolter class", 720_000, 90_000)
)

SHOTCRETE = (
    simple_models("Normet", ["Spraymec 8100 VC", "Spraymec 7110 VC", "Spraymec MF 050 VC", "Spraymec MF 050 VC SD", "Spraymec Alpha 30"], "shotcrete", "Mechanized shotcrete sprayer for underground ground support.", "Shotcrete sprayer class", 650_000, 70_000)
    + simple_models("Epiroc", ["MEYCO Potenza", "MEYCO Suprema", "MEYCO Versa"], "shotcrete", "Concrete spraying system for underground support.", "Shotcrete spraying system class", 520_000, 80_000)
    + simple_models("MacLean", ["SS5 Shotcrete Sprayer", "SS3 Shotcrete Sprayer"], "shotcrete", "Underground shotcrete sprayer for development support.", "Shotcrete sprayer class", 650_000, 70_000)
)

SCALERS = (
    simple_models("Normet", ["Scamec 2000", "Scamec 2000 S", "Scamec LC", "Scamec 7110"], "scaler", "Underground scaler for mechanized rock scaling.", "Underground scaler class", 600_000, 60_000)
    + simple_models("Epiroc", ["Scaletec MC", "Scaletec LC"], "scaler", "Underground scaling rig for development headings.", "Underground scaler class", 620_000, 70_000)
    + simple_models("MacLean", ["RB3 Rockbreaker", "RB4 Rockbreaker"], "scaler", "Mobile rockbreaker used for underground scaling and oversize breaking.", "Mobile scaler / rockbreaker class", 650_000, 80_000)
)

UNDERGROUND_MISC = (
    simple_models("Normet", ["Charmec MC 605 D", "Charmec MF 605 D", "Variomec XS 035", "Variomec MF 060 D", "Utimec LF 090 D", "Utimec MF 500", "Multimec MF 100", "Himec RM 915"], "underground", "Underground utility vehicle for charging, lifting, transport, or construction support.", "Underground utility vehicle class", 520_000, 70_000)
    + simple_models("MacLean", ["SL3 Scissor Lift", "ML5 Multi-Lift", "GR5 Grader", "CS3 Cassette Truck", "AC3 Explosives Charger", "MV5 Shotcrete Carrier", "WC3 Water Cannon"], "underground", "Underground utility vehicle for mine services and maintenance.", "Underground utility vehicle class", 560_000, 70_000)
)

CRUSHERS = (
    simple_models("Metso", ["C80", "C96", "C106", "C116", "C120", "C130", "C150", "C160", "C200"], "crusher", "Nordberg C Series jaw crusher for primary crushing.", "Jaw crusher class", 450_000, 120_000, powerType="electric")
    + simple_models("Metso", ["HP200", "HP300", "HP400", "HP500", "HP6", "GP330", "GP500S", "NP1415", "NP1620"], "crusher", "Cone or impact crusher for secondary and tertiary crushing.", "Crusher class", 550_000, 130_000, powerType="electric")
    + simple_models("Sandvik", ["CJ411", "CJ412", "CJ613", "CJ615", "CH430", "CH440", "CH660"], "crusher", "Jaw or cone crusher for mineral processing circuits.", "Crusher class", 500_000, 140_000, powerType="electric")
)

SCREENS = (
    simple_models("Metso", ["CVB1540", "CVB1845", "CVB2060", "ES202", "ES303", "ES403", "MF2473", "MF3073"], "screen", "Vibrating screen for classification in crushing circuits.", "Vibrating screen class", 180_000, 35_000, powerType="electric")
    + simple_models("Sandvik", ["QA335", "QA441", "QE342", "QE442", "SK2462", "SK3062", "SS1223"], "screen", "Mobile or stationary screen for aggregate and mineral sizing.", "Screening plant class", 220_000, 45_000, powerType="electric")
)

MILLS = (
    simple_models("Metso", ["Premier SAG Mill 24x14", "Premier SAG Mill 28x14", "Premier Ball Mill 18x28", "Premier Ball Mill 22x36", "Select Ball Mill 14x20", "Select Ball Mill 18x24"], "mill", "Grinding mill for mineral processing comminution circuits.", "Grinding mill class", 3_500_000, 450_000, powerType="electric", usefulLifeYears=20)
    + simple_models("Metso", ["Vertimill VTM-1500-WB", "Vertimill VTM-3000-WB", "Vertimill VTM-4500-C", "HIGmill HIG3500", "HIGmill HIG5000"], "mill", "Vertical or stirred mill for fine grinding.", "Fine grinding mill class", 1_800_000, 300_000, powerType="electric", usefulLifeYears=20)
    + simple_models("FLSmidth", ["Fuller-Traylor SAG Mill 32 ft", "Fuller-Traylor SAG Mill 40 ft", "Fuller-Traylor Ball Mill 20 ft", "Fuller-Traylor Ball Mill 26 ft", "FT Series Grinding Mill 16 ft", "FT Series Grinding Mill 24 ft"], "mill", "FLSmidth grinding mill for concentrator circuits.", "Grinding mill class", 3_200_000, 450_000, powerType="electric", usefulLifeYears=20)
    + simple_models("FLSmidth", ["VXPmill VXP5000", "VXPmill VXP10000", "HPGR Pro 24-17"], "mill", "FLSmidth fine grinding or HPGR comminution equipment.", "Comminution equipment class", 2_200_000, 400_000, powerType="electric", usefulLifeYears=20)
)

CONVEYORS = (
    simple_models("Metso", ["Lokolink LL12", "Lokolink LL16", "Nordtrack CW24", "Nordtrack CW85"], "conveyor", "Mobile conveyor for crushing and screening circuits.", "Mobile conveyor class", 220_000, 60_000, powerType="electric")
    + simple_models("Sandvik", ["PF300", "PF400", "PB100-1200/21+26", "PA200"], "conveyor", "Mobile crushing or conveying unit for in-pit systems.", "In-pit conveying class", 1_500_000, 300_000, powerType="electric")
    + simple_models("FLSmidth", ["KOCH Pipe Conveyor", "RAHCO Mobile Conveyor", "Overland Conveyor 1800", "Cross-Pit Conveyor 2400"], "conveyor", "Overland, pipe, or mobile conveyor for mine material transport.", "Bulk conveyor class", 1_200_000, 250_000, powerType="electric")
)

STACKERS = simple_models(
    "FLSmidth",
    ["Mobile Stacking Conveyor", "Longitudinal Stacker", "Circular Stacker Reclaimer", "Bridge Scraper Reclaimer", "Portal Scraper Reclaimer", "Bucket Wheel Stacker Reclaimer", "Circular Blending Bed"],
    "stacker",
    "Stacker or reclaimer for stockyard material handling.",
    "Stockyard stacker/reclaimer class",
    1_600_000,
    300_000,
    powerType="electric",
    usefulLifeYears=20,
)

PUMPS = (
    simple_models("Metso", ["Orion HM100", "Orion HM150", "Orion HM200", "Orion HH150", "MDM300", "MDM400"], "pump", "Slurry pump for mill discharge and process duties.", "Slurry pump class", 120_000, 35_000, powerType="electric")
    + simple_models("FLSmidth", ["KREBS millMAX 6x4", "KREBS millMAX 8x6", "KREBS millMAX 10x8", "KREBS millMAX 12x10", "KREBS gravelMAX", "Technequip TG Pump"], "pump", "Process slurry pump for mineral processing plants.", "Slurry pump class", 110_000, 35_000, powerType="electric")
)

COMPRESSORS = simple_models(
    "Atlas Copco",
    ["XAS 188", "XAS 288", "XAS 400", "XATS 138", "XAHS 186", "XAVS 378", "DrillAir Y35", "DrillAir Y1260", "XRVS 1000", "V900"],
    "compressor",
    "Portable air compressor for drilling and mine support.",
    "Portable compressor class",
    70_000,
    25_000,
)

THICKENERS = [
    spec("FLSmidth", "E-Volute Feedwell Thickener", "thickener", "High-rate thickener with FLSmidth feedwell technology.", "Process thickener class", 1_200_000, powerType="electric", usefulLifeYears=20),
    spec("FLSmidth", "High Rate Thickener", "thickener", "Conventional high-rate thickener for mineral processing.", "High-rate thickener class", 1_100_000, powerType="electric", usefulLifeYears=20),
    spec("FLSmidth", "High Density Thickener", "thickener", "High-density thickener for tailings and concentrate duties.", "High-density thickener class", 1_500_000, powerType="electric", usefulLifeYears=20),
    spec("FLSmidth", "Paste Thickener", "thickener", "Paste thickener for high-solids tailings applications.", "Paste thickener class", 1_900_000, powerType="electric", usefulLifeYears=20),
    spec("FLSmidth", "Deep Cone Thickener", "thickener", "Deep cone thickener for paste and tailings applications.", "Deep cone thickener class", 2_200_000, powerType="electric", usefulLifeYears=20),
    spec("FLSmidth", "EIMCO Thickener", "thickener", "EIMCO thickener used in minerals and tailings circuits.", "Thickener class", 1_000_000, powerType="electric", usefulLifeYears=20),
    spec("FLSmidth", "Dorr-Oliver Thickener", "thickener", "Dorr-Oliver thickener for process and tailings duty.", "Thickener class", 1_050_000, powerType="electric", usefulLifeYears=20),
    spec("Metso", "High Rate Thickener", "thickener", "Metso high-rate thickener for concentrator circuits.", "High-rate thickener class", 1_150_000, powerType="electric", usefulLifeYears=20),
]


DATASETS: list[tuple[str, str, list[Spec]]] = [
    ("surface-trucks.ts", "SURFACE_TRUCKS", TRUCKS),
    ("surface-excavators.ts", "SURFACE_EXCAVATORS", SURFACE_EXCAVATORS),
    ("surface-loaders.ts", "SURFACE_LOADERS", SURFACE_LOADERS),
    ("surface-dozers-graders.ts", "SURFACE_DOZERS_GRADERS", DOZERS + GRADERS),
    ("surface-drills-support.ts", "SURFACE_DRILLS_SUPPORT", DRILLS + WATER_TRUCKS + SERVICE_TRUCKS + SUPPORT),
    (
        "underground.ts",
        "UNDERGROUND_EQUIPMENT",
        UNDERGROUND_TRUCKS
        + UNDERGROUND_LOADERS
        + JUMBOS
        + BOLTERS
        + SHOTCRETE
        + SCALERS
        + UNDERGROUND_MISC,
    ),
    (
        "processing.ts",
        "PROCESSING_EQUIPMENT",
        CRUSHERS
        + SCREENS
        + MILLS
        + CONVEYORS
        + STACKERS
        + PUMPS
        + COMPRESSORS
        + THICKENERS,
    ),
]


def write_index(exports: list[tuple[str, str]]) -> None:
    imports = "\n".join(
        f"import {{ {export_name} }} from './{filename.removesuffix('.ts')}';"
        for filename, export_name in exports
    )
    export_block = "\n".join(
        f"export {{ {export_name} }} from './{filename.removesuffix('.ts')}';"
        for filename, export_name in exports
    )
    spreads = ",\n  ".join(f"...{export_name}" for _, export_name in exports)
    content = (
        "import type { CompactEquipmentSpec } from '../helpers';\n"
        f"{imports}\n\n"
        f"{export_block}\n\n"
        "export const ALL_COMPACT_EQUIPMENT: CompactEquipmentSpec[] = [\n"
        f"  {spreads},\n"
        "];\n"
    )
    (OUT_DIR / "index.ts").write_text(content, encoding="utf-8")


def write_seed_entry() -> None:
    content = """import { buildSeedRows, type EquipmentCatalogSeedRow } from './seed/helpers';
import { ALL_COMPACT_EQUIPMENT } from './seed/datasets';

export type { EquipmentCatalogSeedRow } from './seed/helpers';

export function buildEquipmentCatalogSeedRows(): EquipmentCatalogSeedRow[] {
  return buildSeedRows(ALL_COMPACT_EQUIPMENT);
}
"""
    (ROOT / "lib" / "master-data" / "equipment-seed-data.ts").write_text(
        content, encoding="utf-8"
    )


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    all_rows = [row for _, _, rows in DATASETS for row in rows]
    unique_rows = dedupe(all_rows)
    if len(unique_rows) != len(all_rows):
        unique_by_key = {
            (row["manufacturer"].casefold(), row["model"].casefold()): row
            for row in unique_rows
        }
        deduped_datasets: list[tuple[str, str, list[Spec]]] = []
        for filename, export_name, rows in DATASETS:
            filtered = []
            for row in rows:
                key = (row["manufacturer"].casefold(), row["model"].casefold())
                if unique_by_key.get(key) is row:
                    filtered.append(row)
            deduped_datasets.append((filename, export_name, filtered))
    else:
        deduped_datasets = DATASETS

    for filename, export_name, rows in deduped_datasets:
        write_dataset(filename, export_name, rows)
    write_index([(filename, export_name) for filename, export_name, _ in deduped_datasets])
    write_seed_entry()

    final_rows = [row for _, _, rows in deduped_datasets for row in rows]
    category_counts = Counter(row["category"] for row in final_rows)
    total = len(final_rows)

    print("Category counts:")
    for category in sorted(category_counts):
        print(f"  {category}: {category_counts[category]}")
    print(f"Total: {total}")
    print("Files written:")
    for filename, _, _ in deduped_datasets:
        print(f"  {OUT_DIR / filename}")
    print(f"  {OUT_DIR / 'index.ts'}")
    print(f"  {ROOT / 'lib/master-data/equipment-seed-data.ts'}")

    if not 400 <= total <= 450:
        raise SystemExit(f"Generated total {total} is outside requested 400-450 range")


if __name__ == "__main__":
    main()
