import { PrismaClient } from '@prisma/client';
import {
  performFullAnalysis,
  type ProjectParams,
} from '../lib/calculations';
import { seedEquipmentCatalogIdempotent } from '../lib/master-data';
import { ensureAllDemoProjects } from '../lib/demo';

const prisma = new PrismaClient();

interface SeedProject {
  id: string;
  name: string;
  mineType: string;
  miningMethod: string;
  location: string;
  currency: string;
  exchangeRate: number;
  fuelPricePerLiter: number;
  electricityUnitPrice: number;
  explosiveUnitPrice: number;
  totalReserves: number;
  maxAnnualCapacity: number;
  oreGrade: number;
  oreGradeUnit: string;
  waterConsumptionDaily: number;
  rehabilitationAreaHa: number;
  rehabilitationCostPerHa: number;
  loanAmount: number;
  loanInterestRate: number;
  loanTermYears: number;
  equityRatio: number;
  depreciationMethod: string;
  equipmentRenewalEnabled?: boolean;
  equipmentRenewalCycleYears?: number;
  latitude: number;
  longitude: number;
  workDaysPerYear?: number;
  params: ProjectParams;
  equipments: any[];
  personnels: any[];
  byProducts: any[];
  methodCosts: any[];
}

const PROJECTS: SeedProject[] = [
  // ========== 1. MUĞLA LİNYİT AÇIK OCAK ==========
  {
    id: 'seed-lignite-001',
    name: 'Muğla Yatağan Linyit Projesi',
    mineType: 'lignite',
    miningMethod: 'openPit',
    location: 'Yatağan, Muğla',
    currency: 'USD',
    exchangeRate: 1.0,
    fuelPricePerLiter: 1.35,
    electricityUnitPrice: 0.085,
    explosiveUnitPrice: 1.80,
    totalReserves: 60,
    maxAnnualCapacity: 2.5,
    oreGrade: 2800,
    oreGradeUnit: 'kcal/kg',
    waterConsumptionDaily: 850,
    rehabilitationAreaHa: 320,
    rehabilitationCostPerHa: 12000,
    loanAmount: 120,
    loanInterestRate: 6.5,
    loanTermYears: 12,
    equityRatio: 65,
    depreciationMethod: 'linear',
    equipmentRenewalEnabled: true,
    equipmentRenewalCycleYears: 10,
    latitude: 37.3410,
    longitude: 28.1341,
    params: {
      projectLifeYears: 30,
      discountRate: 5.82,
      taxRate: 22,
      royaltyRate: 4,
      creditRate: 6.5,
      creditYears: 12,
      unitPrice: 75,
      annualProduction: 2.0,
      plantProcessingRate: 35,
      equipmentCost: 53.385,
      facilityCost: 318.0,
      infrastructureCost: 5.9,
      contingencyRate: 10,
      totalCapex: 355.9,
      fuelCost: 2.605,
      personnelCost: 4.28,
      maintenanceCost: 0.494,
      explosivesCost: 7.348,
      tireCost: 0.021,
      strippingCost: 0,
      otherOpex: 1.475,
      totalOpex: 16.223,
      forestCost: 5.022,
      landCost: 1.0,
      rehabilitationCost: 0.75,
      annualStrippingVolume: 13.92,
      strippingUnitCost: 1.05,
      contractorStrippingCost: 2.73,
      plantOperatingCost: 0,
      equipmentDepLife: 6,
      facilityDepLife: 15,
      byProductRevenue: 0,
      fuelPricePerLiter: 1.35,
      electricityUnitPrice: 0.085,
      explosiveUnitPrice: 1.80,
      totalReserves: 60,
      oreGrade: 2800,
      waterConsumptionDaily: 850,
      rehabilitationAreaHa: 320,
      rehabilitationCostPerHa: 12000,
      loanAmount: 120,
      loanInterestRate: 6.5,
      loanTermYears: 12,
      equityRatio: 65,
    },
    equipments: [
      { machineType: 'CAT 390F Ekskavatör', equipmentCategory: 'excavator', model: 'CAT 390F', tonnageCapacity: '90 ton', quantity: 3, spareQuantity: 1, unitCost: 850000, totalCost: 3400000, dailyWorkHours: 16, maintenancePeriodHours: 500, operatorCount: 2, powerType: 'diesel', hourlyFuelConsumption: 65, maintenanceCost: 45000, fuelConsumption: 65, productionImpact: 450, bucketVolume: 6.5 },
      { machineType: 'CAT 777G Kamyon', equipmentCategory: 'truck', model: 'CAT 777G', tonnageCapacity: '100 ton', quantity: 8, spareQuantity: 2, unitCost: 520000, totalCost: 5200000, dailyWorkHours: 16, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 55, maintenanceCost: 28000, fuelConsumption: 55, productionImpact: 280, transportCapacity: 100 },
      { machineType: 'Atlas Copco FlexiROC D65', equipmentCategory: 'drill', model: 'FlexiROC D65', tonnageCapacity: '', quantity: 2, spareQuantity: 0, unitCost: 380000, totalCost: 760000, dailyWorkHours: 12, maintenancePeriodHours: 400, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 35, maintenanceCost: 22000, fuelConsumption: 35, productionImpact: 25, drillCapacity: 25, holeDiameter: 152, maxDrillDepth: 45 },
      { machineType: 'CAT D10T2 Dozer', equipmentCategory: 'dozer', model: 'CAT D10T2', tonnageCapacity: '66 ton', quantity: 2, spareQuantity: 1, unitCost: 620000, totalCost: 1860000, dailyWorkHours: 14, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 50, maintenanceCost: 32000, fuelConsumption: 50, productionImpact: 0 },
      { machineType: 'CAT 14M3 Greyder', equipmentCategory: 'grader', model: 'CAT 14M3', tonnageCapacity: '', quantity: 1, spareQuantity: 0, unitCost: 310000, totalCost: 310000, dailyWorkHours: 10, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 22, maintenanceCost: 15000, fuelConsumption: 22, productionImpact: 0 },
      { machineType: 'CAT 980M Yükleyici', equipmentCategory: 'loader', model: 'CAT 980M', tonnageCapacity: '35 ton', quantity: 2, spareQuantity: 0, unitCost: 420000, totalCost: 840000, dailyWorkHours: 14, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 32, maintenanceCost: 20000, fuelConsumption: 32, productionImpact: 320, loadingCapacity: 320, bucketVolume: 7.5 },
      { machineType: 'Su Tankeri (20.000L)', equipmentCategory: 'support', model: 'MAN TGS', tonnageCapacity: '20000 lt', quantity: 2, spareQuantity: 0, unitCost: 180000, totalCost: 360000, dailyWorkHours: 10, maintenancePeriodHours: 600, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 18, maintenanceCost: 8000, fuelConsumption: 18, productionImpact: 0 },
    ],
    personnels: [
      { role: 'Maden Mühendisi', count: 3, monthlySalary: 4500 },
      { role: 'Jeoloji Mühendisi', count: 2, monthlySalary: 4200 },
      { role: 'Çevre Mühendisi', count: 1, monthlySalary: 4000 },
      { role: 'Vardiya Amiri', count: 4, monthlySalary: 3200 },
      { role: 'Ekskavatör Operatörü', count: 8, monthlySalary: 2800 },
      { role: 'Kamyon Şoförü', count: 12, monthlySalary: 2400 },
      { role: 'Delici Operatörü', count: 4, monthlySalary: 2600 },
      { role: 'Dozer Operatörü', count: 3, monthlySalary: 2500 },
      { role: 'Bakım Teknisyeni', count: 6, monthlySalary: 2800 },
      { role: 'Elektrik Teknisyeni', count: 3, monthlySalary: 2700 },
      { role: 'İdari Personel', count: 5, monthlySalary: 2200 },
      { role: 'Güvenlik', count: 6, monthlySalary: 1800 },
      { role: 'Sağlık Personeli', count: 2, monthlySalary: 3000 },
    ],
    byProducts: [],
    methodCosts: [
      { name: 'Pasa Döküm', category: 'openPit', value: 3.2, unit: 'MUSD' },
      { name: 'Dekapaj', category: 'openPit', value: 14.6, unit: 'MUSD' },
      { name: 'Şev Açıları Düzenleme', category: 'openPit', value: 0.8, unit: 'MUSD' },
      { name: 'Yol Yapımı', category: 'openPit', value: 1.5, unit: 'MUSD' },
      { name: 'Patlatma Giderleri', category: 'openPit', value: 7.35, unit: 'MUSD' },
      { name: 'Basamak Düzenleme', category: 'openPit', value: 0.6, unit: 'MUSD' },
    ],
  },

  // ========== 2. ARTVİN ALTIN MADENİ ==========
  {
    id: 'seed-gold-001',
    name: 'Artvin Çerattepe Altın-Bakır Projesi',
    mineType: 'gold',
    miningMethod: 'openPit',
    location: 'Çerattepe, Artvin',
    currency: 'USD',
    exchangeRate: 1.0,
    fuelPricePerLiter: 1.40,
    electricityUnitPrice: 0.09,
    explosiveUnitPrice: 2.20,
    totalReserves: 2.8,
    maxAnnualCapacity: 0.35,
    oreGrade: 3.5,
    oreGradeUnit: 'g/ton',
    waterConsumptionDaily: 1200,
    rehabilitationAreaHa: 85,
    rehabilitationCostPerHa: 25000,
    loanAmount: 40,
    loanInterestRate: 7.5,
    loanTermYears: 8,
    equityRatio: 60,
    depreciationMethod: 'declining',
    latitude: 41.2500,
    longitude: 41.3500,
    params: {
      projectLifeYears: 15,
      discountRate: 8.0,
      taxRate: 22,
      royaltyRate: 4,
      creditRate: 7.5,
      creditYears: 8,
      unitPrice: 185,
      annualProduction: 0.35,
      plantProcessingRate: 92,
      equipmentCost: 28,
      facilityCost: 45,
      infrastructureCost: 12,
      contingencyRate: 12,
      totalCapex: 95.2,
      fuelCost: 3.2,
      personnelCost: 5.5,
      maintenanceCost: 1.8,
      explosivesCost: 2.0,
      tireCost: 0.18,
      strippingCost: 0,
      otherOpex: 1.5,
      totalOpex: 14.18,
      forestCost: 2.5,
      landCost: 1.5,
      rehabilitationCost: 3.0,
      annualStrippingVolume: 2,
      strippingUnitCost: 2.5,
      contractorStrippingCost: 0,
      plantOperatingCost: 3.5,
      equipmentDepLife: 5,
      facilityDepLife: 10,
      byProductRevenue: 1.8,
      fuelPricePerLiter: 1.40,
      electricityUnitPrice: 0.09,
      explosiveUnitPrice: 2.20,
      totalReserves: 2.8,
      oreGrade: 3.5,
      waterConsumptionDaily: 1200,
      rehabilitationAreaHa: 85,
      rehabilitationCostPerHa: 25000,
      loanAmount: 55,
      loanInterestRate: 7.5,
      loanTermYears: 8,
      equityRatio: 60,
    },
    equipments: [
      { machineType: 'Liebherr R 9200 Ekskavatör', equipmentCategory: 'excavator', model: 'Liebherr R 9200', tonnageCapacity: '200 ton', quantity: 2, spareQuantity: 1, unitCost: 1200000, totalCost: 3600000, dailyWorkHours: 18, maintenancePeriodHours: 400, operatorCount: 2, powerType: 'diesel', hourlyFuelConsumption: 85, maintenanceCost: 62000, fuelConsumption: 85, productionImpact: 600, bucketVolume: 12.5 },
      { machineType: 'Komatsu HD785-8 Kamyon', equipmentCategory: 'truck', model: 'HD785-8', tonnageCapacity: '91 ton', quantity: 6, spareQuantity: 1, unitCost: 480000, totalCost: 3360000, dailyWorkHours: 18, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 48, maintenanceCost: 25000, fuelConsumption: 48, productionImpact: 250, transportCapacity: 91 },
      { machineType: 'Sandvik DR461i Delici', equipmentCategory: 'drill', model: 'DR461i', tonnageCapacity: '', quantity: 1, spareQuantity: 0, unitCost: 520000, totalCost: 520000, dailyWorkHours: 14, maintenancePeriodHours: 350, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 42, maintenanceCost: 35000, fuelConsumption: 42, productionImpact: 30, drillCapacity: 30, holeDiameter: 170, maxDrillDepth: 55 },
      { machineType: 'Metso C130 Konkasör', equipmentCategory: 'crusher', model: 'Metso C130', tonnageCapacity: '600 ton/saat', quantity: 1, spareQuantity: 0, unitCost: 750000, totalCost: 750000, dailyWorkHours: 20, maintenancePeriodHours: 600, operatorCount: 2, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 48000, fuelConsumption: 0, productionImpact: 550, crushingCapacity: 550 },
      { machineType: 'CAT 992K Yükleyici', equipmentCategory: 'loader', model: 'CAT 992K', tonnageCapacity: '48 ton', quantity: 1, spareQuantity: 0, unitCost: 580000, totalCost: 580000, dailyWorkHours: 16, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 45, maintenanceCost: 28000, fuelConsumption: 45, productionImpact: 420, loadingCapacity: 420, bucketVolume: 10.7 },
    ],
    personnels: [
      { role: 'Maden Mühendisi', count: 2, monthlySalary: 5500 },
      { role: 'Jeoloji Mühendisi', count: 2, monthlySalary: 5200 },
      { role: 'Metalurji Mühendisi', count: 1, monthlySalary: 5000 },
      { role: 'Çevre Mühendisi', count: 1, monthlySalary: 4800 },
      { role: 'Vardiya Amiri', count: 3, monthlySalary: 3800 },
      { role: 'Ekipman Operatörü', count: 10, monthlySalary: 3200 },
      { role: 'Tesis Teknisyeni', count: 5, monthlySalary: 3000 },
      { role: 'Bakım Teknisyeni', count: 4, monthlySalary: 3200 },
      { role: 'Laboratuvar Teknisyeni', count: 3, monthlySalary: 2800 },
      { role: 'İdari Personel', count: 4, monthlySalary: 2500 },
      { role: 'Güvenlik', count: 8, monthlySalary: 2000 },
    ],
    byProducts: [
      { name: 'Gümüş', annualProduction: 800, productionUnit: 'kg', unitPrice: 28, priceUnit: 'USD/ons', totalRevenue: 0.72 },
      { name: 'Bakır Konsantresi', annualProduction: 2500, productionUnit: 'ton', unitPrice: 420, priceUnit: 'USD/ton', totalRevenue: 1.05 },
    ],
    methodCosts: [
      { name: 'Pasa Döküm', category: 'openPit', value: 4.8, unit: 'MUSD' },
      { name: 'Dekapaj', category: 'openPit', value: 18.0, unit: 'MUSD' },
      { name: 'Patlatma Giderleri', category: 'openPit', value: 2.8, unit: 'MUSD' },
      { name: 'Siyanür Liqi', category: 'openPit', value: 3.2, unit: 'MUSD' },
    ],
  },

  // ========== 3. SİVAS DEMİR MADENİ (AÇIK OCAK) ==========
  {
    id: 'seed-iron-001',
    name: 'Sivas Divriği Demir Madeni',
    mineType: 'iron',
    miningMethod: 'openPit',
    location: 'Divriği, Sivas',
    currency: 'USD',
    exchangeRate: 1.0,
    fuelPricePerLiter: 1.32,
    electricityUnitPrice: 0.078,
    explosiveUnitPrice: 1.65,
    totalReserves: 180,
    maxAnnualCapacity: 5.0,
    oreGrade: 56,
    oreGradeUnit: '%',
    waterConsumptionDaily: 1500,
    rehabilitationAreaHa: 450,
    rehabilitationCostPerHa: 10000,
    loanAmount: 200,
    loanInterestRate: 5.8,
    loanTermYears: 15,
    equityRatio: 55,
    depreciationMethod: 'linear',
    latitude: 39.3783,
    longitude: 38.1192,
    params: {
      projectLifeYears: 35,
      discountRate: 6.5,
      taxRate: 22,
      royaltyRate: 4,
      creditRate: 5.8,
      creditYears: 15,
      unitPrice: 120,
      annualProduction: 4.5,
      plantProcessingRate: 42,
      equipmentCost: 95,
      facilityCost: 220,
      infrastructureCost: 45,
      contingencyRate: 12,
      totalCapex: 403.2,
      fuelCost: 8.5,
      personnelCost: 7.2,
      maintenanceCost: 3.8,
      explosivesCost: 5.2,
      tireCost: 0.85,
      strippingCost: 6.5,
      otherOpex: 2.8,
      totalOpex: 34.85,
      forestCost: 3.0,
      landCost: 2.5,
      rehabilitationCost: 4.5,
      annualStrippingVolume: 22,
      strippingUnitCost: 1.8,
      contractorStrippingCost: 0,
      plantOperatingCost: 8.0,
      equipmentDepLife: 7,
      facilityDepLife: 15,
      byProductRevenue: 0,
      fuelPricePerLiter: 1.32,
      electricityUnitPrice: 0.078,
      totalReserves: 180,
      oreGrade: 56,
      waterConsumptionDaily: 1500,
      rehabilitationAreaHa: 450,
      rehabilitationCostPerHa: 10000,
      loanAmount: 200,
      loanInterestRate: 5.8,
      loanTermYears: 15,
      equityRatio: 55,
    },
    equipments: [
      { machineType: 'Liebherr R 9400 Ekskavatör', equipmentCategory: 'excavator', model: 'R 9400', tonnageCapacity: '250 ton', quantity: 4, spareQuantity: 1, unitCost: 1800000, totalCost: 9000000, dailyWorkHours: 20, maintenancePeriodHours: 400, operatorCount: 2, powerType: 'diesel', hourlyFuelConsumption: 110, maintenanceCost: 85000, fuelConsumption: 110, productionImpact: 800, bucketVolume: 22 },
      { machineType: 'CAT 793F Kamyon', equipmentCategory: 'truck', model: '793F', tonnageCapacity: '227 ton', quantity: 12, spareQuantity: 3, unitCost: 780000, totalCost: 11700000, dailyWorkHours: 20, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 75, maintenanceCost: 42000, fuelConsumption: 75, productionImpact: 500, transportCapacity: 227 },
      { machineType: 'Epiroc PV-271 Delici', equipmentCategory: 'drill', model: 'PV-271', tonnageCapacity: '', quantity: 3, spareQuantity: 1, unitCost: 450000, totalCost: 1800000, dailyWorkHours: 16, maintenancePeriodHours: 400, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 40, maintenanceCost: 28000, fuelConsumption: 40, productionImpact: 28, drillCapacity: 28, holeDiameter: 165, maxDrillDepth: 50 },
      { machineType: 'CAT D11T Dozer', equipmentCategory: 'dozer', model: 'D11T', tonnageCapacity: '104 ton', quantity: 3, spareQuantity: 1, unitCost: 850000, totalCost: 3400000, dailyWorkHours: 18, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 62, maintenanceCost: 45000, fuelConsumption: 62, productionImpact: 0 },
      { machineType: 'Metso GP330 Konkasör', equipmentCategory: 'crusher', model: 'GP330', tonnageCapacity: '800 ton/saat', quantity: 2, spareQuantity: 0, unitCost: 920000, totalCost: 1840000, dailyWorkHours: 20, maintenancePeriodHours: 600, operatorCount: 2, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 55000, fuelConsumption: 0, productionImpact: 750, crushingCapacity: 750 },
      { machineType: 'CAT 994K Yükleyici', equipmentCategory: 'loader', model: '994K', tonnageCapacity: '56 ton', quantity: 2, spareQuantity: 0, unitCost: 720000, totalCost: 1440000, dailyWorkHours: 18, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 55, maintenanceCost: 38000, fuelConsumption: 55, productionImpact: 550, loadingCapacity: 550, bucketVolume: 13.8 },
      { machineType: 'CAT 16M3 Greyder', equipmentCategory: 'grader', model: '16M3', tonnageCapacity: '', quantity: 2, spareQuantity: 0, unitCost: 380000, totalCost: 760000, dailyWorkHours: 12, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 28, maintenanceCost: 18000, fuelConsumption: 28, productionImpact: 0 },
    ],
    personnels: [
      { role: 'Maden Mühendisi', count: 4, monthlySalary: 4800 },
      { role: 'Jeoloji Mühendisi', count: 2, monthlySalary: 4500 },
      { role: 'Çevre Mühendisi', count: 2, monthlySalary: 4200 },
      { role: 'Makine Mühendisi', count: 2, monthlySalary: 4500 },
      { role: 'Vardiya Amiri', count: 6, monthlySalary: 3500 },
      { role: 'Ekskavatör Operatörü', count: 12, monthlySalary: 3000 },
      { role: 'Kamyon Şoförü', count: 18, monthlySalary: 2600 },
      { role: 'Delici Operatörü', count: 6, monthlySalary: 2800 },
      { role: 'Bakım Ekibi', count: 10, monthlySalary: 2900 },
      { role: 'Tesis Operatörü', count: 8, monthlySalary: 2700 },
      { role: 'İdari Personel', count: 6, monthlySalary: 2300 },
      { role: 'Güvenlik', count: 8, monthlySalary: 1900 },
      { role: 'Sağlık Personeli', count: 3, monthlySalary: 3200 },
    ],
    byProducts: [],
    methodCosts: [
      { name: 'Pasa Döküm', category: 'openPit', value: 8.5, unit: 'MUSD' },
      { name: 'Dekapaj', category: 'openPit', value: 39.6, unit: 'MUSD' },
      { name: 'Patlatma Giderleri', category: 'openPit', value: 5.2, unit: 'MUSD' },
      { name: 'Yol Yapımı', category: 'openPit', value: 3.8, unit: 'MUSD' },
      { name: 'Basamak Düzenleme', category: 'openPit', value: 1.2, unit: 'MUSD' },
    ],
  },

  // ========== 4. ZONGULDAK KÖMÜR (YER ALTI) ==========
  {
    id: 'seed-coal-001',
    name: 'Zonguldak Taşkömürü Projesi',
    mineType: 'coal',
    miningMethod: 'underground',
    location: 'Kozlu, Zonguldak',
    currency: 'USD',
    exchangeRate: 1.0,
    fuelPricePerLiter: 1.38,
    electricityUnitPrice: 0.092,
    explosiveUnitPrice: 2.10,
    totalReserves: 25,
    maxAnnualCapacity: 1.2,
    oreGrade: 6200,
    oreGradeUnit: 'kcal/kg',
    waterConsumptionDaily: 600,
    rehabilitationAreaHa: 45,
    rehabilitationCostPerHa: 18000,
    loanAmount: 85,
    loanInterestRate: 7.0,
    loanTermYears: 10,
    equityRatio: 50,
    depreciationMethod: 'declining',
    latitude: 41.4539,
    longitude: 31.7983,
    params: {
      projectLifeYears: 25,
      discountRate: 7.5,
      taxRate: 22,
      royaltyRate: 4,
      creditRate: 7.0,
      creditYears: 10,
      unitPrice: 185,
      annualProduction: 0.8,
      plantProcessingRate: 65,
      equipmentCost: 42,
      facilityCost: 95,
      infrastructureCost: 35,
      contingencyRate: 18,
      totalCapex: 202.84,
      fuelCost: 1.8,
      personnelCost: 8.5,
      maintenanceCost: 3.2,
      explosivesCost: 1.5,
      tireCost: 0.08,
      strippingCost: 0,
      otherOpex: 2.5,
      totalOpex: 17.58,
      forestCost: 1.0,
      landCost: 0.8,
      rehabilitationCost: 2.0,
      annualStrippingVolume: 0,
      strippingUnitCost: 0,
      contractorStrippingCost: 0,
      plantOperatingCost: 3.5,
      equipmentDepLife: 5,
      facilityDepLife: 12,
      byProductRevenue: 0,
      fuelPricePerLiter: 1.38,
      electricityUnitPrice: 0.092,
      totalReserves: 25,
      oreGrade: 6200,
      waterConsumptionDaily: 600,
      rehabilitationAreaHa: 45,
      rehabilitationCostPerHa: 18000,
      loanAmount: 85,
      loanInterestRate: 7.0,
      loanTermYears: 10,
      equityRatio: 50,
    },
    equipments: [
      { machineType: 'Joy 12CM30 Continuous Miner', equipmentCategory: 'underground', model: '12CM30', tonnageCapacity: '30 ton/dk', quantity: 2, spareQuantity: 1, unitCost: 950000, totalCost: 2850000, dailyWorkHours: 18, maintenancePeriodHours: 300, operatorCount: 2, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 75000, fuelConsumption: 0, productionImpact: 480, gallerySuitability: 'Uzun ayak' },
      { machineType: 'Sandvik LH517i LHD', equipmentCategory: 'underground', model: 'LH517i', tonnageCapacity: '17 ton', quantity: 3, spareQuantity: 1, unitCost: 620000, totalCost: 2480000, dailyWorkHours: 16, maintenancePeriodHours: 400, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 28, maintenanceCost: 38000, fuelConsumption: 28, productionImpact: 340, gallerySuitability: 'Ana galeri' },
      { machineType: 'Yer Altı Kamyon TH663i', equipmentCategory: 'truck', model: 'TH663i', tonnageCapacity: '63 ton', quantity: 4, spareQuantity: 1, unitCost: 480000, totalCost: 2400000, dailyWorkHours: 16, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 32, maintenanceCost: 28000, fuelConsumption: 32, productionImpact: 200, transportCapacity: 63 },
      { machineType: 'Atlas Copco Boomer E2', equipmentCategory: 'drill', model: 'Boomer E2', tonnageCapacity: '', quantity: 2, spareQuantity: 0, unitCost: 420000, totalCost: 840000, dailyWorkHours: 14, maintenancePeriodHours: 350, operatorCount: 1, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 32000, fuelConsumption: 0, productionImpact: 18, drillCapacity: 18, holeDiameter: 48, maxDrillDepth: 5.5 },
      { machineType: 'Havalandırma Fanı (Ana)', equipmentCategory: 'support', model: 'Howden VAF-800', tonnageCapacity: '250 m³/s', quantity: 2, spareQuantity: 1, unitCost: 280000, totalCost: 840000, dailyWorkHours: 24, maintenancePeriodHours: 1000, operatorCount: 0, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 18000, fuelConsumption: 0, productionImpact: 0 },
      { machineType: 'Shotcrete Makinesi', equipmentCategory: 'underground', model: 'Normet Spraymec 8100', tonnageCapacity: '25 m³/saat', quantity: 1, spareQuantity: 0, unitCost: 350000, totalCost: 350000, dailyWorkHours: 10, maintenancePeriodHours: 400, operatorCount: 2, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 22000, fuelConsumption: 0, productionImpact: 0, gallerySuitability: 'Tahkimat' },
    ],
    personnels: [
      { role: 'Maden Mühendisi', count: 3, monthlySalary: 5000 },
      { role: 'Jeoloji Mühendisi', count: 1, monthlySalary: 4800 },
      { role: 'Havalandırma Mühendisi', count: 1, monthlySalary: 4500 },
      { role: 'Vardiya Amiri', count: 6, monthlySalary: 3800 },
      { role: 'Continuous Miner Operatörü', count: 6, monthlySalary: 3500 },
      { role: 'LHD Operatörü', count: 6, monthlySalary: 3200 },
      { role: 'Yer Altı Kamyon Şoförü', count: 8, monthlySalary: 3000 },
      { role: 'Tahkimatçı', count: 8, monthlySalary: 2800 },
      { role: 'Elektrik Teknisyeni', count: 4, monthlySalary: 3000 },
      { role: 'Mekanik', count: 6, monthlySalary: 3000 },
      { role: 'Güvenlik/Kurtarma', count: 6, monthlySalary: 2500 },
      { role: 'İdari Personel', count: 4, monthlySalary: 2200 },
      { role: 'Sağlık Personeli', count: 3, monthlySalary: 3200 },
    ],
    byProducts: [],
    methodCosts: [
      { name: 'Tahkimat', category: 'underground', value: 8.5, unit: 'MUSD' },
      { name: 'Püskürtme Beton', category: 'underground', value: 3.2, unit: 'MUSD' },
      { name: 'Havalandırma', category: 'underground', value: 2.8, unit: 'MUSD' },
      { name: 'Drenaj', category: 'underground', value: 1.5, unit: 'MUSD' },
      { name: 'Galeri Açma', category: 'underground', value: 12.0, unit: 'MUSD' },
      { name: 'Kuyu Açma', category: 'underground', value: 6.5, unit: 'MUSD' },
      { name: 'Yer Altı Aydınlatma', category: 'underground', value: 0.8, unit: 'MUSD' },
    ],
  },

  // ========== 5. ELAZIĞ BAKIR MADENİ (YER ALTI) ==========
  {
    id: 'seed-copper-001',
    name: 'Elazığ Maden Bakır Projesi',
    mineType: 'copper',
    miningMethod: 'underground',
    location: 'Maden, Elazığ',
    currency: 'USD',
    exchangeRate: 1.0,
    fuelPricePerLiter: 1.36,
    electricityUnitPrice: 0.088,
    explosiveUnitPrice: 2.00,
    totalReserves: 45,
    maxAnnualCapacity: 2.0,
    oreGrade: 2.8,
    oreGradeUnit: '%',
    waterConsumptionDaily: 950,
    rehabilitationAreaHa: 65,
    rehabilitationCostPerHa: 20000,
    loanAmount: 150,
    loanInterestRate: 6.2,
    loanTermYears: 12,
    equityRatio: 45,
    depreciationMethod: 'linear',
    latitude: 38.3930,
    longitude: 39.6714,
    params: {
      projectLifeYears: 22,
      discountRate: 7.0,
      taxRate: 22,
      royaltyRate: 4,
      creditRate: 6.2,
      creditYears: 12,
      unitPrice: 8500,
      annualProduction: 0.028,
      plantProcessingRate: 88,
      equipmentCost: 55,
      facilityCost: 180,
      infrastructureCost: 40,
      contingencyRate: 15,
      totalCapex: 316.25,
      fuelCost: 3.5,
      personnelCost: 9.2,
      maintenanceCost: 4.5,
      explosivesCost: 2.8,
      tireCost: 0.12,
      strippingCost: 0,
      otherOpex: 3.0,
      totalOpex: 23.12,
      forestCost: 1.5,
      landCost: 1.2,
      rehabilitationCost: 3.5,
      annualStrippingVolume: 0,
      strippingUnitCost: 0,
      contractorStrippingCost: 0,
      plantOperatingCost: 12.0,
      equipmentDepLife: 6,
      facilityDepLife: 12,
      byProductRevenue: 2.5,
      fuelPricePerLiter: 1.36,
      electricityUnitPrice: 0.088,
      totalReserves: 45,
      oreGrade: 2.8,
      waterConsumptionDaily: 950,
      rehabilitationAreaHa: 65,
      rehabilitationCostPerHa: 20000,
      loanAmount: 150,
      loanInterestRate: 6.2,
      loanTermYears: 12,
      equityRatio: 45,
    },
    equipments: [
      { machineType: 'Sandvik DD422i Jumbo', equipmentCategory: 'drill', model: 'DD422i', tonnageCapacity: '', quantity: 3, spareQuantity: 1, unitCost: 580000, totalCost: 2320000, dailyWorkHours: 16, maintenancePeriodHours: 350, operatorCount: 1, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 42000, fuelConsumption: 0, productionImpact: 22, drillCapacity: 22, holeDiameter: 51, maxDrillDepth: 5.2 },
      { machineType: 'Sandvik LH621i LHD', equipmentCategory: 'underground', model: 'LH621i', tonnageCapacity: '21 ton', quantity: 4, spareQuantity: 1, unitCost: 720000, totalCost: 3600000, dailyWorkHours: 18, maintenancePeriodHours: 400, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 32, maintenanceCost: 45000, fuelConsumption: 32, productionImpact: 400, gallerySuitability: 'Ana ve tali galeri' },
      { machineType: 'Sandvik TH551i Kamyon', equipmentCategory: 'truck', model: 'TH551i', tonnageCapacity: '51 ton', quantity: 5, spareQuantity: 1, unitCost: 520000, totalCost: 3120000, dailyWorkHours: 18, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 28, maintenanceCost: 30000, fuelConsumption: 28, productionImpact: 180, transportCapacity: 51 },
      { machineType: 'Normet Spraymec 9100', equipmentCategory: 'underground', model: 'Spraymec 9100', tonnageCapacity: '30 m³/saat', quantity: 2, spareQuantity: 0, unitCost: 420000, totalCost: 840000, dailyWorkHours: 12, maintenancePeriodHours: 400, operatorCount: 2, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 28000, fuelConsumption: 0, productionImpact: 0, gallerySuitability: 'Tahkimat' },
      { machineType: 'Ana Havalandırma Fanı', equipmentCategory: 'support', model: 'Howden VAF-1200', tonnageCapacity: '400 m³/s', quantity: 2, spareQuantity: 1, unitCost: 380000, totalCost: 1140000, dailyWorkHours: 24, maintenancePeriodHours: 1000, operatorCount: 0, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 22000, fuelConsumption: 0, productionImpact: 0 },
      { machineType: 'Cevher Geçirme Sistemi', equipmentCategory: 'underground', model: 'Conveyor Belt', tonnageCapacity: '500 ton/saat', quantity: 1, spareQuantity: 0, unitCost: 850000, totalCost: 850000, dailyWorkHours: 20, maintenancePeriodHours: 800, operatorCount: 1, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 35000, fuelConsumption: 0, productionImpact: 500, gallerySuitability: 'Ana galeri' },
    ],
    personnels: [
      { role: 'Maden Mühendisi', count: 3, monthlySalary: 5200 },
      { role: 'Jeoloji Mühendisi', count: 2, monthlySalary: 4800 },
      { role: 'Metalurji Mühendisi', count: 2, monthlySalary: 5000 },
      { role: 'Havalandırma Mühendisi', count: 1, monthlySalary: 4800 },
      { role: 'Çevre Mühendisi', count: 1, monthlySalary: 4500 },
      { role: 'Vardiya Amiri', count: 6, monthlySalary: 3800 },
      { role: 'Jumbo Operatörü', count: 6, monthlySalary: 3500 },
      { role: 'LHD Operatörü', count: 8, monthlySalary: 3200 },
      { role: 'Kamyon Şoförü', count: 8, monthlySalary: 3000 },
      { role: 'Tahkimatçı', count: 10, monthlySalary: 2800 },
      { role: 'Mekanik/Bakım', count: 8, monthlySalary: 3000 },
      { role: 'Elektrikçi', count: 5, monthlySalary: 3000 },
      { role: 'Tesis Operatörü', count: 6, monthlySalary: 2800 },
      { role: 'Güvenlik/Kurtarma', count: 8, monthlySalary: 2500 },
      { role: 'İdari Personel', count: 5, monthlySalary: 2300 },
      { role: 'Sağlık', count: 3, monthlySalary: 3200 },
    ],
    byProducts: [
      { name: 'Altın', annualProduction: 120, productionUnit: 'kg', unitPrice: 62, priceUnit: 'USD/gram', totalRevenue: 7.44 },
      { name: 'Gümüş', annualProduction: 2200, productionUnit: 'kg', unitPrice: 28, priceUnit: 'USD/ons', totalRevenue: 1.98 },
      { name: 'Molib den', annualProduction: 85, productionUnit: 'ton', unitPrice: 44000, priceUnit: 'USD/ton', totalRevenue: 3.74 },
    ],
    methodCosts: [
      { name: 'Tahkimat', category: 'underground', value: 12.5, unit: 'MUSD' },
      { name: 'Püskürtme Beton', category: 'underground', value: 5.8, unit: 'MUSD' },
      { name: 'Havalandırma', category: 'underground', value: 4.2, unit: 'MUSD' },
      { name: 'Drenaj/Pompalama', category: 'underground', value: 2.8, unit: 'MUSD' },
      { name: 'Galeri Açma', category: 'underground', value: 18.0, unit: 'MUSD' },
      { name: 'Kuyu Açma', category: 'underground', value: 8.5, unit: 'MUSD' },
      { name: 'Yer Altı Aydınlatma', category: 'underground', value: 1.2, unit: 'MUSD' },
    ],
  },

  // ========== 6. ESKIŞEHİR KROM MADENİ ==========
  {
    id: 'seed-chrome-001',
    name: 'Eskişehir Krom Madeni',
    mineType: 'chrome',
    miningMethod: 'openPit',
    location: 'Mihalıççık, Eskişehir',
    currency: 'USD',
    exchangeRate: 1.0,
    fuelPricePerLiter: 1.30,
    electricityUnitPrice: 0.082,
    explosiveUnitPrice: 1.75,
    totalReserves: 8,
    maxAnnualCapacity: 0.5,
    oreGrade: 38,
    oreGradeUnit: '%',
    waterConsumptionDaily: 350,
    rehabilitationAreaHa: 55,
    rehabilitationCostPerHa: 15000,
    loanAmount: 25,
    loanInterestRate: 6.8,
    loanTermYears: 7,
    equityRatio: 70,
    depreciationMethod: 'linear',
    latitude: 39.8868,
    longitude: 31.0242,
    params: {
      projectLifeYears: 18,
      discountRate: 7.0,
      taxRate: 22,
      royaltyRate: 4,
      creditRate: 6.8,
      creditYears: 7,
      unitPrice: 320,
      annualProduction: 0.4,
      plantProcessingRate: 55,
      equipmentCost: 18,
      facilityCost: 32,
      infrastructureCost: 8,
      contingencyRate: 12,
      totalCapex: 64.96,
      fuelCost: 1.8,
      personnelCost: 3.5,
      maintenanceCost: 0.9,
      explosivesCost: 0.6,
      tireCost: 0.05,
      strippingCost: 1.2,
      otherOpex: 0.8,
      totalOpex: 8.85,
      forestCost: 0.5,
      landCost: 0.3,
      rehabilitationCost: 0.8,
      annualStrippingVolume: 3,
      strippingUnitCost: 2.2,
      contractorStrippingCost: 0,
      plantOperatingCost: 2.0,
      equipmentDepLife: 6,
      facilityDepLife: 12,
      byProductRevenue: 0,
      fuelPricePerLiter: 1.30,
      electricityUnitPrice: 0.082,
      totalReserves: 8,
      oreGrade: 38,
      waterConsumptionDaily: 350,
      rehabilitationAreaHa: 55,
      rehabilitationCostPerHa: 15000,
      loanAmount: 25,
      loanInterestRate: 6.8,
      loanTermYears: 7,
      equityRatio: 70,
    },
    equipments: [
      { machineType: 'Komatsu PC350 Ekskavatör', equipmentCategory: 'excavator', model: 'PC350', tonnageCapacity: '35 ton', quantity: 2, spareQuantity: 0, unitCost: 380000, totalCost: 760000, dailyWorkHours: 14, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 32, maintenanceCost: 22000, fuelConsumption: 32, productionImpact: 220, bucketVolume: 2.3 },
      { machineType: 'Volvo A40G Kamyon', equipmentCategory: 'truck', model: 'A40G', tonnageCapacity: '39 ton', quantity: 4, spareQuantity: 1, unitCost: 350000, totalCost: 1750000, dailyWorkHours: 14, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 28, maintenanceCost: 18000, fuelConsumption: 28, productionImpact: 150, transportCapacity: 39 },
      { machineType: 'Furukawa HCR-1500 Delici', equipmentCategory: 'drill', model: 'HCR-1500', tonnageCapacity: '', quantity: 1, spareQuantity: 0, unitCost: 280000, totalCost: 280000, dailyWorkHours: 10, maintenancePeriodHours: 400, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 22, maintenanceCost: 15000, fuelConsumption: 22, productionImpact: 18, drillCapacity: 18, holeDiameter: 115, maxDrillDepth: 30 },
      { machineType: 'CAT 966M Yükleyici', equipmentCategory: 'loader', model: '966M', tonnageCapacity: '22 ton', quantity: 1, spareQuantity: 0, unitCost: 310000, totalCost: 310000, dailyWorkHours: 12, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 20, maintenanceCost: 14000, fuelConsumption: 20, productionImpact: 180, loadingCapacity: 180, bucketVolume: 4.2 },
      { machineType: 'CAT D8T Dozer', equipmentCategory: 'dozer', model: 'D8T', tonnageCapacity: '38 ton', quantity: 1, spareQuantity: 0, unitCost: 380000, totalCost: 380000, dailyWorkHours: 10, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 30, maintenanceCost: 20000, fuelConsumption: 30, productionImpact: 0 },
    ],
    personnels: [
      { role: 'Maden Mühendisi', count: 2, monthlySalary: 4500 },
      { role: 'Jeoloji Mühendisi', count: 1, monthlySalary: 4200 },
      { role: 'Vardiya Amiri', count: 3, monthlySalary: 3200 },
      { role: 'Operatör', count: 6, monthlySalary: 2800 },
      { role: 'Şoför', count: 6, monthlySalary: 2400 },
      { role: 'Bakım Teknisyeni', count: 3, monthlySalary: 2700 },
      { role: 'İşçi', count: 10, monthlySalary: 2000 },
      { role: 'Güvenlik', count: 4, monthlySalary: 1800 },
      { role: 'İdari Personel', count: 3, monthlySalary: 2200 },
    ],
    byProducts: [],
    methodCosts: [
      { name: 'Pasa Döküm', category: 'openPit', value: 1.5, unit: 'MUSD' },
      { name: 'Dekapaj', category: 'openPit', value: 6.6, unit: 'MUSD' },
      { name: 'Patlatma Giderleri', category: 'openPit', value: 0.6, unit: 'MUSD' },
      { name: 'Yol Yapımı', category: 'openPit', value: 0.5, unit: 'MUSD' },
    ],
  },

  // ========== 7. AFYON MERMER OCAGI ==========
  {
    id: 'seed-marble-001',
    name: 'Afyon İscehisar Mermer Ocağı',
    mineType: 'marble',
    miningMethod: 'openPit',
    location: 'İscehisar, Afyonkarahisar',
    currency: 'EUR',
    exchangeRate: 0.92,
    fuelPricePerLiter: 1.45,
    electricityUnitPrice: 0.095,
    explosiveUnitPrice: 0,
    totalReserves: 12,
    maxAnnualCapacity: 0.3,
    oreGrade: 0,
    oreGradeUnit: '%',
    waterConsumptionDaily: 280,
    rehabilitationAreaHa: 25,
    rehabilitationCostPerHa: 8000,
    loanAmount: 10,
    loanInterestRate: 5.5,
    loanTermYears: 6,
    equityRatio: 80,
    depreciationMethod: 'linear',
    latitude: 38.7415,
    longitude: 30.5890,
    params: {
      projectLifeYears: 40,
      discountRate: 5.5,
      taxRate: 22,
      royaltyRate: 4,
      creditRate: 5.5,
      creditYears: 6,
      unitPrice: 180,
      annualProduction: 0.25,
      plantProcessingRate: 30,
      equipmentCost: 12,
      facilityCost: 8,
      infrastructureCost: 3,
      contingencyRate: 10,
      totalCapex: 25.3,
      fuelCost: 0.8,
      personnelCost: 1.8,
      maintenanceCost: 0.5,
      explosivesCost: 0,
      tireCost: 0.02,
      strippingCost: 0.3,
      otherOpex: 0.5,
      totalOpex: 3.92,
      forestCost: 0.2,
      landCost: 0.15,
      rehabilitationCost: 0.2,
      annualStrippingVolume: 0.5,
      strippingUnitCost: 1.5,
      contractorStrippingCost: 0,
      plantOperatingCost: 0.8,
      equipmentDepLife: 8,
      facilityDepLife: 20,
      byProductRevenue: 0.5,
      fuelPricePerLiter: 1.45,
      electricityUnitPrice: 0.095,
      totalReserves: 12,
      oreGrade: 0,
      waterConsumptionDaily: 280,
      rehabilitationAreaHa: 25,
      rehabilitationCostPerHa: 8000,
      loanAmount: 10,
      loanInterestRate: 5.5,
      loanTermYears: 6,
      equityRatio: 80,
    },
    equipments: [
      { machineType: 'Fantini GU70 Zincirli Kesici', equipmentCategory: 'general', model: 'GU70', tonnageCapacity: '', quantity: 2, spareQuantity: 1, unitCost: 280000, totalCost: 840000, dailyWorkHours: 10, maintenancePeriodHours: 300, operatorCount: 1, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 35000, fuelConsumption: 0, productionImpact: 15 },
      { machineType: 'Elmas Telli Kesme Makinesi', equipmentCategory: 'general', model: 'Benetti BT-48', tonnageCapacity: '', quantity: 3, spareQuantity: 1, unitCost: 85000, totalCost: 340000, dailyWorkHours: 10, maintenancePeriodHours: 200, operatorCount: 1, powerType: 'electric', hourlyFuelConsumption: 0, maintenanceCost: 18000, fuelConsumption: 0, productionImpact: 12 },
      { machineType: 'Komatsu PC210 Ekskavatör', equipmentCategory: 'excavator', model: 'PC210', tonnageCapacity: '22 ton', quantity: 1, spareQuantity: 0, unitCost: 180000, totalCost: 180000, dailyWorkHours: 10, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 18, maintenanceCost: 12000, fuelConsumption: 18, productionImpact: 120, bucketVolume: 1.2 },
      { machineType: 'Volvo FH16 Kamyon', equipmentCategory: 'truck', model: 'FH16', tonnageCapacity: '30 ton', quantity: 3, spareQuantity: 0, unitCost: 120000, totalCost: 360000, dailyWorkHours: 10, maintenancePeriodHours: 600, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 15, maintenanceCost: 8000, fuelConsumption: 15, productionImpact: 100, transportCapacity: 30 },
      { machineType: 'Vinç (50 ton)', equipmentCategory: 'support', model: 'Liebherr LTM 1050', tonnageCapacity: '50 ton', quantity: 1, spareQuantity: 0, unitCost: 250000, totalCost: 250000, dailyWorkHours: 8, maintenancePeriodHours: 500, operatorCount: 1, powerType: 'diesel', hourlyFuelConsumption: 20, maintenanceCost: 15000, fuelConsumption: 20, productionImpact: 0 },
    ],
    personnels: [
      { role: 'Maden Mühendisi', count: 1, monthlySalary: 4200 },
      { role: 'Usta Kesimci', count: 4, monthlySalary: 3000 },
      { role: 'Operatör', count: 4, monthlySalary: 2500 },
      { role: 'Şoför', count: 4, monthlySalary: 2200 },
      { role: 'İşçi', count: 8, monthlySalary: 1800 },
      { role: 'Bakım Teknisyeni', count: 2, monthlySalary: 2600 },
      { role: 'İdari Personel', count: 2, monthlySalary: 2000 },
      { role: 'Güvenlik', count: 2, monthlySalary: 1700 },
    ],
    byProducts: [
      { name: 'Mermer Kırığı (Agrega)', annualProduction: 50000, productionUnit: 'ton', unitPrice: 10, priceUnit: 'USD/ton', totalRevenue: 0.5 },
    ],
    methodCosts: [
      { name: 'Elmas Tel Giderleri', category: 'openPit', value: 1.8, unit: 'MUSD' },
      { name: 'Zincir Kesici Bakım', category: 'openPit', value: 0.7, unit: 'MUSD' },
      { name: 'Blok Kesim Alanı Hazırlama', category: 'openPit', value: 0.4, unit: 'MUSD' },
      { name: 'Yol Yapımı', category: 'openPit', value: 0.3, unit: 'MUSD' },
    ],
  },

  // ========== 8. ÖDEV - MAD436 LİNYİT AÇIK OCAK ==========
  {
    id: 'seed-odev-001',
    name: 'Ödev',
    mineType: 'lignite',
    miningMethod: 'openPit',
    location: '',
    currency: 'USD',
    exchangeRate: 44.0,
    fuelPricePerLiter: 1.64,
    electricityUnitPrice: 0,
    explosiveUnitPrice: 0.45,
    totalReserves: 61.05,
    maxAnnualCapacity: 2.16,
    oreGrade: 0,
    oreGradeUnit: '',
    waterConsumptionDaily: 0,
    rehabilitationAreaHa: 500,
    rehabilitationCostPerHa: 1500,
    loanAmount: 286.5,
    loanInterestRate: 4,
    loanTermYears: 10,
    equityRatio: 41,
    depreciationMethod: 'linear',
    latitude: 0,
    longitude: 0,
    params: {
      projectLifeYears: 30,
      discountRate: 5.82,
      taxRate: 22,
      royaltyRate: 4,
      creditRate: 4,
      creditYears: 10,
      unitPrice: 75,
      annualProduction: 2.035,
      plantProcessingRate: 35,
      equipmentCost: 53.385,
      facilityCost: 318.0,
      infrastructureCost: 6.0,
      contingencyRate: 8.45,
      totalCapex: 409.285,
      fuelCost: 2.605,
      personnelCost: 4.280,
      maintenanceCost: 0.494,
      explosivesCost: 7.348,
      tireCost: 0.021,
      strippingCost: 0,
      otherOpex: 1.475,
      totalOpex: 16.223,
      forestCost: 5.022,
      landCost: 1.0,
      rehabilitationCost: 0.75,
      annualStrippingVolume: 13.92,
      strippingUnitCost: 1.05,
      contractorStrippingCost: 2.87,
      plantOperatingCost: 8.6,
      equipmentDepLife: 6,
      facilityDepLife: 15,
      byProductRevenue: 0,
      fuelPricePerLiter: 1.64,
      electricityUnitPrice: 0,
      explosiveUnitPrice: 0.45,
      totalReserves: 61.05,
      oreGrade: 0,
      waterConsumptionDaily: 0,
      rehabilitationAreaHa: 500,
      rehabilitationCostPerHa: 1500,
      loanAmount: 286.5,
      loanInterestRate: 4,
      loanTermYears: 10,
      equityRatio: 41,
    },
    equipments: [
      { machineType: 'Ekskavatör - Dekapaj', equipmentCategory: 'excavators', model: '', tonnageCapacity: '10.6 yd³', quantity: 5, spareQuantity: 1, unitCost: 1500000, totalCost: 9000000, fuelConsumption: 0, maintenanceCost: 0, dailyWorkHours: 0, hourlyFuelConsumption: 0, operatorCount: 15, powerType: 'diesel' },
      { machineType: 'Kamyon - Dekapaj', equipmentCategory: 'trucks', model: '', tonnageCapacity: '42.23 m³', quantity: 25, spareQuantity: 2, unitCost: 1100000, totalCost: 29700000, fuelConsumption: 0, maintenanceCost: 0, dailyWorkHours: 0, hourlyFuelConsumption: 0, operatorCount: 75, powerType: 'diesel' },
      { machineType: 'Ekskavatör - Linyit', equipmentCategory: 'excavators', model: '', tonnageCapacity: '8.5 yd³', quantity: 1, spareQuantity: 1, unitCost: 700000, totalCost: 1400000, fuelConsumption: 225000, maintenanceCost: 45000, dailyWorkHours: 0, hourlyFuelConsumption: 50, operatorCount: 0, powerType: 'diesel' },
      { machineType: 'Kamyon - Linyit', equipmentCategory: 'trucks', model: '', tonnageCapacity: '25.2 m³', quantity: 5, spareQuantity: 1, unitCost: 650000, totalCost: 3900000, fuelConsumption: 144000, maintenanceCost: 165000, dailyWorkHours: 0, hourlyFuelConsumption: 32, operatorCount: 0, powerType: 'diesel' },
      { machineType: 'Delici Makine - Linyit', equipmentCategory: 'drills', model: '', tonnageCapacity: '4 inç', quantity: 1, spareQuantity: 0, unitCost: 350000, totalCost: 350000, fuelConsumption: 90000, maintenanceCost: 21000, dailyWorkHours: 0, hourlyFuelConsumption: 30, operatorCount: 3, powerType: 'diesel' },
      { machineType: 'Delici Makine - Dekapaj', equipmentCategory: 'drills', model: '', tonnageCapacity: '7.5 inç', quantity: 2, spareQuantity: 1, unitCost: 1500000, totalCost: 4500000, fuelConsumption: 0, maintenanceCost: 0, dailyWorkHours: 0, hourlyFuelConsumption: 0, operatorCount: 0, powerType: 'diesel' },
      { machineType: 'Yükleyici', equipmentCategory: 'loaders', model: '', tonnageCapacity: '5 m³', quantity: 2, spareQuantity: 0, unitCost: 700000, totalCost: 1400000, fuelConsumption: 36000, maintenanceCost: 39000, dailyWorkHours: 0, hourlyFuelConsumption: 12, operatorCount: 15, powerType: 'diesel' },
      { machineType: 'Dozer', equipmentCategory: 'excavators', model: '', tonnageCapacity: '40 Ton', quantity: 2, spareQuantity: 0, unitCost: 850000, totalCost: 1700000, fuelConsumption: 120000, maintenanceCost: 21000, dailyWorkHours: 0, hourlyFuelConsumption: 40, operatorCount: 3, powerType: 'diesel' },
      { machineType: 'Greyder', equipmentCategory: 'excavators', model: '', tonnageCapacity: '196 HP', quantity: 2, spareQuantity: 0, unitCost: 400000, totalCost: 800000, fuelConsumption: 36000, maintenanceCost: 90000, dailyWorkHours: 0, hourlyFuelConsumption: 12, operatorCount: 6, powerType: 'diesel' },
      { machineType: 'Tamir Aracı', equipmentCategory: 'trucks', model: '', tonnageCapacity: '', quantity: 1, spareQuantity: 0, unitCost: 50000, totalCost: 50000, fuelConsumption: 7200, maintenanceCost: 42000, dailyWorkHours: 0, hourlyFuelConsumption: 12, operatorCount: 6, powerType: 'diesel' },
      { machineType: 'Arazöz', equipmentCategory: 'trucks', model: '', tonnageCapacity: '10 Ton', quantity: 3, spareQuantity: 0, unitCost: 75000, totalCost: 225000, fuelConsumption: 7200, maintenanceCost: 25500, dailyWorkHours: 0, hourlyFuelConsumption: 12, operatorCount: 4, powerType: 'diesel' },
      { machineType: 'Malzeme Kamyonu', equipmentCategory: 'trucks', model: '', tonnageCapacity: '10 Ton', quantity: 1, spareQuantity: 0, unitCost: 65000, totalCost: 65000, fuelConsumption: 6000, maintenanceCost: 36000, dailyWorkHours: 0, hourlyFuelConsumption: 10, operatorCount: 6, powerType: 'diesel' },
      { machineType: 'Ambulans', equipmentCategory: 'trucks', model: '', tonnageCapacity: '', quantity: 1, spareQuantity: 0, unitCost: 65000, totalCost: 65000, fuelConsumption: 15000, maintenanceCost: 1500, dailyWorkHours: 0, hourlyFuelConsumption: 10, operatorCount: 3, powerType: 'diesel' },
      { machineType: 'Jeep', equipmentCategory: 'trucks', model: '', tonnageCapacity: '', quantity: 3, spareQuantity: 0, unitCost: 55000, totalCost: 165000, fuelConsumption: 6600, maintenanceCost: 2250, dailyWorkHours: 0, hourlyFuelConsumption: 11, operatorCount: 9, powerType: 'diesel' },
      { machineType: 'Akaryakıt Kamyonu', equipmentCategory: 'trucks', model: '', tonnageCapacity: '10 Ton', quantity: 1, spareQuantity: 0, unitCost: 65000, totalCost: 65000, fuelConsumption: 36000, maintenanceCost: 5850, dailyWorkHours: 0, hourlyFuelConsumption: 12, operatorCount: 3, powerType: 'diesel' },
    ],
    personnels: [
      { role: 'Ekskavatör Operatörü - Dekapaj', count: 15, monthlySalary: 1500 },
      { role: 'Kamyon Operatörü - Dekapaj', count: 75, monthlySalary: 1500 },
      { role: 'Delici Makine Operatörü', count: 3, monthlySalary: 2250 },
      { role: 'Yükleyici Operatörü', count: 15, monthlySalary: 1500 },
      { role: 'Dozer Operatörü', count: 3, monthlySalary: 1500 },
      { role: 'Greyder Operatörü', count: 6, monthlySalary: 1500 },
      { role: 'Tamir Aracı Sürücüsü', count: 6, monthlySalary: 1200 },
      { role: 'Arazöz Sürücüsü', count: 4, monthlySalary: 1000 },
      { role: 'Malzeme Kamyonu Sürücüsü', count: 6, monthlySalary: 1000 },
      { role: 'Ambulans Sürücüsü', count: 3, monthlySalary: 1000 },
      { role: 'Jeep Sürücüsü', count: 9, monthlySalary: 1250 },
      { role: 'Akaryakıt Kamyonu Sürücüsü', count: 3, monthlySalary: 1000 },
      { role: 'Bakım Onarım Personeli', count: 18, monthlySalary: 1250 },
      { role: 'Diğer İşçi', count: 8, monthlySalary: 800 },
      { role: 'Güvenlikçi', count: 12, monthlySalary: 800 },
      { role: 'Mühendis', count: 16, monthlySalary: 3500 },
      { role: 'İdari Personel', count: 10, monthlySalary: 2500 },
      { role: 'Müdür-İdareci', count: 5, monthlySalary: 5000 },
    ],
    byProducts: [],
    methodCosts: [
      { name: 'Dekapaj İşletme (Yıllık Ort.)', category: 'openPit', value: 14.616, unit: 'MUSD' },
      { name: 'Dekapaj Yüklenici (Yıllık Ort.)', category: 'openPit', value: 2.87, unit: 'MUSD' },
      { name: 'Linyit Kazı ve Nakliye (Yıllık)', category: 'openPit', value: 16.661, unit: 'MUSD' },
      { name: 'Tesis İşletme Gideri (Yıllık Ort.)', category: 'other', value: 8.6, unit: 'MUSD' },
      { name: 'Orman İzin Gideri', category: 'other', value: 5.022, unit: 'MUSD' },
      { name: 'Kamulaştırma Gideri', category: 'other', value: 1.0, unit: 'MUSD' },
      { name: 'Rehabilitasyon Gideri', category: 'other', value: 0.75, unit: 'MUSD' },
      { name: 'Etüt Proje Giderleri', category: 'other', value: 1.0, unit: 'MUSD' },
      { name: 'Arazi Düzenleme Giderleri', category: 'other', value: 1.0, unit: 'MUSD' },
      { name: 'Bina ve Yol Giderleri', category: 'other', value: 3.0, unit: 'MUSD' },
      { name: 'Akaryakıt Depo-Drenaj Sistemleri', category: 'other', value: 0.5, unit: 'MUSD' },
      { name: 'İletişim Sistemleri', category: 'other', value: 0.2, unit: 'MUSD' },
      { name: 'Kuruluş Gideri', category: 'other', value: 0.2, unit: 'MUSD' },
      { name: 'Reklamasyon Giderleri', category: 'other', value: 0.1, unit: 'MUSD' },
      { name: 'Linyit Tesisi Kurulumu', category: 'other', value: 318.0, unit: 'MUSD' },
      { name: 'Öngörülemeyen Giderler', category: 'other', value: 31.9, unit: 'MUSD' },
      { name: 'Patlayıcı Madde (Yıllık)', category: 'openPit', value: 7.348, unit: 'MUSD' },
      { name: 'Yakıt Giderleri (Yıllık)', category: 'other', value: 2.605, unit: 'MUSD' },
      { name: 'Personel Giderleri (Yıllık)', category: 'other', value: 4.280, unit: 'MUSD' },
      { name: 'Yedek Parça Tamir Bakım (Yıllık)', category: 'other', value: 0.494, unit: 'MUSD' },
      { name: 'Lastik Giderleri (Yıllık)', category: 'other', value: 0.021, unit: 'MUSD' },
    ],
  },
];



async function seedEquipmentCatalog(): Promise<void> {
  const { upserted } = await seedEquipmentCatalogIdempotent(prisma);
  console.log(`\u2705 Equipment catalog seeded (idempotent upsert): ${upserted} items`);
}

/**
 * Idempotent demo-project seed: create if missing, update scalars if present.
 * Never deletes projects or child rows — preserves user edits and unrelated data.
 */
async function seedDemoProject(proj: SeedProject): Promise<void> {
  const analysis = performFullAnalysis(proj.params);

  const cashFlowData = (analysis?.cashFlows ?? []).map((cf: any) => ({
    year: cf?.year ?? 0,
    revenue: cf?.revenue ?? 0,
    opex: cf?.opex ?? 0,
    depreciation: cf?.depreciation ?? 0,
    taxPayment: cf?.taxPayment ?? 0,
    royalty: cf?.royalty ?? 0,
    creditPayment: cf?.creditPayment ?? 0,
    creditInterest: cf?.creditInterest ?? 0,
    netCashFlow: cf?.netCashFlow ?? 0,
    cumulativeCashFlow: cf?.cumulativeCashFlow ?? 0,
    discountedCashFlow: cf?.discountedCashFlow ?? 0,
  }));
  const projNpv = analysis?.npv ?? 0;
  const projIrr = analysis?.irr ?? 0;
  const projPayback = analysis?.paybackPeriod ?? 0;
  const projBreakeven = analysis?.breakevenPrice ?? 0;
  const projTotalRevenue = analysis?.totalRevenue ?? 0;
  const projTotalCost = analysis?.totalCost ?? 0;

  const scalarData = {
    name: proj.name,
    mineType: proj.mineType,
    miningMethod: proj.miningMethod,
    location: proj.location,
    currency: proj.currency,
    exchangeRate: proj.exchangeRate,
    fuelPricePerLiter: proj.fuelPricePerLiter,
    electricityUnitPrice: proj.electricityUnitPrice,
    explosiveUnitPrice: proj.explosiveUnitPrice,
    totalReserves: proj.totalReserves,
    maxAnnualCapacity: proj.maxAnnualCapacity,
    oreGrade: proj.oreGrade,
    oreGradeUnit: proj.oreGradeUnit,
    waterConsumptionDaily: proj.waterConsumptionDaily,
    rehabilitationAreaHa: proj.rehabilitationAreaHa,
    rehabilitationCostPerHa: proj.rehabilitationCostPerHa,
    loanAmount: proj.loanAmount,
    loanInterestRate: proj.loanInterestRate,
    loanTermYears: proj.loanTermYears,
    equityRatio: proj.equityRatio,
    depreciationMethod: proj.depreciationMethod,
    equipmentRenewalEnabled: proj.equipmentRenewalEnabled ?? true,
    equipmentRenewalCycleYears: proj.equipmentRenewalCycleYears ?? 10,
    latitude: proj.latitude,
    longitude: proj.longitude,
    projectLifeYears: proj.params.projectLifeYears,
    discountRate: proj.params.discountRate,
    taxRate: proj.params.taxRate,
    royaltyRate: proj.params.royaltyRate,
    creditRate: proj.params.creditRate,
    creditYears: proj.params.creditYears,
    unitPrice: proj.params.unitPrice,
    annualProduction: proj.params.annualProduction,
    productionUnit: 'Mt',
    plantProcessingRate: proj.params.plantProcessingRate,
    equipmentCost: proj.params.equipmentCost,
    facilityCost: proj.params.facilityCost,
    infrastructureCost: proj.params.infrastructureCost,
    contingencyRate: proj.params.contingencyRate,
    totalCapex: proj.params.totalCapex,
    fuelCost: proj.params.fuelCost,
    personnelCost: proj.params.personnelCost,
    maintenanceCost: proj.params.maintenanceCost,
    explosivesCost: proj.params.explosivesCost,
    tireCost: proj.params.tireCost,
    strippingCost: proj.params.strippingCost,
    otherOpex: proj.params.otherOpex,
    totalOpex: proj.params.totalOpex,
    forestCost: proj.params.forestCost,
    landCost: proj.params.landCost,
    rehabilitationCost: proj.params.rehabilitationCost,
    annualStrippingVolume: proj.params.annualStrippingVolume,
    strippingUnitCost: proj.params.strippingUnitCost,
    contractorStrippingCost: proj.params.contractorStrippingCost,
    plantOperatingCost: proj.params.plantOperatingCost,
    equipmentDepLife: proj.params.equipmentDepLife,
    facilityDepLife: proj.params.facilityDepLife,
    npv: projNpv,
    irr: projIrr,
    paybackPeriod: projPayback,
    breakevenPrice: projBreakeven,
    totalRevenue: projTotalRevenue,
    totalCost: projTotalCost,
    byProductRevenue: proj.params.byProductRevenue ?? 0,
    customCashFlows: false,
  };

  const existing = await prisma.miningProject.findUnique({
    where: { id: proj.id },
    select: { id: true },
  });

  if (existing) {
    // Update scalars only — do not wipe child collections or user edits.
    await prisma.miningProject.update({
      where: { id: proj.id },
      data: scalarData,
    });
    console.log(
      `\u2705 ${proj.name} g\u00fcncellendi (NPV: ${projNpv.toFixed(2)} MUSD, IRR: ${projIrr.toFixed(2)}%)`
    );
    return;
  }

  await prisma.miningProject.create({
    data: {
      id: proj.id,
      ...scalarData,
      cashFlows: {
        create: cashFlowData.map((cf: any) => ({
          year: cf.year,
          revenue: cf.revenue,
          opex: cf.opex,
          depreciation: cf.depreciation,
          taxPayment: cf.taxPayment,
          royalty: cf.royalty,
          creditPayment: cf.creditPayment,
          creditInterest: cf.creditInterest,
          netCashFlow: cf.netCashFlow,
          cumulativeCashFlow: cf.cumulativeCashFlow,
          discountedCashFlow: cf.discountedCashFlow,
        })),
      },
      equipments: {
        create: proj.equipments.map((eq: any) => ({
          machineType: eq.machineType,
          equipmentCategory: eq.equipmentCategory,
          model: eq.model ?? '',
          tonnageCapacity: eq.tonnageCapacity ?? '',
          quantity: eq.quantity ?? 1,
          spareQuantity: eq.spareQuantity ?? 0,
          unitCost: eq.unitCost ?? 0,
          totalCost: eq.totalCost ?? 0,
          fuelConsumption: eq.fuelConsumption ?? 0,
          maintenanceCost: eq.maintenanceCost ?? 0,
          dailyWorkHours: eq.dailyWorkHours ?? 8,
          maintenancePeriodHours: eq.maintenancePeriodHours ?? 500,
          operatorCount: eq.operatorCount ?? 1,
          powerType: eq.powerType ?? 'diesel',
          hourlyFuelConsumption: eq.hourlyFuelConsumption ?? 0,
          productionImpact: eq.productionImpact ?? 0,
          drillCapacity: eq.drillCapacity ?? 0,
          holeDiameter: eq.holeDiameter ?? 0,
          maxDrillDepth: eq.maxDrillDepth ?? 0,
          bucketVolume: eq.bucketVolume ?? 0,
          transportCapacity: eq.transportCapacity ?? 0,
          loadingCapacity: eq.loadingCapacity ?? 0,
          crushingCapacity: eq.crushingCapacity ?? 0,
          gallerySuitability: eq.gallerySuitability ?? '',
        })),
      },
      personnels: {
        create: proj.personnels.map((p: any) => ({
          role: p.role,
          count: p.count ?? 1,
          monthlySalary: p.monthlySalary ?? 0,
          annualCost: (p.count ?? 1) * (p.monthlySalary ?? 0) * 12,
        })),
      },
      byProducts: {
        create: proj.byProducts.map((bp: any) => ({
          name: bp.name,
          annualProduction: bp.annualProduction ?? 0,
          productionUnit: bp.productionUnit ?? 'ton',
          unitPrice: bp.unitPrice ?? 0,
          priceUnit: bp.priceUnit ?? 'USD/ton',
          totalRevenue: bp.totalRevenue ?? 0,
        })),
      },
      methodCosts: {
        create: proj.methodCosts.map((mc: any) => ({
          name: mc.name,
          category: mc.category ?? 'other',
          value: mc.value ?? 0,
          unit: mc.unit ?? 'MUSD',
        })),
      },
    },
  });

  console.log(
    `\u2705 ${proj.name} eklendi (NPV: ${projNpv.toFixed(2)} MUSD, IRR: ${projIrr.toFixed(2)}%)`
  );
}

async function main() {
  await seedEquipmentCatalog();
  const demos = await ensureAllDemoProjects(prisma);
  for (const demo of demos) {
    console.log(
      `\u2705 Demo ${demo.id} ${demo.created ? 'created' : 'updated'}`
    );
  }

  for (const proj of PROJECTS) {
    await seedDemoProject(proj);
  }

  console.log(
    `\n\u2705 Seed tamamland\u0131: ${demos.length} demo + ${PROJECTS.length} örnek proje (idempotent)`
  );
}

main()
  .catch((e: any) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });