/**
 * Commodity Master Data seed rows — indicative engineering defaults for
 * feasibility studies (order-of-magnitude, mid-cycle 2024–2026).
 * Not trading quotes. Projects snapshot these into MiningProject scalars.
 */

export interface CommodityCatalogSeedRow {
  code: string;
  name: string;
  nameTr: string;
  symbol: string;
  unit: string;
  typicalSellingUnit: string;
  typicalPriceUsd: number;
  priceCurrency: string;
  gradeMin: number;
  gradeMax: number;
  gradeUnit: string;
  recoveryMinPct: number;
  recoveryMaxPct: number;
  densityTPerM3: number | null;
  typicalProcessingMethod: string;
  typicalMiningMethods: string;
  typicalMineLifeYears: number;
  refiningCostUsdPerT: number | null;
  smeltingCostUsdPerT: number | null;
  payabilityPct: number | null;
  transportationCostUsdPerT: number | null;
  royaltyDefaultPct: number;
  environmentalRisk: string;
  colorHex: string;
  iconKey: string;
  notes: string;
  searchAliases: string;
  isActive: boolean;
  sortOrder: number;
}

function row(
  partial: Omit<CommodityCatalogSeedRow, 'priceCurrency' | 'isActive'> & {
    priceCurrency?: string;
    isActive?: boolean;
  }
): CommodityCatalogSeedRow {
  return {
    priceCurrency: 'USD',
    isActive: true,
    ...partial,
  };
}

export function buildCommodityCatalogSeedRows(): CommodityCatalogSeedRow[] {
  return [
    row({
      code: 'copper',
      name: 'Copper',
      nameTr: 'Bakır',
      symbol: 'Cu',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 9000,
      gradeMin: 0.4,
      gradeMax: 1.5,
      gradeUnit: '%',
      recoveryMinPct: 85,
      recoveryMaxPct: 92,
      densityTPerM3: 2.7,
      typicalProcessingMethod: 'Crush–grind–flotation → concentrate → smelt/refine',
      typicalMiningMethods: 'openPit,underground',
      typicalMineLifeYears: 20,
      refiningCostUsdPerT: 100,
      smeltingCostUsdPerT: 120,
      payabilityPct: 96,
      transportationCostUsdPerT: 40,
      royaltyDefaultPct: 3,
      environmentalRisk: 'medium',
      colorHex: '#b87333',
      iconKey: 'copper',
      notes: 'Concentrate Tc/Rc and payability vary by offtake; price is cathode-equivalent indicator.',
      searchAliases: 'Cu,bakır,copper concentrate',
      sortOrder: 10,
    }),
    row({
      code: 'gold',
      name: 'Gold',
      nameTr: 'Altın',
      symbol: 'Au',
      unit: 'oz',
      typicalSellingUnit: 'USD/oz',
      typicalPriceUsd: 2300,
      gradeMin: 0.8,
      gradeMax: 5,
      gradeUnit: 'g/t',
      recoveryMinPct: 80,
      recoveryMaxPct: 95,
      densityTPerM3: 2.7,
      typicalProcessingMethod: 'CIL/CIP or gravity + leach; doré bar',
      typicalMiningMethods: 'openPit,underground',
      typicalMineLifeYears: 12,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: 99,
      transportationCostUsdPerT: null,
      royaltyDefaultPct: 2,
      environmentalRisk: 'medium',
      colorHex: '#d4af37',
      iconKey: 'gem',
      notes: 'Unit price in USD/oz troy. Grade in g/t. Refining typically charged per oz, not per tonne ore.',
      searchAliases: 'Au,altın,doré',
      sortOrder: 20,
    }),
    row({
      code: 'silver',
      name: 'Silver',
      nameTr: 'Gümüş',
      symbol: 'Ag',
      unit: 'oz',
      typicalSellingUnit: 'USD/oz',
      typicalPriceUsd: 28,
      gradeMin: 50,
      gradeMax: 300,
      gradeUnit: 'g/t',
      recoveryMinPct: 75,
      recoveryMaxPct: 90,
      densityTPerM3: 2.8,
      typicalProcessingMethod: 'Flotation and/or leach; often by-product of base metals',
      typicalMiningMethods: 'openPit,underground',
      typicalMineLifeYears: 12,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: 95,
      transportationCostUsdPerT: null,
      royaltyDefaultPct: 2,
      environmentalRisk: 'medium',
      colorHex: '#c0c0c0',
      iconKey: 'gem',
      notes: 'Frequently modelled as by-product revenue; standalone high-grade Ag veins are less common.',
      searchAliases: 'Ag,gümüş',
      sortOrder: 30,
    }),
    row({
      code: 'nickel',
      name: 'Nickel',
      nameTr: 'Nikel',
      symbol: 'Ni',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 16500,
      gradeMin: 0.6,
      gradeMax: 2.5,
      gradeUnit: '%',
      recoveryMinPct: 70,
      recoveryMaxPct: 88,
      densityTPerM3: 2.9,
      typicalProcessingMethod: 'Sulphide flotation → matte; laterite: HPAL / RKEF',
      typicalMiningMethods: 'openPit,underground',
      typicalMineLifeYears: 18,
      refiningCostUsdPerT: 1500,
      smeltingCostUsdPerT: 800,
      payabilityPct: 90,
      transportationCostUsdPerT: 50,
      royaltyDefaultPct: 3,
      environmentalRisk: 'high',
      colorHex: '#7a9e7e',
      iconKey: 'nickel',
      notes: 'Sulphide vs laterite cost structures differ sharply; defaults lean sulphide open-pit/UG.',
      searchAliases: 'Ni,nikel,class 1 nickel',
      sortOrder: 40,
    }),
    row({
      code: 'lithium',
      name: 'Lithium',
      nameTr: 'Lityum',
      symbol: 'Li',
      unit: 't',
      typicalSellingUnit: 'USD/t LCE',
      typicalPriceUsd: 12000,
      gradeMin: 0.8,
      gradeMax: 1.6,
      gradeUnit: '% Li2O',
      recoveryMinPct: 60,
      recoveryMaxPct: 80,
      densityTPerM3: 2.6,
      typicalProcessingMethod: 'Hard-rock: concentrate → spodumene → convert to LCE/LiOH; brine: evaporation ponds',
      typicalMiningMethods: 'openPit',
      typicalMineLifeYears: 20,
      refiningCostUsdPerT: 2500,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 80,
      royaltyDefaultPct: 3,
      environmentalRisk: 'medium',
      colorHex: '#5b8def',
      iconKey: 'battery',
      notes: 'Price expressed as lithium carbonate equivalent (LCE). Spodumene concentrate SC6 trades separately.',
      searchAliases: 'Li,lityum,LCE,spodumene',
      sortOrder: 50,
    }),
    row({
      code: 'iron',
      name: 'Iron Ore',
      nameTr: 'Demir Cevheri',
      symbol: 'Fe',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 105,
      gradeMin: 55,
      gradeMax: 65,
      gradeUnit: '% Fe',
      recoveryMinPct: 80,
      recoveryMaxPct: 95,
      densityTPerM3: 3.5,
      typicalProcessingMethod: 'Crushing, screening, beneficiation; pellets/sinter feed',
      typicalMiningMethods: 'openPit',
      typicalMineLifeYears: 25,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 15,
      royaltyDefaultPct: 4,
      environmentalRisk: 'medium',
      colorHex: '#8b4513',
      iconKey: 'mountain',
      notes: 'Benchmark ~62% Fe CFR China. Fines vs lump differential not modelled here.',
      searchAliases: 'Fe,demir,iron ore,hematite,magnetite',
      sortOrder: 60,
    }),
    row({
      code: 'coal',
      name: 'Coal',
      nameTr: 'Kömür',
      symbol: 'C',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 140,
      gradeMin: 5000,
      gradeMax: 6500,
      gradeUnit: 'kcal/kg',
      recoveryMinPct: 85,
      recoveryMaxPct: 95,
      densityTPerM3: 1.4,
      typicalProcessingMethod: 'ROM coal → crush/screen ± wash plant',
      typicalMiningMethods: 'openPit,underground',
      typicalMineLifeYears: 25,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 20,
      royaltyDefaultPct: 5,
      environmentalRisk: 'high',
      colorHex: '#2f2f2f',
      iconKey: 'flame',
      notes: 'Thermal coal Newcastle 6000 kcal/kg indicator. Coking coal is typically higher-priced.',
      searchAliases: 'kömür,thermal coal,coking coal',
      sortOrder: 70,
    }),
    row({
      code: 'zinc',
      name: 'Zinc',
      nameTr: 'Çinko',
      symbol: 'Zn',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 2800,
      gradeMin: 3,
      gradeMax: 10,
      gradeUnit: '%',
      recoveryMinPct: 80,
      recoveryMaxPct: 92,
      densityTPerM3: 3.0,
      typicalProcessingMethod: 'Flotation concentrate → roast/leach or ISP → SHG metal',
      typicalMiningMethods: 'underground,openPit',
      typicalMineLifeYears: 15,
      refiningCostUsdPerT: 200,
      smeltingCostUsdPerT: 180,
      payabilityPct: 85,
      transportationCostUsdPerT: 45,
      royaltyDefaultPct: 3,
      environmentalRisk: 'medium',
      colorHex: '#7f8c8d',
      iconKey: 'zinc',
      notes: 'Often co-mined with lead/silver. Concentrate treatment charges apply.',
      searchAliases: 'Zn,çinko',
      sortOrder: 80,
    }),
    row({
      code: 'lead',
      name: 'Lead',
      nameTr: 'Kurşun',
      symbol: 'Pb',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 2050,
      gradeMin: 2,
      gradeMax: 8,
      gradeUnit: '%',
      recoveryMinPct: 80,
      recoveryMaxPct: 92,
      densityTPerM3: 3.2,
      typicalProcessingMethod: 'Flotation → sinter/blast furnace or QSL → refined Pb',
      typicalMiningMethods: 'underground,openPit',
      typicalMineLifeYears: 15,
      refiningCostUsdPerT: 150,
      smeltingCostUsdPerT: 160,
      payabilityPct: 95,
      transportationCostUsdPerT: 40,
      royaltyDefaultPct: 3,
      environmentalRisk: 'high',
      colorHex: '#5d6d7e',
      iconKey: 'lead',
      notes: 'ESG and permitting sensitivity is elevated for Pb projects.',
      searchAliases: 'Pb,kurşun',
      sortOrder: 90,
    }),
    row({
      code: 'bauxite',
      name: 'Bauxite',
      nameTr: 'Boksit',
      symbol: 'Al',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 50,
      gradeMin: 40,
      gradeMax: 55,
      gradeUnit: '% Al2O3',
      recoveryMinPct: 85,
      recoveryMaxPct: 95,
      densityTPerM3: 1.8,
      typicalProcessingMethod: 'Selective mining → crush; alumina via Bayer process off-site',
      typicalMiningMethods: 'openPit',
      typicalMineLifeYears: 25,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 18,
      royaltyDefaultPct: 4,
      environmentalRisk: 'medium',
      colorHex: '#c4a484',
      iconKey: 'layers',
      notes: 'Mine-gate bauxite; alumina/aluminium smelting costs are downstream and not included.',
      searchAliases: 'boksit,alumina feedstock',
      sortOrder: 100,
    }),
    row({
      code: 'rareEarth',
      name: 'Rare Earth Elements',
      nameTr: 'Nadir Toprak Elementleri',
      symbol: 'REE',
      unit: 't',
      typicalSellingUnit: 'USD/kg TREO',
      typicalPriceUsd: 60,
      gradeMin: 0.5,
      gradeMax: 3,
      gradeUnit: '% TREO',
      recoveryMinPct: 50,
      recoveryMaxPct: 75,
      densityTPerM3: 2.8,
      typicalProcessingMethod: 'Beneficiation → cracking → solvent extraction separation',
      typicalMiningMethods: 'openPit',
      typicalMineLifeYears: 20,
      refiningCostUsdPerT: 8000,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 100,
      royaltyDefaultPct: 3,
      environmentalRisk: 'high',
      colorHex: '#9b59b6',
      iconKey: 'atom',
      notes: 'Basket price depends on NdPr vs Ce/La mix. Separation is the cost driver.',
      searchAliases: 'REE,nadir toprak,NdPr,TREO',
      sortOrder: 110,
    }),
    row({
      code: 'phosphate',
      name: 'Phosphate',
      nameTr: 'Fosfat',
      symbol: 'P',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 150,
      gradeMin: 20,
      gradeMax: 32,
      gradeUnit: '% P2O5',
      recoveryMinPct: 70,
      recoveryMaxPct: 90,
      densityTPerM3: 2.2,
      typicalProcessingMethod: 'Beneficiation to phosphate rock; phosphoric acid downstream',
      typicalMiningMethods: 'openPit',
      typicalMineLifeYears: 30,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 25,
      royaltyDefaultPct: 4,
      environmentalRisk: 'medium',
      colorHex: '#27ae60',
      iconKey: 'sprout',
      notes: 'Rock phosphate FOB indicator; fertilizer product prices differ.',
      searchAliases: 'fosfat,P2O5,phosphate rock',
      sortOrder: 120,
    }),
    row({
      code: 'uranium',
      name: 'Uranium',
      nameTr: 'Uranyum',
      symbol: 'U',
      unit: 'lb',
      typicalSellingUnit: 'USD/lb U3O8',
      typicalPriceUsd: 80,
      gradeMin: 0.05,
      gradeMax: 0.5,
      gradeUnit: '% U3O8',
      recoveryMinPct: 70,
      recoveryMaxPct: 90,
      densityTPerM3: 2.6,
      typicalProcessingMethod: 'Conventional mill or ISR (in-situ recovery)',
      typicalMiningMethods: 'underground,openPit',
      typicalMineLifeYears: 15,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: null,
      royaltyDefaultPct: 5,
      environmentalRisk: 'high',
      colorHex: '#f1c40f',
      iconKey: 'radiation',
      notes: 'Spot U3O8 indicator. ISR projects have different opex/capex profiles.',
      searchAliases: 'U3O8,uranyum,yellowcake',
      sortOrder: 130,
    }),
    row({
      code: 'potash',
      name: 'Potash',
      nameTr: 'Potasyum (Potash)',
      symbol: 'K',
      unit: 't',
      typicalSellingUnit: 'USD/t KCl',
      typicalPriceUsd: 300,
      gradeMin: 15,
      gradeMax: 25,
      gradeUnit: '% K2O',
      recoveryMinPct: 75,
      recoveryMaxPct: 90,
      densityTPerM3: 2.1,
      typicalProcessingMethod: 'Conventional UG or solution mining → flotation/crystallisation',
      typicalMiningMethods: 'underground',
      typicalMineLifeYears: 30,
      refiningCostUsdPerT: 40,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 35,
      royaltyDefaultPct: 3,
      environmentalRisk: 'low',
      colorHex: '#e67e22',
      iconKey: 'flask',
      notes: 'MOP (KCl) benchmark. Solution mining common in Saskatchewan-style deposits.',
      searchAliases: 'KCl,MOP,potasyum',
      sortOrder: 140,
    }),
    row({
      code: 'graphite',
      name: 'Graphite',
      nameTr: 'Grafit',
      symbol: 'C',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 700,
      gradeMin: 5,
      gradeMax: 20,
      gradeUnit: '% Cg',
      recoveryMinPct: 80,
      recoveryMaxPct: 92,
      densityTPerM3: 2.2,
      typicalProcessingMethod: 'Flotation concentrate; spherical/coated graphite is downstream',
      typicalMiningMethods: 'openPit,underground',
      typicalMineLifeYears: 20,
      refiningCostUsdPerT: 200,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 50,
      royaltyDefaultPct: 3,
      environmentalRisk: 'medium',
      colorHex: '#34495e',
      iconKey: 'hexagon',
      notes: 'Flake graphite concentrate indicator; battery anode (CSPG) prices are higher.',
      searchAliases: 'grafit,flake graphite,Cg',
      sortOrder: 150,
    }),
    row({
      code: 'tin',
      name: 'Tin',
      nameTr: 'Kalay',
      symbol: 'Sn',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 25000,
      gradeMin: 0.5,
      gradeMax: 2,
      gradeUnit: '%',
      recoveryMinPct: 60,
      recoveryMaxPct: 80,
      densityTPerM3: 3.0,
      typicalProcessingMethod: 'Gravity ± flotation concentrate → smelt to metal',
      typicalMiningMethods: 'underground,openPit',
      typicalMineLifeYears: 12,
      refiningCostUsdPerT: 400,
      smeltingCostUsdPerT: 500,
      payabilityPct: 90,
      transportationCostUsdPerT: 60,
      royaltyDefaultPct: 3,
      environmentalRisk: 'medium',
      colorHex: '#b0bec5',
      iconKey: 'package',
      notes: 'Alluvial tin has different recovery/cost structure than hard-rock cassiterite.',
      searchAliases: 'Sn,kalay,cassiterite',
      sortOrder: 160,
    }),
    row({
      code: 'molybdenum',
      name: 'Molybdenum',
      nameTr: 'Molibden',
      symbol: 'Mo',
      unit: 't',
      typicalSellingUnit: 'USD/lb',
      typicalPriceUsd: 20,
      gradeMin: 0.05,
      gradeMax: 0.25,
      gradeUnit: '%',
      recoveryMinPct: 70,
      recoveryMaxPct: 88,
      densityTPerM3: 2.7,
      typicalProcessingMethod: 'Cu-Mo flotation; Mo concentrate roasting to oxide',
      typicalMiningMethods: 'openPit,underground',
      typicalMineLifeYears: 20,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: 90,
      transportationCostUsdPerT: 80,
      royaltyDefaultPct: 3,
      environmentalRisk: 'medium',
      colorHex: '#6c7a89',
      iconKey: 'circles',
      notes: 'Price in USD/lb Mo. Often a by-product of porphyry copper.',
      searchAliases: 'Mo,molibden,moly',
      sortOrder: 170,
    }),
    row({
      code: 'chromium',
      name: 'Chromium',
      nameTr: 'Krom',
      symbol: 'Cr',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 300,
      gradeMin: 30,
      gradeMax: 45,
      gradeUnit: '% Cr2O3',
      recoveryMinPct: 75,
      recoveryMaxPct: 90,
      densityTPerM3: 3.8,
      typicalProcessingMethod: 'Dense media / gravity concentrate (chromite)',
      typicalMiningMethods: 'underground,openPit',
      typicalMineLifeYears: 15,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 40,
      royaltyDefaultPct: 4,
      environmentalRisk: 'medium',
      colorHex: '#1abc9c',
      iconKey: 'chrome',
      notes: 'Chromite concentrate 42–44% Cr₂O₃ indicator. Ferrochrome is downstream.',
      searchAliases: 'Cr,krom,chrome,chromite',
      sortOrder: 180,
    }),
    row({
      code: 'manganese',
      name: 'Manganese',
      nameTr: 'Manganez',
      symbol: 'Mn',
      unit: 't',
      typicalSellingUnit: 'USD/dmtu',
      typicalPriceUsd: 5,
      gradeMin: 30,
      gradeMax: 48,
      gradeUnit: '% Mn',
      recoveryMinPct: 80,
      recoveryMaxPct: 92,
      densityTPerM3: 3.4,
      typicalProcessingMethod: 'Crush/screen ± DMS; metallurgical or battery-grade paths',
      typicalMiningMethods: 'openPit,underground',
      typicalMineLifeYears: 18,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 30,
      royaltyDefaultPct: 3,
      environmentalRisk: 'medium',
      colorHex: '#e74c3c',
      iconKey: 'triangle',
      notes: 'Price often quoted USD/dmtu (dry metric tonne unit). Convert carefully for models.',
      searchAliases: 'Mn,manganez,manganese ore',
      sortOrder: 190,
    }),
    // Backward-compatible extras already used by the app UI / demos
    row({
      code: 'lignite',
      name: 'Lignite',
      nameTr: 'Linyit',
      symbol: 'C',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 35,
      gradeMin: 1800,
      gradeMax: 2800,
      gradeUnit: 'kcal/kg',
      recoveryMinPct: 90,
      recoveryMaxPct: 98,
      densityTPerM3: 1.2,
      typicalProcessingMethod: 'ROM lignite; limited washing',
      typicalMiningMethods: 'openPit',
      typicalMineLifeYears: 30,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 8,
      royaltyDefaultPct: 4,
      environmentalRisk: 'high',
      colorHex: '#5d4037',
      iconKey: 'flame',
      notes: 'Domestic low-rank coal; price is local/mine-mouth indicator.',
      searchAliases: 'linyit,brown coal',
      sortOrder: 200,
    }),
    row({
      code: 'boron',
      name: 'Boron',
      nameTr: 'Bor',
      symbol: 'B',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 700,
      gradeMin: 25,
      gradeMax: 35,
      gradeUnit: '% B2O3',
      recoveryMinPct: 80,
      recoveryMaxPct: 92,
      densityTPerM3: 2.0,
      typicalProcessingMethod: 'Crush → dissolve/crystallise refined borates',
      typicalMiningMethods: 'openPit',
      typicalMineLifeYears: 25,
      refiningCostUsdPerT: 120,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 30,
      royaltyDefaultPct: 4,
      environmentalRisk: 'medium',
      colorHex: '#16a085',
      iconKey: 'flask',
      notes: 'Refined borax-equivalent indicator; Türkiye is a major producer.',
      searchAliases: 'bor,borax,colemanite,B2O3',
      sortOrder: 210,
    }),
    row({
      code: 'marble',
      name: 'Marble',
      nameTr: 'Mermer',
      symbol: 'Ca',
      unit: 't',
      typicalSellingUnit: 'USD/t',
      typicalPriceUsd: 120,
      gradeMin: 90,
      gradeMax: 98,
      gradeUnit: '% CaCO3',
      recoveryMinPct: 40,
      recoveryMaxPct: 70,
      densityTPerM3: 2.7,
      typicalProcessingMethod: 'Block quarrying → cut/polish; or crushed aggregate',
      typicalMiningMethods: 'openPit',
      typicalMineLifeYears: 20,
      refiningCostUsdPerT: null,
      smeltingCostUsdPerT: null,
      payabilityPct: null,
      transportationCostUsdPerT: 25,
      royaltyDefaultPct: 2,
      environmentalRisk: 'low',
      colorHex: '#ecf0f1',
      iconKey: 'square',
      notes: 'Block marble pricing is highly quality-dependent; crushed stone is lower value.',
      searchAliases: 'mermer,dimension stone',
      sortOrder: 220,
    }),
  ];
}
