/**
 * Country Master Data seed rows — indicative mining-jurisdiction defaults
 * for techno-economic studies (order-of-magnitude, mid-2020s).
 * Not legal advice; royalty/tax regimes are simplified single rates.
 */

export interface CountryCatalogSeedRow {
  code: string;
  name: string;
  nameTr: string;
  currencyCode: string;
  corporateTaxPct: number;
  royaltyPct: number;
  inflationPct: number;
  discountRateRecommendation: number;
  dieselPriceUsdPerLiter: number;
  electricityCostUsdPerKwh: number;
  waterCostUsdPerM3: number;
  laborCostIndex: number;
  exchangeRateToUsd: number;
  environmentalCostIndex: number;
  infrastructureRating: number;
  miningInvestmentRisk: string;
  esgDifficulty: string;
  typicalPermittingYears: number;
  typicalRehabilitationCostUsdPerHa: number;
  politicalRisk: string;
  notes: string;
  searchAliases: string;
  isActive: boolean;
  sortOrder: number;
}

function row(
  partial: Omit<CountryCatalogSeedRow, 'isActive'> & { isActive?: boolean }
): CountryCatalogSeedRow {
  return { isActive: true, ...partial };
}

export function buildCountryCatalogSeedRows(): CountryCatalogSeedRow[] {
  return [
    row({
      code: 'CL',
      name: 'Chile',
      nameTr: 'Şili',
      currencyCode: 'CLP',
      corporateTaxPct: 27,
      royaltyPct: 3,
      inflationPct: 3.5,
      discountRateRecommendation: 8,
      dieselPriceUsdPerLiter: 1.1,
      electricityCostUsdPerKwh: 0.09,
      waterCostUsdPerM3: 1.5,
      laborCostIndex: 110,
      exchangeRateToUsd: 950,
      environmentalCostIndex: 115,
      infrastructureRating: 7.5,
      miningInvestmentRisk: 'medium',
      esgDifficulty: 'medium',
      typicalPermittingYears: 4,
      typicalRehabilitationCostUsdPerHa: 18000,
      politicalRisk: 'medium',
      notes: 'Major copper jurisdiction. Royalty simplified; actual regime is progressive on operating margin.',
      searchAliases: 'Şili,Chile,CL',
      sortOrder: 10,
    }),
    row({
      code: 'TR',
      name: 'Türkiye',
      nameTr: 'Türkiye',
      currencyCode: 'TRY',
      corporateTaxPct: 25,
      royaltyPct: 4,
      inflationPct: 25,
      discountRateRecommendation: 12,
      dieselPriceUsdPerLiter: 1.35,
      electricityCostUsdPerKwh: 0.12,
      waterCostUsdPerM3: 0.8,
      laborCostIndex: 70,
      exchangeRateToUsd: 34,
      environmentalCostIndex: 100,
      infrastructureRating: 6.5,
      miningInvestmentRisk: 'medium',
      esgDifficulty: 'medium',
      typicalPermittingYears: 3,
      typicalRehabilitationCostUsdPerHa: 12000,
      politicalRisk: 'medium',
      notes: 'State royalty rates vary by commodity group; 4% is a planning default. High inflation → higher discount rate.',
      searchAliases: 'Turkey,Türkiye,Turkiye,TR',
      sortOrder: 20,
    }),
    row({
      code: 'CA',
      name: 'Canada',
      nameTr: 'Kanada',
      currencyCode: 'CAD',
      corporateTaxPct: 26,
      royaltyPct: 5,
      inflationPct: 2.2,
      discountRateRecommendation: 7,
      dieselPriceUsdPerLiter: 1.25,
      electricityCostUsdPerKwh: 0.08,
      waterCostUsdPerM3: 1.2,
      laborCostIndex: 140,
      exchangeRateToUsd: 1.36,
      environmentalCostIndex: 130,
      infrastructureRating: 8.5,
      miningInvestmentRisk: 'low',
      esgDifficulty: 'high',
      typicalPermittingYears: 5,
      typicalRehabilitationCostUsdPerHa: 25000,
      politicalRisk: 'low',
      notes: 'Federal + provincial tax/royalty blend simplified. Strong ESG and Indigenous consultation expectations.',
      searchAliases: 'Kanada,Canada,CA',
      sortOrder: 30,
    }),
    row({
      code: 'AU',
      name: 'Australia',
      nameTr: 'Avustralya',
      currencyCode: 'AUD',
      corporateTaxPct: 30,
      royaltyPct: 5,
      inflationPct: 2.8,
      discountRateRecommendation: 7.5,
      dieselPriceUsdPerLiter: 1.3,
      electricityCostUsdPerKwh: 0.11,
      waterCostUsdPerM3: 1.8,
      laborCostIndex: 150,
      exchangeRateToUsd: 1.52,
      environmentalCostIndex: 125,
      infrastructureRating: 8.5,
      miningInvestmentRisk: 'low',
      esgDifficulty: 'high',
      typicalPermittingYears: 4.5,
      typicalRehabilitationCostUsdPerHa: 22000,
      politicalRisk: 'low',
      notes: 'State royalties differ (WA iron ore vs QLD coal). Figures are planning defaults.',
      searchAliases: 'Avustralya,Australia,AU',
      sortOrder: 40,
    }),
    row({
      code: 'PE',
      name: 'Peru',
      nameTr: 'Peru',
      currencyCode: 'PEN',
      corporateTaxPct: 29.5,
      royaltyPct: 3,
      inflationPct: 2.5,
      discountRateRecommendation: 9,
      dieselPriceUsdPerLiter: 1.15,
      electricityCostUsdPerKwh: 0.1,
      waterCostUsdPerM3: 1.0,
      laborCostIndex: 75,
      exchangeRateToUsd: 3.75,
      environmentalCostIndex: 110,
      infrastructureRating: 6,
      miningInvestmentRisk: 'medium',
      esgDifficulty: 'high',
      typicalPermittingYears: 4,
      typicalRehabilitationCostUsdPerHa: 15000,
      politicalRisk: 'medium',
      notes: 'Social licence and community agreements are often on the critical path.',
      searchAliases: 'Perú,Peru,PE',
      sortOrder: 50,
    }),
    row({
      code: 'BR',
      name: 'Brazil',
      nameTr: 'Brezilya',
      currencyCode: 'BRL',
      corporateTaxPct: 34,
      royaltyPct: 3,
      inflationPct: 4,
      discountRateRecommendation: 10,
      dieselPriceUsdPerLiter: 1.2,
      electricityCostUsdPerKwh: 0.1,
      waterCostUsdPerM3: 0.9,
      laborCostIndex: 85,
      exchangeRateToUsd: 5.1,
      environmentalCostIndex: 115,
      infrastructureRating: 6.5,
      miningInvestmentRisk: 'medium',
      esgDifficulty: 'medium',
      typicalPermittingYears: 4,
      typicalRehabilitationCostUsdPerHa: 16000,
      politicalRisk: 'medium',
      notes: 'CFEM royalty simplified. Iron ore and bauxite are major sectors.',
      searchAliases: 'Brezilya,Brasil,Brazil,BR',
      sortOrder: 60,
    }),
    row({
      code: 'US',
      name: 'USA',
      nameTr: 'ABD',
      currencyCode: 'USD',
      corporateTaxPct: 21,
      royaltyPct: 4,
      inflationPct: 2.5,
      discountRateRecommendation: 7,
      dieselPriceUsdPerLiter: 1.05,
      electricityCostUsdPerKwh: 0.09,
      waterCostUsdPerM3: 1.4,
      laborCostIndex: 145,
      exchangeRateToUsd: 1,
      environmentalCostIndex: 135,
      infrastructureRating: 8,
      miningInvestmentRisk: 'low',
      esgDifficulty: 'high',
      typicalPermittingYears: 6,
      typicalRehabilitationCostUsdPerHa: 28000,
      politicalRisk: 'low',
      notes: 'Federal + state royalties/taxes vary widely; NEPA-style timelines can be long.',
      searchAliases: 'United States,ABD,USA,US',
      sortOrder: 70,
    }),
    row({
      code: 'ZA',
      name: 'South Africa',
      nameTr: 'Güney Afrika',
      currencyCode: 'ZAR',
      corporateTaxPct: 27,
      royaltyPct: 5,
      inflationPct: 5,
      discountRateRecommendation: 11,
      dieselPriceUsdPerLiter: 1.2,
      electricityCostUsdPerKwh: 0.1,
      waterCostUsdPerM3: 1.1,
      laborCostIndex: 80,
      exchangeRateToUsd: 18.5,
      environmentalCostIndex: 105,
      infrastructureRating: 5.5,
      miningInvestmentRisk: 'medium',
      esgDifficulty: 'medium',
      typicalPermittingYears: 3.5,
      typicalRehabilitationCostUsdPerHa: 14000,
      politicalRisk: 'medium',
      notes: 'Power reliability and logistics can dominate opex risk for deep-level mines.',
      searchAliases: 'Güney Afrika,South Africa,RSA,ZA',
      sortOrder: 80,
    }),
    row({
      code: 'ID',
      name: 'Indonesia',
      nameTr: 'Endonezya',
      currencyCode: 'IDR',
      corporateTaxPct: 22,
      royaltyPct: 5,
      inflationPct: 3,
      discountRateRecommendation: 10,
      dieselPriceUsdPerLiter: 0.95,
      electricityCostUsdPerKwh: 0.1,
      waterCostUsdPerM3: 0.7,
      laborCostIndex: 55,
      exchangeRateToUsd: 15800,
      environmentalCostIndex: 100,
      infrastructureRating: 5.5,
      miningInvestmentRisk: 'medium',
      esgDifficulty: 'medium',
      typicalPermittingYears: 3.5,
      typicalRehabilitationCostUsdPerHa: 10000,
      politicalRisk: 'medium',
      notes: 'Downstreaming / export rules for Ni and other ores change frequently — verify policy.',
      searchAliases: 'Endonezya,Indonesia,ID',
      sortOrder: 90,
    }),
    row({
      code: 'KZ',
      name: 'Kazakhstan',
      nameTr: 'Kazakistan',
      currencyCode: 'KZT',
      corporateTaxPct: 20,
      royaltyPct: 4,
      inflationPct: 6,
      discountRateRecommendation: 11,
      dieselPriceUsdPerLiter: 0.7,
      electricityCostUsdPerKwh: 0.06,
      waterCostUsdPerM3: 0.5,
      laborCostIndex: 60,
      exchangeRateToUsd: 480,
      environmentalCostIndex: 90,
      infrastructureRating: 5.5,
      miningInvestmentRisk: 'medium',
      esgDifficulty: 'medium',
      typicalPermittingYears: 3,
      typicalRehabilitationCostUsdPerHa: 9000,
      politicalRisk: 'medium',
      notes: 'MET (mineral extraction tax) simplified into a single royalty proxy.',
      searchAliases: 'Kazakistan,Kazakhstan,KZ',
      sortOrder: 100,
    }),
    row({
      code: 'SE',
      name: 'Sweden',
      nameTr: 'İsveç',
      currencyCode: 'SEK',
      corporateTaxPct: 20.6,
      royaltyPct: 0.2,
      inflationPct: 2,
      discountRateRecommendation: 6.5,
      dieselPriceUsdPerLiter: 1.8,
      electricityCostUsdPerKwh: 0.08,
      waterCostUsdPerM3: 1.5,
      laborCostIndex: 160,
      exchangeRateToUsd: 10.5,
      environmentalCostIndex: 140,
      infrastructureRating: 9,
      miningInvestmentRisk: 'low',
      esgDifficulty: 'high',
      typicalPermittingYears: 7,
      typicalRehabilitationCostUsdPerHa: 30000,
      politicalRisk: 'low',
      notes: 'Very low mineral fee but long ESG/permitting timelines; high labour and rehab costs.',
      searchAliases: 'İsveç,Sweden,SE',
      sortOrder: 110,
    }),
    row({
      code: 'FI',
      name: 'Finland',
      nameTr: 'Finlandiya',
      currencyCode: 'EUR',
      corporateTaxPct: 20,
      royaltyPct: 0.15,
      inflationPct: 2,
      discountRateRecommendation: 6.5,
      dieselPriceUsdPerLiter: 1.75,
      electricityCostUsdPerKwh: 0.09,
      waterCostUsdPerM3: 1.4,
      laborCostIndex: 155,
      exchangeRateToUsd: 0.92,
      environmentalCostIndex: 140,
      infrastructureRating: 9,
      miningInvestmentRisk: 'low',
      esgDifficulty: 'high',
      typicalPermittingYears: 6,
      typicalRehabilitationCostUsdPerHa: 28000,
      politicalRisk: 'low',
      notes: 'Mining royalty/fee structure is light; permitting and ESG dominate schedule risk.',
      searchAliases: 'Finlandiya,Finland,FI',
      sortOrder: 120,
    }),
    row({
      code: 'MN',
      name: 'Mongolia',
      nameTr: 'Moğolistan',
      currencyCode: 'MNT',
      corporateTaxPct: 25,
      royaltyPct: 5,
      inflationPct: 8,
      discountRateRecommendation: 12,
      dieselPriceUsdPerLiter: 1.15,
      electricityCostUsdPerKwh: 0.08,
      waterCostUsdPerM3: 1.2,
      laborCostIndex: 50,
      exchangeRateToUsd: 3400,
      environmentalCostIndex: 95,
      infrastructureRating: 4.5,
      miningInvestmentRisk: 'high',
      esgDifficulty: 'medium',
      typicalPermittingYears: 3.5,
      typicalRehabilitationCostUsdPerHa: 8000,
      politicalRisk: 'high',
      notes: 'Logistics to China and winter climate are key cost drivers for bulk commodities.',
      searchAliases: 'Moğolistan,Mongolia,MN',
      sortOrder: 130,
    }),
    row({
      code: 'AR',
      name: 'Argentina',
      nameTr: 'Arjantin',
      currencyCode: 'ARS',
      corporateTaxPct: 35,
      royaltyPct: 3,
      inflationPct: 40,
      discountRateRecommendation: 14,
      dieselPriceUsdPerLiter: 1.1,
      electricityCostUsdPerKwh: 0.07,
      waterCostUsdPerM3: 0.9,
      laborCostIndex: 75,
      exchangeRateToUsd: 900,
      environmentalCostIndex: 105,
      infrastructureRating: 5.5,
      miningInvestmentRisk: 'high',
      esgDifficulty: 'medium',
      typicalPermittingYears: 4,
      typicalRehabilitationCostUsdPerHa: 11000,
      politicalRisk: 'high',
      notes: 'FX and inflation volatility are material; model in USD where possible. Lithium triangle province.',
      searchAliases: 'Arjantin,Argentina,AR',
      sortOrder: 140,
    }),
    row({
      code: 'MX',
      name: 'Mexico',
      nameTr: 'Meksika',
      currencyCode: 'MXN',
      corporateTaxPct: 30,
      royaltyPct: 7.5,
      inflationPct: 4,
      discountRateRecommendation: 9,
      dieselPriceUsdPerLiter: 1.15,
      electricityCostUsdPerKwh: 0.1,
      waterCostUsdPerM3: 1.0,
      laborCostIndex: 70,
      exchangeRateToUsd: 17.5,
      environmentalCostIndex: 110,
      infrastructureRating: 6.5,
      miningInvestmentRisk: 'medium',
      esgDifficulty: 'medium',
      typicalPermittingYears: 3.5,
      typicalRehabilitationCostUsdPerHa: 13000,
      politicalRisk: 'medium',
      notes: 'Includes mining royalty + mining duty simplified into a single royalty proxy (~7.5%).',
      searchAliases: 'Meksika,México,Mexico,MX',
      sortOrder: 150,
    }),
  ];
}
