import { slugifyEquipmentCode } from './validation';

/**
 * Production seed rows for the Equipment Catalog.
 *
 * Rules:
 * - Only include technical values we are reasonably confident about from public OEM specs.
 * - Unknown specs are null (never fabricated).
 * - List prices are indicative and always flagged isPriceEstimated=true.
 */

export interface EquipmentCatalogSeedRow {
  code: string;
  manufacturer: string;
  model: string;
  category: string;
  description: string;
  imageUrl: string;
  capacityLabel: string;
  payloadTons: number | null;
  bucketCapacityM3: number | null;
  enginePowerKw: number | null;
  operatingWeightTons: number | null;
  purchasePriceUsd: number | null;
  fuelConsumptionLph: number | null;
  fuelTankCapacityL: number | null;
  usefulLifeYears: number | null;
  availabilityPct: number | null;
  maintenanceCostUsdYear: number | null;
  isPriceEstimated: boolean;
  powerType: string;
  oemWebsite: string;
  country: string;
  notes: string;
  searchAliases: string;
  isActive: boolean;
  sortOrder: number;
}

type SeedInput = Omit<EquipmentCatalogSeedRow, 'code' | 'isActive' | 'sortOrder' | 'imageUrl'> & {
  imageUrl?: string;
};

function row(input: SeedInput, sortOrder: number): EquipmentCatalogSeedRow {
  return {
    code: slugifyEquipmentCode([input.category, input.manufacturer, input.model]),
    imageUrl: input.imageUrl ?? '',
    isActive: true,
    sortOrder,
    ...input,
  };
}

const PRICE_NOTE =
  'Purchase price is an approximate list-price estimate for feasibility studies (±15–25% typical variation by config/region).';

/**
 * Build the commercial equipment seed dataset.
 */
export function buildEquipmentCatalogSeedRows(): EquipmentCatalogSeedRow[] {
  const items: SeedInput[] = [
    // ——— Haul trucks ———
    {
      manufacturer: 'Caterpillar',
      model: '770G',
      category: 'truck',
      description: 'Rigid frame off-highway truck for quarry and small open-pit applications.',
      capacityLabel: '38.6 t nominal payload class',
      payloadTons: 38.6,
      bucketCapacityM3: null,
      enginePowerKw: 381,
      operatingWeightTons: null,
      purchasePriceUsd: 1_100_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: 530,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 44_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: PRICE_NOTE,
      searchAliases: 'CAT,Cat,Caterpillar',
    },
    {
      manufacturer: 'Caterpillar',
      model: '777G',
      category: 'truck',
      description: 'Widely used 100-ton class rigid haul truck for open-pit mining.',
      capacityLabel: '98.2 t nominal payload class',
      payloadTons: 98.2,
      bucketCapacityM3: null,
      enginePowerKw: 765,
      operatingWeightTons: null,
      purchasePriceUsd: 1_950_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: 1137,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 78_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: PRICE_NOTE,
      searchAliases: 'CAT,Cat,Caterpillar',
    },
    {
      manufacturer: 'Caterpillar',
      model: '793F',
      category: 'truck',
      description: 'Ultra-class rigid frame truck for large open-pit mines.',
      capacityLabel: '226.8 t nominal payload class',
      payloadTons: 226.8,
      bucketCapacityM3: null,
      enginePowerKw: 1976,
      operatingWeightTons: null,
      purchasePriceUsd: 5_500_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: 1893,
      usefulLifeYears: 12,
      availabilityPct: 85,
      maintenanceCostUsdYear: 220_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: PRICE_NOTE,
      searchAliases: 'CAT,Cat,Caterpillar',
    },
    {
      manufacturer: 'Komatsu',
      model: 'HD785-8',
      category: 'truck',
      description: '91-ton class rigid dump truck for mining and quarry.',
      capacityLabel: '91 t payload class',
      payloadTons: 91,
      bucketCapacityM3: null,
      enginePowerKw: 895,
      operatingWeightTons: null,
      purchasePriceUsd: 1_650_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 66_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.komatsu.com',
      country: 'Japan',
      notes: PRICE_NOTE,
      searchAliases: 'Komatsu',
    },
    {
      manufacturer: 'Komatsu',
      model: '930E-5',
      category: 'truck',
      description: 'Electric-drive ultra-class haul truck.',
      capacityLabel: '290 t payload class',
      payloadTons: 290,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 6_000_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 12,
      availabilityPct: 85,
      maintenanceCostUsdYear: 240_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.komatsu.com',
      country: 'Japan',
      notes: `${PRICE_NOTE} Engine power varies by engine option; left unspecified.`,
      searchAliases: 'Komatsu',
    },
    {
      manufacturer: 'Liebherr',
      model: 'T 264',
      category: 'truck',
      description: '240-ton class diesel-electric mining truck.',
      capacityLabel: '240 t payload class',
      payloadTons: 240,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 5_200_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 12,
      availabilityPct: 85,
      maintenanceCostUsdYear: 208_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.liebherr.com',
      country: 'Germany',
      notes: PRICE_NOTE,
      searchAliases: 'Liebherr',
    },
    {
      manufacturer: 'Hitachi',
      model: 'EH4000AC-3',
      category: 'truck',
      description: 'AC-drive rigid mining truck in the 220-ton class.',
      capacityLabel: '221 t payload class',
      payloadTons: 221,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 4_800_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 12,
      availabilityPct: 85,
      maintenanceCostUsdYear: 192_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.hitachicm.com',
      country: 'Japan',
      notes: PRICE_NOTE,
      searchAliases: 'Hitachi',
    },
    {
      manufacturer: 'Bell',
      model: 'B60E',
      category: 'truck',
      description: 'Articulated dump truck for rough-terrain mining and construction.',
      capacityLabel: '55 t payload class',
      payloadTons: 55,
      bucketCapacityM3: null,
      enginePowerKw: 430,
      operatingWeightTons: null,
      purchasePriceUsd: 750_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 8,
      availabilityPct: 85,
      maintenanceCostUsdYear: 30_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.bellequipment.com',
      country: 'South Africa',
      notes: PRICE_NOTE,
      searchAliases: 'Bell,Bell Equipment',
    },
    {
      manufacturer: 'XCMG',
      model: 'XDE160',
      category: 'truck',
      description: 'Electric-drive mining dump truck for medium open-pit fleets.',
      capacityLabel: '160 t payload class',
      payloadTons: 160,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 2_800_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 112_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.xcmg.com',
      country: 'China',
      notes: PRICE_NOTE,
      searchAliases: 'XCMG',
    },
    {
      manufacturer: 'SANY',
      model: 'SKT90S',
      category: 'truck',
      description: 'Off-highway mining dump truck for mid-size pits.',
      capacityLabel: '90 t payload class',
      payloadTons: 90,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_400_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 56_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.sanyglobal.com',
      country: 'China',
      notes: PRICE_NOTE,
      searchAliases: 'SANY,Sany',
    },

    // ——— Excavators ———
    {
      manufacturer: 'Caterpillar',
      model: '6015B',
      category: 'excavator',
      description: 'Hydraulic mining shovel / excavator for loading haul trucks.',
      capacityLabel: '~8 m³ class (configuration dependent)',
      payloadTons: null,
      bucketCapacityM3: 8,
      enginePowerKw: 615,
      operatingWeightTons: null,
      purchasePriceUsd: 2_800_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 112_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: `${PRICE_NOTE} Bucket capacity depends on attachment; ~8 m³ is a common configuration reference.`,
      searchAliases: 'CAT,Cat,Caterpillar',
    },
    {
      manufacturer: 'Komatsu',
      model: 'PC2000-11',
      category: 'excavator',
      description: 'Large mining hydraulic excavator.',
      capacityLabel: '~12 m³ class (configuration dependent)',
      payloadTons: null,
      bucketCapacityM3: 12,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 3_200_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 128_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.komatsu.com',
      country: 'Japan',
      notes: PRICE_NOTE,
      searchAliases: 'Komatsu',
    },
    {
      manufacturer: 'Hitachi',
      model: 'EX2600-7',
      category: 'excavator',
      description: 'Ultra-large mining excavator for high-production loading.',
      capacityLabel: '~15 m³ class (configuration dependent)',
      payloadTons: null,
      bucketCapacityM3: 15,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 4_500_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 12,
      availabilityPct: 85,
      maintenanceCostUsdYear: 180_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.hitachicm.com',
      country: 'Japan',
      notes: PRICE_NOTE,
      searchAliases: 'Hitachi',
    },
    {
      manufacturer: 'Liebherr',
      model: 'R 9800',
      category: 'excavator',
      description: 'Mining excavator for ultra-class truck loading.',
      capacityLabel: 'Mining excavator (bucket config dependent)',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 5_000_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 12,
      availabilityPct: 85,
      maintenanceCostUsdYear: 200_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.liebherr.com',
      country: 'Germany',
      notes: `${PRICE_NOTE} Detailed bucket/power figures omitted where configuration-specific.`,
      searchAliases: 'Liebherr',
    },
    {
      manufacturer: 'Volvo CE',
      model: 'EC950F',
      category: 'excavator',
      description: 'Large crawler excavator for quarry and mining support.',
      capacityLabel: '95 t operating-weight class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: 95,
      purchasePriceUsd: 1_100_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 44_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.volvoce.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Volvo,Volvo CE',
    },
    {
      manufacturer: 'SANY',
      model: 'SY1250H',
      category: 'excavator',
      description: 'Large hydraulic excavator for mining and heavy earthmoving.',
      capacityLabel: 'Large mining excavator class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_800_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 72_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.sanyglobal.com',
      country: 'China',
      notes: PRICE_NOTE,
      searchAliases: 'SANY,Sany',
    },

    // ——— Wheel loaders ———
    {
      manufacturer: 'Caterpillar',
      model: '988K',
      category: 'loader',
      description: 'Large wheel loader for load-and-carry and truck loading.',
      capacityLabel: '~6.9 m³ bucket class',
      payloadTons: null,
      bucketCapacityM3: 6.9,
      enginePowerKw: 403,
      operatingWeightTons: null,
      purchasePriceUsd: 1_300_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 52_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: PRICE_NOTE,
      searchAliases: 'CAT,Cat,Caterpillar',
    },
    {
      manufacturer: 'Caterpillar',
      model: '994K',
      category: 'loader',
      description: 'Ultra-large wheel loader for high-production mining.',
      capacityLabel: '~19 m³ bucket class',
      payloadTons: null,
      bucketCapacityM3: 19,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 5_000_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 12,
      availabilityPct: 85,
      maintenanceCostUsdYear: 200_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: PRICE_NOTE,
      searchAliases: 'CAT,Cat,Caterpillar',
    },
    {
      manufacturer: 'Komatsu',
      model: 'WA900-8',
      category: 'loader',
      description: 'Large mining wheel loader.',
      capacityLabel: 'Large wheel loader class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 2_200_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 88_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.komatsu.com',
      country: 'Japan',
      notes: PRICE_NOTE,
      searchAliases: 'Komatsu',
    },
    {
      manufacturer: 'Volvo CE',
      model: 'L350H',
      category: 'loader',
      description: 'Large wheel loader for quarry and mining.',
      capacityLabel: 'Large wheel loader class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_200_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 48_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.volvoce.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Volvo,Volvo CE',
    },
    {
      manufacturer: 'XCMG',
      model: 'LW1200KN',
      category: 'loader',
      description: 'Large wheel loader for heavy materials handling.',
      capacityLabel: 'Large wheel loader class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 650_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 26_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.xcmg.com',
      country: 'China',
      notes: PRICE_NOTE,
      searchAliases: 'XCMG',
    },

    // ——— Dozers ———
    {
      manufacturer: 'Caterpillar',
      model: 'D9T',
      category: 'dozer',
      description: 'Track-type tractor for pioneering, cleanup and dump maintenance.',
      capacityLabel: '~49 t operating-weight class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: 306,
      operatingWeightTons: 49,
      purchasePriceUsd: 1_300_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 52_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: PRICE_NOTE,
      searchAliases: 'CAT,Cat,Caterpillar',
    },
    {
      manufacturer: 'Caterpillar',
      model: 'D11',
      category: 'dozer',
      description: 'Largest CAT track-type tractor for mining applications.',
      capacityLabel: '~104 t operating-weight class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: 634,
      operatingWeightTons: 104,
      purchasePriceUsd: 2_500_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 12,
      availabilityPct: 85,
      maintenanceCostUsdYear: 100_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: PRICE_NOTE,
      searchAliases: 'CAT,Cat,Caterpillar',
    },
    {
      manufacturer: 'Komatsu',
      model: 'D375A-8',
      category: 'dozer',
      description: 'Large mining dozer for dump and road maintenance.',
      capacityLabel: '~72 t operating-weight class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: 72,
      purchasePriceUsd: 1_500_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 60_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.komatsu.com',
      country: 'Japan',
      notes: PRICE_NOTE,
      searchAliases: 'Komatsu',
    },
    {
      manufacturer: 'Liebherr',
      model: 'PR 776',
      category: 'dozer',
      description: 'Large crawler tractor for mining support.',
      capacityLabel: 'Large mining dozer class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_800_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 72_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.liebherr.com',
      country: 'Germany',
      notes: PRICE_NOTE,
      searchAliases: 'Liebherr',
    },

    // ——— Surface drills ———
    {
      manufacturer: 'Epiroc',
      model: 'Pit Viper 271',
      category: 'drill',
      description: 'Rotary blasthole drill for large open-pit benches.',
      capacityLabel: 'Ø171–270 mm rotary class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 3_500_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 12,
      availabilityPct: 85,
      maintenanceCostUsdYear: 140_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.epiroc.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Epiroc,Atlas Copco',
    },
    {
      manufacturer: 'Epiroc',
      model: 'SmartROC D65',
      category: 'drill',
      description: 'Surface top-hammer drill rig for quarrying and mining.',
      capacityLabel: 'Surface drill (hole diameter config dependent)',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 900_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 36_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.epiroc.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Epiroc',
    },
    {
      manufacturer: 'Sandvik',
      model: 'DR412i',
      category: 'drill',
      description: 'Intelligent rotary blasthole drill for surface mining.',
      capacityLabel: 'Rotary blasthole drill class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 2_800_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 12,
      availabilityPct: 85,
      maintenanceCostUsdYear: 112_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.sandvik.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Sandvik',
    },
    {
      manufacturer: 'Caterpillar',
      model: 'MD6250',
      category: 'drill',
      description: 'Rotary drill for mid-size surface mining.',
      capacityLabel: 'Surface rotary drill class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 2_200_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 88_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: PRICE_NOTE,
      searchAliases: 'CAT,Cat,Caterpillar',
    },

    // ——— Underground trucks ———
    {
      manufacturer: 'Sandvik',
      model: 'TH545i',
      category: 'undergroundTruck',
      description: 'Underground mining truck for ore and waste haulage.',
      capacityLabel: '45 t payload class',
      payloadTons: 45,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_500_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 60_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.sandvik.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Sandvik',
    },
    {
      manufacturer: 'Sandvik',
      model: 'TH663i',
      category: 'undergroundTruck',
      description: 'Higher-capacity underground truck.',
      capacityLabel: '63 t payload class',
      payloadTons: 63,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_900_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 76_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.sandvik.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Sandvik',
    },
    {
      manufacturer: 'Epiroc',
      model: 'Minetruck MT65',
      category: 'undergroundTruck',
      description: 'Underground articulated mining truck.',
      capacityLabel: '65 t payload class',
      payloadTons: 65,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_850_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 74_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.epiroc.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Epiroc',
    },
    {
      manufacturer: 'Caterpillar',
      model: 'AD45',
      category: 'undergroundTruck',
      description: 'Underground articulated truck for hard-rock mines.',
      capacityLabel: '45 t payload class',
      payloadTons: 45,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_400_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 56_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: PRICE_NOTE,
      searchAliases: 'CAT,Cat,Caterpillar',
    },

    // ——— Underground loaders (LHD) ———
    {
      manufacturer: 'Sandvik',
      model: 'LH517i',
      category: 'undergroundLoader',
      description: 'Intelligent LHD for underground production.',
      capacityLabel: '17 t tramming capacity class',
      payloadTons: 17,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_400_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 56_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.sandvik.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Sandvik,LHD',
    },
    {
      manufacturer: 'Sandvik',
      model: 'LH621i',
      category: 'undergroundLoader',
      description: 'Large intelligent LHD for high-production stopes.',
      capacityLabel: '21 t tramming capacity class',
      payloadTons: 21,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_700_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 68_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.sandvik.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Sandvik,LHD',
    },
    {
      manufacturer: 'Epiroc',
      model: 'Scooptram ST18',
      category: 'undergroundLoader',
      description: 'Underground loader (LHD) for production and development.',
      capacityLabel: '18 t class LHD',
      payloadTons: 18,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_350_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 54_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.epiroc.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Epiroc,Scooptram,LHD',
    },
    {
      manufacturer: 'Caterpillar',
      model: 'R1700',
      category: 'undergroundLoader',
      description: 'Underground LHD for hard-rock mining.',
      capacityLabel: 'Underground LHD class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_450_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 58_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.cat.com',
      country: 'USA',
      notes: PRICE_NOTE,
      searchAliases: 'CAT,Cat,Caterpillar,LHD',
    },

    // ——— Jumbos ———
    {
      manufacturer: 'Sandvik',
      model: 'DD422i',
      category: 'jumbo',
      description: 'Development drill jumbo for underground tunneling.',
      capacityLabel: '2-boom jumbo class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_200_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 48_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.sandvik.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Sandvik,Jumbo',
    },
    {
      manufacturer: 'Sandvik',
      model: 'DD422iE',
      category: 'jumbo',
      description: 'Battery-electric development jumbo.',
      capacityLabel: '2-boom electric jumbo class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_450_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 45_000,
      isPriceEstimated: true,
      powerType: 'electric',
      oemWebsite: 'https://www.sandvik.com',
      country: 'Sweden',
      notes: `${PRICE_NOTE} Electric variant — no diesel fuel consumption.`,
      searchAliases: 'Sandvik,Jumbo,electric',
    },
    {
      manufacturer: 'Epiroc',
      model: 'Boomer M2',
      category: 'jumbo',
      description: 'Face drilling jumbo for underground development.',
      capacityLabel: '2-boom jumbo class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 1_100_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 44_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.epiroc.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Epiroc,Boomer,Jumbo',
    },
    {
      manufacturer: 'Epiroc',
      model: 'Boomer S2',
      category: 'jumbo',
      description: 'Compact face drilling jumbo for narrower headings.',
      capacityLabel: '2-boom compact jumbo class',
      payloadTons: null,
      bucketCapacityM3: null,
      enginePowerKw: null,
      operatingWeightTons: null,
      purchasePriceUsd: 950_000,
      fuelConsumptionLph: null,
      fuelTankCapacityL: null,
      usefulLifeYears: 10,
      availabilityPct: 85,
      maintenanceCostUsdYear: 38_000,
      isPriceEstimated: true,
      powerType: 'diesel',
      oemWebsite: 'https://www.epiroc.com',
      country: 'Sweden',
      notes: PRICE_NOTE,
      searchAliases: 'Epiroc,Boomer,Jumbo',
    },
  ];

  return items.map((item, index) => row(item, index));
}
